<?php
/**
*
* acp_database.php [Sorani Kurdish]
*
* @package language
* @version $Id: $
* @copyright (c) 2009 phpBB Group
* @author 2009-06-06 - Chawg.org Group
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACP_BACKUP_EXPLAIN'	=> 'Here you can backup all your phpBB related data. You may store the resulting archive in your <samp>store/</samp> folder or download it directly. Depending on your server configuration you may be able to compress the file in a number of formats.',
	'ACP_RESTORE_EXPLAIN'	=> 'This will perform a full restore of all phpBB tables from a saved file. If your server supports it you may use a gzip or bzip2 compressed text file and it will automatically be decompressed. <strong>WARNING</strong> This will overwrite any existing data. The restore may take a long time to process please do not move from this page till it is complete. Backups are stored in the <samp>store/</samp> folder and are assumed to be generated by phpBB’s backup functionality. Restoring backups that were not created by the built in system may or may not work.',
	'BACKUP_DELETE'	=> 'پەڕگەی پشتگیری بە سەرکەوتوویی سڕدرایەوە.',
	'BACKUP_INVALID'	=> 'پەڕگەی دیاریکراو بۆ پشتگیری نەگونجاوە.',
	'BACKUP_OPTIONS'	=> 'هەڵبژاردنەکانی پشتگیری',
	'BACKUP_SUCCESS'	=> 'پەڕگەی پشتگیری بە سەرکەوتوویی دروستکرا.',
	'BACKUP_TYPE'	=> 'جۆری پشتگیری',
	'DATABASE'	=> 'Database utilities',
	'DATA_ONLY'	=> 'تەنها دراوە',
	'DELETE_BACKUP'	=> 'پشتگیری بسڕەوە',
	'DELETE_SELECTED_BACKUP'	=> 'دڵنیایت لە سڕینەوەی پەڕگەی پشتگیری دیاریکراو؟',
	'DESELECT_ALL'	=> 'هیچ دیاری مەکە',
	'DOWNLOAD_BACKUP'	=> 'پەڕگەی پشتگیری دابگرە',
	'FILE_TYPE'	=> 'جۆری پەڕگە',
	'FILE_WRITE_FAIL'	=> 'نەتوانرا پەڕگە بنووسرێت لە بوخچەی پاشەکەوت.',
	'FULL_BACKUP'	=> 'پڕ',
	'RESTORE_FAILURE'	=> 'لەوانەیە پەڕگەی پشتگیری تێکچووبێت.',
	'RESTORE_OPTIONS'	=> 'هەڵبژاردنەکان بگێڕەوە',
	'RESTORE_SUCCESS'	=> 'بنکەدراوە بە سەرکەوتوویی گێڕدرایەوە.<br /><br />مەکۆکەت پێویستە بگەڕێتەوە بۆ ئەو دۆخەی کە پەڕگەی پشتگیرییەکە دروستکرا.',
	'SELECT_ALL'	=> 'هەمووی دیاری بکە',
	'SELECT_FILE'	=> 'پەڕگەیەک دیاری بکە',
	'START_BACKUP'	=> 'دەست بە پشتگیری بکە',
	'START_RESTORE'	=> 'دەست بکە گێڕاندنەوە بکە',
	'STORE_AND_DOWNLOAD'	=> 'پاشەکەوتی بکە و دایبگرە',
	'STORE_LOCAL'	=> 'پەڕگەکە ناوخۆییانە پاشەکەوت بکە',
	'STRUCTURE_ONLY'	=> 'تەنها پێکهاتە.',
	'TABLE_SELECT'	=> 'دیاریکردنی خشتەکان',
	'TABLE_SELECT_ERROR'	=> 'پێویستە لانی کەم خشتەیەک دیاری بکەیت.',
));

?>
