<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Translated By SaM GoRaN',
	'DIRECTION'			=> 'ئەم وەرگێڕانە جاری یەکەمە و ئەگەری ئەوە هەیە هەلەی ڕێزمانی هەبێت و هیوادارم لەکەمو کوڕییەکانم ببورن ئەگەر هەبوو',
	'DATE_FORMAT'		=> '|23 11 2014|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|23 11 2014, 1:26 am|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'ku',
	'DIRECTION'			=> 'rtl',  //Bo KURDI 

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 ڕۆژ',
	'1_MONTH'		=> '1 مانگ',
	'1_YEAR'		=> '1 ساڵ',
	'2_WEEKS'		=> '2 هەفتە',
	'3_MONTHS'		=> '3 مانگ',
	'6_MONTHS'		=> '6 مانگ',
	'7_DAYS'		=> '7 ڕۆژ',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'ڕاژەکەت چاڵاکە.',
	'ACCOUNT_DEACTIVATED'			=> 'هەژمارەکەت ناچاڵاک بوو، تەنها دەستەی بەڕێوەبەران دەتوانن دووبارە  چاڵاکی بکەنەوە.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'ڕاژەکەت هێشتا چاڵاک نەکراوە.',
	'ACP'							=> 'پەڕەی سەرەکی بەڕێوەبردن',
	'ACP_SHORT'						=> 'بەڕێوەبردن',
	'ACTIVE'						=> 'چاڵاک',
	'ACTIVE_ERROR'					=> 'ناوی بەکارهێنەر هێشتا ناچاڵاکە. ئەگەر کێشەت هەیە لە چاڵاککردنی ڕاژەکەت، تکایە پەیوەندی بە بەڕێوەبەرایەتی بکە.',
	'ADMINISTRATOR'					=> 'بەڕێوەبەری گشتی',
	'ADMINISTRATORS'				=> 'بەڕێوەبەران',
	'AGE'							=> 'تەمەن',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX هەلەی',
	'AJAX_ERROR_TEXT'				=> 'هەڵەیەک ڕوویدا لە کاتی جێبەجێکردنی داواکارییەت.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'بەکارهێنەر داواکارییەکەی پەسەند نەکرد.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'داواکارییەکەت جێبەجێ نەکرا؛ تکایە دواتر هەولبدە.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'هەلەیەک ڕوویدا لەگەل داواکارییەکە و وەڵامێکی نادروست گەڕایەوە بۆ ڕاژە.',
	'ALLOWED'						=> 'ڕێگە پێدراو',
	'ALL_FILES'						=> 'سەرجەم پەڕگەکان',
	'ALL_FORUMS'					=> 'سەرجەم سەکۆکان',
	'ALL_MESSAGES'					=> 'سەرجەم پەیامەکان',
	'ALL_POSTS'						=> 'سەرجەم بەشدارییەکان',
	'ALL_TIMES'						=> 'سەرجەم کاتەکان <abbr title="%2$s">%1$s</abbr> بەکاردەبەن',
	'ALL_TOPICS'					=> 'سەرجەم بابەتەکان',
	'AND'							=> 'و',
	'ARE_WATCHING_FORUM'			=> 'هاوبەشیت کردووە بۆ ئاگەدارکردنەوە لە بەشدارییە نوێیەکانی ناو ئەم سەکۆیە.',
	'ARE_WATCHING_TOPIC'			=> 'هاوبەشیت کردووە بۆ ئاگەدارکردنەوە لە بەشدارییە نوێیەکانی ناو ئەم بابەتە.',
	'ASCENDING'						=> 'Ascending',
	'ATTACHMENTS'					=> 'هاوپێچەکان',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'وێنەی هاوپێچ هەلەیە.',
	'AUTHOR'						=> 'نووسەر',
	'AUTH_NO_PROFILE_CREATED'		=> 'هەلەیەک ڕوویدا لە دروستکردنی پەڕگەی بەکارهێنەر.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'تێکراوی بنکەی زانیاری بوونی نییە.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'جۆری خزمەتگوزاری بۆ OAuth بەردەست نییە.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'خزمەت گوزاری OAuth دروست نەکراوە',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth کۆدی پاشەکەوت بەکرا.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth بەجۆرێکی هەلە پاشەکەوتکرا.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'بارکرکردنەکە ڕەتکرایەوە چونکە فایلەکە زیان بەخشە.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'ئەم پەڕگەیە پیشان نادرێت چونکە ئەم پێوەکراوە <strong>%s</strong>ڕێگەی پێ نەدراوە.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'وێنۆچکەی دیاریکراو بار نەکرا، هەلەیەک لە جۆری وێنۆچکەکە هەیە تکایە دووبارە هەولدەوە.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'بارکردنی وێنۆچکە بەتالە.',
	'AVATAR_INVALID_FILENAME'		=> '%s ناوێکی هەلەیە.',
	'AVATAR_NOT_UPLOADED'			=> 'وێنۆچکە بار نەکرا.',
	'AVATAR_NO_SIZE'				=> 'بەرزی یان پانی بەستەری وێنۆچکە ناتوانرێت پێناسەی بکرێت. تکایە بە دەستکاریکردن بەکار بێنە.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'وێنەیەکی پارچەییت بارکرد.',
	'AVATAR_PHP_SIZE_NA'			=> 'قەبارەی وێنۆچکە زۆر گەورەیە.<br /> بەرزترین ئاست دیاریکراوە لەلایەن PHP.ini نەی توانی بیناسێت.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'قەبارەی وێنۆچکە زۆر گەورە. بەزترین ئاستی ڕێگەپێدراو بریتییە لە %1$d %2$s.<br />.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'وێنۆچکەی دیاریکراو نەهاتە بارکردن چونکە کات کۆتایی هات.',
	'AVATAR_URL_INVALID'			=> 'بەستەر هەلەیە.',
	'AVATAR_URL_NOT_FOUND'			=> 'پەڕگەی دیاری کراو نەدۆزرایەوە.',
	'AVATAR_WRONG_FILESIZE'			=> 'قەبارەی وێنۆچکە دەبێت لە نێوان 0 و %1$d %2$s بێت.',
	'AVATAR_WRONG_SIZE'				=> 'وێنۆچکەی دانراو بریتییە  لە %5$s وێنەخال و درێژییەکەی %6$s وێنەخال. پێویستە وێنۆچکە بەلایەنی کەم %1$s وێنەخال و درێژییەکەی %2$s بێت وە زۆربەی کات ڕووبەرەکەی %3$s وێنەخال و درێژی %4$s وێنەخال.',

	'BACK_TO_TOP'			=> 'لووتکە',
	'BACK_TO_PREV'			=> 'گەڕانەوەی بۆ پەڕەی دواوە',
	'BAN_TRIGGERED_BY_EMAIL'=> 'قەدەغەکردنەکە بەهۆی پۆستی ئەلیکترۆنییەوە بوو.',
	'BAN_TRIGGERED_BY_IP'	=> 'قەدەغەکردنەکە بەهۆی ئای پیەکەت بوو.',
	'BAN_TRIGGERED_BY_USER'	=> 'قەدەغەکردنەکە بەهۆی ناوی بەکارهێنەرت بوو.',
	'BBCODE_GUIDE'			=> 'BBCode ڕێبەری',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'ڕۆژی لەدایکبووان',
	'BOARD_BAN_PERM'		=> 'تۆ بەشێوەیەکی <strong>هەمیشەیی</strong> قەدەغەکرای لەم سەکۆیە.<br /><br />تکایە پەیوەندی بکە بە %2$sپەڕەی بەڕێوەبەرایەتی%3$s بۆ زانیاری زیاتر.',
	'BOARD_BAN_REASON'		=> 'هۆکاری قەدەغەکردنەکە: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'تۆ لەم سەکۆیە قەدەغەکرای تا <strong>%1$s</strong>.<br /><br />تکایە پەیوەندی بکە بە %2$sپەڕەی بەڕێوەبەر%3$s بۆ زانیاری زیاتر.',
	'BOARD_DISABLE'			=> 'ببورە ئەم سەکۆیە بەردەست نییە.',
	'BOARD_DISABLED'		=> 'ئەم سەکۆیە لەکار کەوتووە.',
	'BOARD_UNAVAILABLE'		=> 'ببورە، سەکۆ بۆ ماوەیەکی کاتی ڕاگیرا,تکایە لە کاتێکی تر سەردانمان بکەوە.',
	'BROWSING_FORUM'		=> 'ئەو بەکارهێنەرانەی ئەم سەکۆیەیان کردۆتەوە: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'ئەو بەکارهێنەرانەی ئەم سەکۆیەیان کردۆتەوە: %2$s و %1$d میوان',
		2	=> 'ئەو بەکارهێنەرانەی ئەم سەکۆیەیان کردۆتەوە: %2$s و%1$d میوان',
	),
	'BUTTON_EDIT'			=> 'دەستکاریکردن',
	'BUTTON_FORUM_LOCKED'	=> 'داخراو',
	'BUTTON_NEW_TOPIC'		=> 'بابەتی نوێ',
	'BUTTON_PM'				=> 'پەیامی تایبەتی',
	'BUTTON_PM_FORWARD'		=> 'ناردن',
	'BUTTON_PM_NEW'			=> 'پەیامی تابەتی نوێ',
	'BUTTON_PM_REPLY'		=> 'ناردنی وەڵام',
	'BUTTON_PM_REPLY_ALL'	=> 'وەڵام دانەوەی گشتی',
	'BUTTON_POST_REPLY'		=> 'زیادکردنی وەڵام',
	'BUTTON_QUOTE'			=> 'دەق',
	'BUTTON_TOPIC_LOCKED'	=> 'داخراو',
	'BYTES'					=> 'Bytes',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> 'داخستن',
	'CHANGE'				=> 'گۆڕین',
	'CHANGE_FONT_SIZE'		=> 'گۆڕینی قەبارەی فۆنت',
	'CHANGING_PREFERENCES'	=> 'گۆڕینی ڕێکخستنەکانی سەکۆ',
	'CHANGING_PROFILE'		=> 'گۆڕینی ڕێکخستنەکانی پەڕەی تایبەتی',
	'CHARACTERS'			=> array(
		1	=> '%d پیت',
		2	=> '%d پیت',
	),
	'COLLAPSE_VIEW'			=> 'بینینی بچوککراو',
	'CLOSE_WINDOW'			=> 'داخستن',
	'COLOUR_SWATCH'			=> 'لیستی ڕەنگەکان',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'بەڵێ کردن',
	'CONFIRM_CODE'			=> 'بەڵێ کردنی کۆد',
	'CONFIRM_CODE_EXPLAIN'	=> 'کۆدەکە بنووسەوە وەک چۆن دەرکەوتووە.',
	'CONFIRM_CODE_WRONG'	=> 'ئەو کۆدەی نووسیوتە هەلەیە.',
	'CONFIRM_OPERATION'		=> 'ئایە تۆ دڵنیایت لە جێ بەجێکردنی ئەم کردارە?',
	'CONFIRM_AVATAR_DELETE' => 'ئایە تۆ دڵنیایت لە سڕینەوەی وێنۆچکە?',
	'CONGRATULATIONS'		=> 'پیرۆزە لە',
	'CONNECTION_FAILED'		=> 'هەلە لە پەیوەندی.',
	'CONNECTION_SUCCESS'	=> 'بەسەرکەوتویی پەیوەندی کرا!',
	'CONTACT'				=> 'پەیوەندی',
	'CONTACT_USER'			=> 'پەیوەندی %s',
	'CONTACT_US'			=> 'پەیوەندیمان پێ بکە ',
	'COOKIES_DELETED'		=> 'سەرجەم کوکیزەکان سڕانەوە.',
	'CURRENT_TIME'			=> 'ئەمڕۆ بریتییە لە %s',

	'DAY'					=> 'ڕۆژ',
	'DAYS'					=> 'ڕۆژ',
	'DELETE'				=> 'سڕینەوە',
	'DELETE_ALL'			=> 'سڕینەوەی گشتی',
	'DELETE_COOKIES'		=> 'سڕینەوەی سەرجەم کۆکیزەکانی سەکۆ',
	'DELETE_MARKED'			=> 'سڕینەوەی دیاریکراوەکان',
	'DELETE_POST'			=> 'سڕینەوەی بەشداری',
	'DELIMITER'				=> 'جياكەرەوە',
	'DESCENDING'			=> 'سەربەرەوخوار',
	'DISABLED'				=> 'ناچالاککراو',
	'DISPLAY'				=> 'پیشان دان',
	'DISPLAY_GUESTS'		=> 'پیشان دانی میوانەکان ',
	'DISPLAY_MESSAGES'		=> ' پیشان دانی پەیامەکانی ڕابردوو لەوەتەی',
	'DISPLAY_POSTS'			=> 'پیشان دانی بەشدارییەکانی ڕابردوو لەوەتەی ',
	'DISPLAY_TOPICS'		=> 'پیشان دانی بابەتەکانی ڕابردوو لەوەتەی ',
	'DOWNLOADED'			=> 'داگرتن',
	'DOWNLOADING_FILE'		=> 'داگرتنی پەڕگە',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'هێشتا دانەگیراوە',
		1	=> ' %d جار داگیراوە',
		2	=> ' %d جار داگیراوە',
	),

	'EDIT_POST'							=> 'دەستکاریکردنی بەشداری',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> 'پۆستی ئەلیکترۆنی ', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'پۆستی ئەلیکترۆنی',
	'EMAIL_INVALID_EMAIL'				=> 'ئەو پۆستە ئەلیکترۆنیەی نووسیوتە هەلەیە.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'کێشەیەک هەیە لە ناردنی پۆستی ئەلیکترۆنی لە <strong>دێڕ %1$s</strong>. وەڵام دانەوە: %2$s.',
	'EMPTY_SUBJECT'						=> 'پێویستە ناونیشانێک بۆ بابەتەکەت دابنێیت پێش ناردن.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'پێویستە ناونیشانێک بۆ پەیامەکەت دابنێیت پێش ناردن.',
	'ENABLED'							=> 'چاڵاک',
	'ENCLOSURE'							=> 'گەمارۆدان',
	'ENTER_USERNAME'					=> 'ناوی بەکارهێنەر بنووسە',
	'ERR_CHANGING_DIRECTORY'			=> 'ناتوانرێت ڕێڕەو بگۆڕدرێت.',
	'ERR_CONNECTING_SERVER'				=> 'هەلەیەک ڕوویدا لە پەیوەندی کردن بە ڕاژەوە.',
	'ERR_JAB_AUTH'						=> 'بەکارهێنانی ڕاژەی   Jabber ڕێگە پێنەدراوە.',
	'ERR_JAB_CONNECT'					=> 'ناتوانرێت پەیوەندی بە ڕاژەی Jabber بکات.',
	'ERR_UNABLE_TO_LOGIN'				=> 'ناو یان تێپەڕەووشە هەلەیە.',
	'ERR_UNWATCHING'					=> 'هەلەیەک ڕوویدا لەکاتی لادانی هاوبەشی کردن.',
	'ERR_WATCHING'						=> 'هەلەیەک ڕوویدا لە کاتی هەولدانی هاوبەشی کردن.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'پێ دەچێت ڕێڕوەی phpBB دیاریکراو هەلەبێت.',
	'ERROR'									=> 'هەڵه',
	'EXPAND_VIEW'						=> 'بینینی فراوان',
	'EXTENSION'							=> 'پێوەکراو',
	'EXTENSION_DISABLED'				=> 'پێوەکراوی <strong>%s</strong> بەردەست نییە.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'پێوەکراوی <strong>%s</strong> ناچاڵاککراوە و چیتر دەرناکەوێت.',
	'EXTENSION_DOES_NOT_EXIST'			=> ' پێوەکراوی <strong>%s</strong> بوونی نییە.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'					=> 'FAQ',
	'FAQ_EXPLAIN'			=> 'پرسیاری هەمیشە دووبارە',
	'FILENAME'				=> 'ناوی پەڕگە',
	'FILESIZE'				=> 'قەبارەی پەڕگە',
	'FILEDATE'				=> 'بەرواری پەڕگە',
	'FILE_COMMENT'			=> 'لێدوان',
	'FILE_CONTENT_ERR'		=> 'نەتوانرا ناوەڕۆکی پوڕگەی : %s بخوێندرێتەوە',
	'FILE_JSON_DECODE_ERR'	=> 'کۆدهەڵوەشاندنەوەی پەڕگەی json : %s سەرکەوتوو نەبوو',
	'FILE_NOT_FOUND'		=> 'پەڕگەی داواکراو نەدۆزرایەوە: %s',
	'FIND_USERNAME'			=> 'دۆزینەوەی ژمارە',
	'FOLDER'				=> 'بوخچە',
	'FORGOT_PASS'			=> 'تێپەڕەووشەم لەیاد کردووە',
	'FORM_INVALID'			=> 'فۆرم نێردراو هەلەیە. دووبارە هەولی ناردنی بدە.',
	'FORUM'					=> 'بەش',
	'FORUMS'				=> 'بەشەکان',
	'FORUMS_MARKED'			=> 'بەشەکانی وەک خوێندراو دیاریکراوە.',
	'FORUM_CAT'				=> 'هاوپۆلەکان',
	'FORUM_INDEX'			=> 'لیستی سەکۆ',
	'FORUM_LINK'			=> 'بەستەری سەکۆ',
	'FORUM_LOCATION'		=> 'شوێنی سەکۆ',
	'FORUM_LOCKED'			=> 'سەکۆ داخراوە',
	'FORUM_RULES'			=> 'یاساکانی سەکۆ',
	'FORUM_RULES_LINK'		=> 'تکایە ئێرە داگرە بۆ بینینی یاساکانی سەکۆ',
	'FROM'					=> 'لە',
	'FSOCK_DISABLED'		=> 'ناتوانرێت پرۆسەکە بەردەوام بێت چونکە کرداری <var>fsockopen</var> لەکار کەوت یان ڕاژە پالپشتی ئەم کردارە ناکات.',
	'FSOCK_TIMEOUT'			=> 'کات تەواوبوو لە ماوەی خوێندەوەی زانیارییەکان لە تۆڕ.',

	'FTP_FSOCK_HOST'				=> 'FTP host',
	'FTP_FSOCK_HOST_EXPLAIN'		=> ' ڕاژەی FTP بەکارهات بۆ پەیوەندی کردن بە وێبگەگەت.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP تێپەڕەووشەی',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'تێپەڕەووشە بۆ نازناوی FTP خۆت.',
	'FTP_FSOCK_PORT'				=> 'FTP port',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Port بەکارهێنراوبۆ پەیوەندی کردن بە وێبگەگەت.',
	'FTP_FSOCK_ROOT_PATH'			=> 'ڕێڕەو بۆ  phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'ڕێڕەو لە root بۆ پەڕەی phpBB تایبەتیت.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP کات بەسەر چوو',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'The amount of time, in seconds, that the system will wait for a reply from your server.',
	'FTP_FSOCK_USERNAME'			=> 'FTP نازناوی',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'نازناو بەکارهات بۆ پەیوەندی کردن بە ڕاژەکەت.',

	'FTP_HOST'					=> 'FTP host',
	'FTP_HOST_EXPLAIN'			=> ' ڕاژەی FTP server بەکارهات بۆ پەیوەندی کردن بە وێبگەگەت.',
	'FTP_PASSWORD'				=> 'FTP تێپەڕەووشەی',
	'FTP_PASSWORD_EXPLAIN'		=> 'تێپەڕەووشە بۆ نازناوی FTP خۆت.',
	'FTP_PORT'					=> 'FTP port',
	'FTP_PORT_EXPLAIN'			=> 'Port بەکارهێنراو بۆ ڕاژەکەت.',
	'FTP_ROOT_PATH'				=> 'ڕێڕەو بۆ phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'ڕێڕەو لە root بۆ پەڕی phpBB تابەتیت.',
	'FTP_TIMEOUT'				=> 'FTP کات بەسەرچوو',
	'FTP_TIMEOUT_EXPLAIN'		=> 'The amount of time, in seconds, that the system will wait for a reply from your server.',
	'FTP_USERNAME'				=> 'FTP ناوی بەکارهێنەری',
	'FTP_USERNAME_EXPLAIN'		=> 'ناوی بەکارهێنەری بەکارهێنراو بۆ پەیوەندی کردن بە ڕاژە.',

	'GENERAL_ERROR'				=> 'هەڵەی گشتی',
	'GB'						=> 'گیگابایت',
	'GIB'						=> 'GiB',
	'GO'						=> 'بڕۆ',
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'بڕۆ بۆ یەکەم بەشداری',
	'GOTO_LAST_POST'			=> 'بڕۆ بۆ دوایین بەشداری',
	'GOTO_PAGE'					=> 'بڕۆ بۆ پەڕە',
	'GROUP'						=> 'گرووپ',
	'GROUPS'					=> 'گرووپەکان',
	'GROUP_ERR_TYPE'			=> 'جۆری گرووپەکە گونجاو نییە.',
	'GROUP_ERR_USERNAME'		=> 'ناو بۆ گرووپەکە دیاری نەکرا.',
	'GROUP_ERR_USER_LONG'		=> 'ناوی گرووپ زۆر درێژە.',
	'GUEST'						=> 'میوان',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> 'ئێستا  %d  میوان لەسەر هێلە',
		2	=> 'ئێستا %d  میوان لەسەر هێلە',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d میوان',
		2	=> '%d میوان',
	),
	'G_ADMINISTRATORS'			=> 'بەڕێوەبەر',
	'G_BOTS'					=> 'گەڕۆکەکان',
	'G_GUESTS'					=> 'میوانان',
	'G_REGISTERED'				=> 'ئەندامانی تۆماربوو',
	'G_REGISTERED_COPPA'		=> 'ئەندامانی خوار 13 ساڵ',
	'G_GLOBAL_MODERATORS'		=> 'بەڕێوەبەری گشتی',
	'G_NEWLY_REGISTERED'		=> 'نوێترین ئەندام',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d ئەندامی شارەوە',
		2	=> '%d ئەندامی شارەوە',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d شارەوە',
		2	=> '%d شارەوە',
	),
	'HIDE_GUESTS'					=> 'میوانی شاراوە',
	'HIDE_ME'						=> 'منی وەک شارەوە پیشان بدە',
	'HOURS'							=> 'کاتژمێر',
	'HOME'							=> 'دەستپێک',

	'ICQ'						=> 'ICQ',
	'IF'						=> 'ئەگەر',
	'IMAGE'						=> 'وێنە',
	'IMAGE_FILETYPE_INVALID'	=> 'جۆری پەڕگەی وێنە %d لە جۆری وێنە  %s پالپشتی نەکراوە.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'جۆری پەڕگە ناگونجێت: جۆری گونجاو %1$s بەلا هی تۆ %2$s',
	'IN'						=> 'لە',
	'INDEX'						=> 'پەڕەی سەرەکی',
	'INFORMATION'				=> 'زانیاری',
	'INSECURE_REDIRECT'			=> 'هەولی کردنەوەی بەستەرێکی نا پارێزراو درا.',
	'INTERESTS'					=> 'گرینگیدانەکان',
	'INVALID_DIGEST_CHALLENGE'	=> 'نادروستە digest challenge.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> لەوانەیە پۆستی ئەلیکترۆنی هەلە بێت?',
	'INVALID_PLURAL_RULE'		=> ' بنکەی کۆکردنەوەی هەلبژێردراو هەلەیە، نرخی دروست دەبێت پێکهاتبێت لە ژمارەیەک لە نێوان  0 و 15.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> 'ناونیشانی ip تایبەتییەکەت  %1$s ڕاگیرا چونکە لە لیستی ڕەشدایە. بۆ زانیاری زیاتر تکایە پێداچونەوەی <a href="%2$s">%2$s</a> بکە',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'ئەندامە لە',
	'JUMP_PAGE'				=> 'ژمارەی ئەو لاپەڕەیە بنووسە کە دەتەوێ بۆی بچی',
	'JUMP_TO'				=> 'گواستنەوە بۆ',
	'JUMP_TO_PAGE'			=> 'گواستنەوە بۆ پەڕە',
	'JUMP_TO_PAGE_CLICK'	=> 'کرتە بکە بۆ چوونە سەر پەڕە…',

	'KB'					=> 'کیلۆباتر',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'دوایین بەشداری',
	'LAST_UPDATED'						=> 'دوایین نوێکردنەوە',
	'LAST_VISIT'						=> 'دوایین سەردان',
	'LDAP_NO_LDAP_EXTENSION'			=> ' پێوەکراوی LDAP بەردەست نییە.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'ناتوانرێت پەیوەندی بکرێت بە ڕاژەی LDAP .',
	'LDAP_SEARCH_FAILED'				=> 'هەلەیەک ڕوویدا لە کاتی گەڕان بەدوای ڕێڕەوی LDAP .',
	'LEGEND'							=> 'ڕەنگی گروپەکان',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'گەڕانی زیندو ڕێ پێدراو نییە.',
	'LOADING'							=> 'ئامادەکردن',
	'LOCATION'							=> 'شوێن',
	'LOCK_POST'							=> 'داخستنی بەشداری',
	'LOCK_POST_EXPLAIN'					=> 'قەدەغەکردنی دەستکاریکردن',
	'LOCK_TOPIC'						=> 'داخستنی بابەت',
	'LOGIN'								=> 'چوونەژوور',
	'LOGIN_CHECK_PM'					=> 'چوونەژوورەوە بۆ بینینی پەیامی تایبەتی.',
	'LOGIN_CONFIRMATION'				=> 'دڵنیاکردنەوەی چوونە ژوورەوە',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'بۆ ڕێگرتن لە هەولی هاککردنی هەژمارەکان بەشێوەیەکی خۆکارانە، سەکۆ داوای تێکردنی کۆدی پاراستن دەکات، دوای بەکارهێنانی هەموو هەولەکانی چوونە ژوور، کۆدی پاراستنی لە ژێر وێنەکەدایە. ئەگەر ناتوانیت کۆدەکان بخوێنیتەوە تکایە پەیوەندی بکە بە %sبەڕێوەبەری سەکۆ %s.',
	// unused
	'LOGIN_ERROR_ATTEMPTS'				=> ' ئاستی ڕێگەپێدراوت تێ پەڕاند بۆ چوونە ژوورەوە. ئێستا وێڕای ناوی بەکارهێنەر و تێپەڕەووشە پێویستە لەسەرت چارەسەر کۆدی پاراستنیش بکەی کە لەخوارەوەیە.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'دەسەلاتت نییە لەلایەن ئەپاچی.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'داوای خزمەتگوزارییەکت کرد  OAuth کە بەردەست نییە.',
	'LOGIN_ERROR_PASSWORD'				=> 'تێپەڕەووشەی هەڵەت بەکارهێناوە.تکایە دووبارە هەوڵدەوە. ئەگەر کێشەکە هەر بەردەوام بوو تکایە پەیوندی بکە بە %s بەڕێوەبەری سەکۆ %s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'ناکرێت تێپەڕەووشە بگوازییەوە لەکایئ نوێکردنەوەی سیستەمی سەکۆکان. تکایە داوای  %s تێپەڕەووشەی نوێ %s بکە. ئەگەر هێشتا کێشەکە ڕووبەڕووت دەبێتەوە تکایە پەیوەندی بکە بە %sبەڕێوەبەرایەتی وێبگە%s',
	'LOGIN_ERROR_USERNAME'				=> 'ناوی بەکارهێنەری هەڵەت بەکارهێناوە.تکایە دووبارە هەوڵدەوە. ئەگەر کێشەکە هەر بەردەوام بوو تکایە پەیوندی بکە بە %s بەڕێوەبەری سەکۆ %s.',
	'LOGIN_FORUM'						=> 'بۆ بینین یان بەشداری کردن لەم سەکۆیە پێویستە تێپەڕەووشەکەی بنووسیت.',
	'LOGIN_INFO'						=> 'پێویستە تۆمارکرابی بۆ ئەوەی بتوانیت بێیتە ژوور. خۆتۆمارکردن هیچت لێ نابات تەنها چەن خولەکێک مەبێت و زۆر شتی باشترت پێ دەدات. وە لەوانەیە بەڕێوەبەرایەتی سەکۆ دەسەلاتی زیاتر بە ئەندامانی تۆماربوو بەخشی بێت، پێش خۆتۆمارکردن دڵنیابە لەوەی کە مەرج و یاساکانی سەکۆت خوێندوەتەوە و ڕازیت لەسەریان. تکایە دڵنیابەوە لە مەرجی سەرجەم بەشەکان پێش ئەوەی بەشداری تێدا بکەی.',
	'LOGIN_VIEWFORUM'					=> 'پێویستە ئەندامێکی تۆمارکراو بیت تا بتوانیت ئەم سەکۆیە ببینیت.',
	'LOGIN_EXPLAIN_EDIT'				=> 'بۆ ئەوەی بتوانی دەستکاری بەشدارییەکانت بکەیت پێویستە ببی بە ئەندام لە سەکۆ.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'بۆ ئەوەی سەیری لیستی ئامادەبووان بکەیت پێویستە خۆت تۆمار بکەیت و بێیتە ژوورەوە.',
	'LOGIN_REQUIRED'					=> 'پێویستە بێیتە ژوورەوە بۆ جێ بەجێکردنی ئەم کارە.',
	'LOGOUT'							=> 'دەرچوون',
	'LOGOUT_USER'						=> 'دەرچوون [ %s ]',
	'LOG_ME_IN'							=> 'منت لەبیربێت',

	'MAIN'					=> 'دەستپێک',
	'MARK'					=> 'دیاریکردن',
	'MARK_ALL'				=> 'دیاری کردنی گشتی',
	'MARK_ALL_READ'			=> 'هەموویان وەک خوێندراو دیاری بکە',
	'MARK_FORUMS_READ'		=> 'سەکۆ وەک خوێندراو دیاری بکە',
	'MARK_READ'				=> 'وەک خوێندراو دیاری بکە',
	'MARK_SUBFORUMS_READ'	=> 'سەکۆ ناوخۆییەکان وەک خوێندرا دیاری بکە',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'پەڕەی بەڕێوەبەر',
	'MCP_SHORT'				=> 'سەرپەرشتیارێتی',
	'MEMBERLIST'			=> 'ئەندامان',
	'MEMBERLIST_EXPLAIN'	=> 'بینینی سەرجەم ئەندامان',
	'MERGE'					=> 'لکاندن',
	'MERGE_POSTS'			=> 'گواستنەوەی بابەت',
	'MERGE_TOPIC'			=> 'لکاندنی بابەت',
	'MESSAGE'				=> 'پەیام',
	'MESSAGES'				=> 'پەیامەکان',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d پەیام',
		2	=> '%d پەیامەکان',
	),
	'MESSAGE_BODY'			=> 'پەیکەری پەیام',
	'MINUTES'				=> 'چرکە',
	'MODERATE'				=> 'بەرێوەبەر',
	'MODERATOR'				=> 'سەرپەرشتیار',
	'MODERATORS'			=> 'سەرپەرشتیاران',
	'MODULE_NOT_ACCESS'		=> 'ناکرێت بگەیتە مۆدل',
	'MODULE_NOT_FIND'		=> 'نەهاتە دۆزینەوە مۆدلی %s',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'فایلی مۆدل %s گۆڕاوێکی تەواوی لەخۆ نەگرتووە [%s]',
	'MONTH'					=> 'مانگ',
	'MOVE'					=> 'گواستنەوە',

	'NA'						=> '',
	'NEWEST_USER'				=> 'ئەندامە نوێیەکان <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'پەیامی نوێ',
	'NEW_MESSAGES'				=> 'پەیامە نوێیەکان',
	'NEW_POST'					=> 'بەشداری نوێ',	// Not used anymore
	'NEW_POSTS'					=> 'بەشدارییە نوێیەکان',	// Not used anymore
	'NEXT'						=> 'داهاتوو',		// Used in pagination
	'NEXT_STEP'					=> 'داهاتوو',
	'NEVER'						=> 'هەرگیز',
	'NO'						=> 'نەخێر',
	'NO_NOTIFICATIONS'			=> 'هیچ ئاگەداکردنەوەیەکت بۆ نەهاتووە',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'تۆ رێگەت پێ نەدراوە بۆ بەڕێوەبردنی ئەم گرووپە.',
	'NOT_AUTHORISED'			=> 'دەسەلاتی گەیشتن بەم شێونەت نییە.',
	'NOT_WATCHING_FORUM'		=> 'هاوبەش نیت لە نوێکارییەکانی ئەم سەکۆیە.',
	'NOT_WATCHING_TOPIC'		=> 'هاوبەش نیت لە نوێکارییەکانی ئەم بابەتە.',
	'NOTIFICATIONS'				=> 'ئاگەدارییەکان',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>وەڵامدانەوە</strong> لە %1$s لەبابەتە دڵخوازەکان:',
	),
	'NOTIFICATION_FORUM'				=> '<em>سەکۆ:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>داوای بە ئەندام بوون</strong> لە %1$s بۆ هاتنە ناو گرووپ %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>داوای بە ئەندام بوون پەسەند کرا</strong> بۆ هاتنە ناو گروپ %1$s.',
	'NOTIFICATION_PM'					=> '<strong>پەیامی تایبەتی</strong> لە %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>وەڵامدانەو</strong> لە %1$s لە بابەت:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>بەشداری پەسەندکرا</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>بەشداری پەسەند نەکرا</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>بەشداری پەسەند بکرێت</strong> داواکراوە لەلایەن %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>دەق کراوە</strong> لەلایەن %1$s لە:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>هۆکار:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>ئاگەداری لە پەیامی تایبەتی</strong> لەلایەن %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>بەشداری ئاگەدار کراوەتەوە</strong> لەلایەن %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>ئاگەداری داخراوە</strong> لەلایەن %1$s for:',
	'NOTIFICATION_TOPIC'				=> '<strong>Neبابەتی نوێ</strong> لەلایەن %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>بابەت پەسەندکرا</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>بابەت پەسەند نەکرا</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>بابەت پەسەند بکرێت</strong> داواکراوە لەلایەن %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'جۆری ئاگەدارکردنەوە "%s" لە فایلەکانی سیستەم دا لەدەست دراوە .',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>چاڵاککردن داواکراوە</strong>بۆ ئەندامە تازەکان: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'ئەوانەی دیکە',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d ئەوانەی دیکە',
	),
	'NOTIFY_ADMIN'				=> 'تکایە ئێمە ئاگەدار بکەوە.',
	'NOTIFY_ADMIN_EMAIL'		=> 'تکایە دەستەی بەڕێوەبەران ئاگەدار بکەوە: <a href="ناردن پەیام بۆ:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'ڕێگەت پێ نەدراوە ئەم فایلە دابگری.',
	'NO_ACTION'					=> 'هیچ هەلبژاردنێکی دیاریکراو نییە.',
	'NO_ADMINISTRATORS'			=> 'هیچ بەڕێوەبەرێک لە سەکۆیەدا نییە.',
	'NO_AUTH_ADMIN'				=> 'دەسەلاتی بەڕێوەبرایەتیت نییە و ناتوانیت بگەیتە پەڕەی بەڕێوەبردن.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'ناتوانیت دووبارە خۆت پێناسە بکەیت بە ناوی ئەندامێکی ترەوە.',
	'NO_AUTH_OPERATION'			=> 'وەکو پێویست ئەو دەسەلاتەت نییە بۆ تەواوکردنی ئەم پرۆسەیە.',
	'NO_AVATARS'				=> 'ئێستا هیچ وێنۆچکەیەک نییە',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'ناتوانێت پەیوەندی بکات بە smtp host : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'ئەمڕۆ لەدایکبوونی هیچ کەسێک نییە',
	'NO_EMAIL_MESSAGE'			=> 'پەیامی ئەلیکترۆنی بەتالە.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'ناتوانێت پۆستی ڕاژە بێنێت .',
	'NO_EMAIL_SUBJECT'			=> 'ناونیشانی پەیامت دانەناوە.',
	'NO_FORUM'					=> 'سەکۆی دیاریکراو بوونی نییە.',
	'NO_FORUMS'					=> 'ئەم سەکۆییە هیچ بەشێکی نییە.',
	'NO_GROUP'					=> 'ئەو گروپەی داوات کرد بوونی نییە.',
	'NO_GROUP_MEMBERS'			=> 'ئەم گرووپە ئەندامی تێدا نییە.',
	'NO_IPS_DEFINED'			=> 'هیچ  ناونیشانیIP یان hostnames نەدۆزرایەوە',
	'NO_MEMBERS'				=> 'هیچ ئەندامێک نەدۆزرایەوە بەم گەڕانە.',
	'NO_MESSAGES'				=> 'پەیام نییە',
	'NO_MODE'					=> 'سەرپەشتیارێتی دیاری نەکراوە  .',
	'NO_MODERATORS'				=> 'هیچ سەرپەرشیارێک نییە.',
	'NO_NEW_MESSAGES'			=> 'پەیامی نوێ نییە',
	'NO_NEW_POSTS'				=> 'بەشداری نوێ نییە',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'ئەندامانی تۆماربوو لەسەرهێل نییە',
	'NO_POSTS'					=> 'بەشداری نییە',
	'NO_POSTS_TIME_FRAME'		=> 'هیچ بەشدارییەکی دیاریکراو  لەم بابەتەدا بوونی نییە.',
	'NO_FEED_ENABLED'			=> 'دانی پێدانەکان بەردەست نییە لەم تەختەیە.',
	'NO_FEED'					=> 'دان پێ دانی داواکراو بەردەست نییە.',
	'NO_STYLE_DATA'				=> 'ناتوانێت زانیاری ستایل بێنیت',
	'NO_SUBJECT'				=> 'ناونیشانی دیاریکراو بوونی نییە ',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'گەڕانی دیاری کراو بوونی نییە.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'هیچ پالپشتیەک نییە بۆ دەسەلاتی ڕێگاکان.',
	'NO_TOPIC'					=> 'بابەتی داواکراو بوونی نییە.',
	'NO_TOPIC_FORUM'			=> 'بابەت یان سەکۆی داواکراو بوونی نییە.',
	'NO_TOPICS'					=> 'هیچ بابەتێک یان بەشداری لەم سەکۆیەدا نییە.',
	'NO_TOPICS_TIME_FRAME'		=> 'هیچ بابەتێک نییە لەم ماوەیەی کە دیاری کراوە.',
	'NO_UNREAD_POSTS'			=> 'هیچ بەشدارییەک نییە نەهاتبێتە خوێندنەوە',
	'NO_UPLOAD_FORM_FOUND'		=> 'بەسەرکەوتویی بارکرا، بەڵام فایلەکە دروست نییە.',
	'NO_USER'					=> 'ئەندامە داواکراوەکان بەردەست نین.',
	'NO_USERS'					=> 'ئەندامە داواکراوەکان بەردەست نین.',
	'NO_USER_SPECIFIED'			=> 'ناوی بەکارهێنەر دیاری نەکرا.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d هاوپێچ',
		2	=> '%d هاوپێچ',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'هیچ بەشدارییەک لە چاوەڕوانی دا نییە',		// 0
		1			=> '1 بەشداری ل چاوەڕوانی دایە',		// 1
		2			=> '%d بەشداری لە چاوەڕوانی دایە',		// 2+
	),

	'OCCUPATION'				=> 'دەست بە سەرداگرتن',
	'OFFLINE'					=> 'دەهێل',
	'ONLINE'					=> 'سەرهێل',
	'ONLINE_BUDDIES'			=> 'هاوڕێیانی سەرهێل',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'لەسەرجەمی گشتی there are <strong>%1$d</strong> بەکارهێنەر لە سەر هێلە :: %2$s, %3$s و %4$s',
		2	=> 'لەسەرجەمی گشتی there are <strong>%1$d</strong> بەکارهێنەر لە سەر هێلە :: %2$s, %3$s و %4$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'لەسەرجەمی گشتی there are <strong>%1$d</strong> بەکارهێنەر لە سەر هێلە :: %2$s, %3$s و %4$s',
		2	=> 'لەسەرجەمی گشتی there are <strong>%1$d</strong> بەکارهێنەر لەسەر هێلە :: %2$s, %3$s و %4$s',
	),
	'OPTIONS'					=> 'هەلبژاردنەکان',

	'PAGE_OF'				=> 'پەڕە <strong>%1$d</strong> لە <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'پەڕە %s',
	'PASSWORD'				=> 'تێپەڕەووسە',
	'PIXEL'					=> 'وێنەخاڵ',
	'PIXELS'				=> array(
		1	=> '%d وێنەخاڵ',
		2	=> '%d وێنەخاڵ',
	),
	'PLAY_QUICKTIME_FILE'	=> 'لێدانی فایلی Quicktime ',
	'PLEASE_WAIT'			=> 'تکایە چاوەڕێکە.',
	'PM'					=> 'پەیامی تایبەتی',
	'PM_REPORTED'			=> 'کرتە بکە بۆ بینینی ئاگەداری',
	'POSTING_MESSAGE'		=> 'پەیامێک بڵاو دەکاتەوە لە %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'پەیامی تایبەتی دەنێرێت',
	'POST'					=> 'بەشداری',
	'POST_ANNOUNCEMENT'		=> 'ڕاگەیاند',
	'POST_STICKY'			=> 'جێگیر',
	'POSTED'				=> 'بڵاوکرا',
	'POSTED_IN_FORUM'		=> 'لە',
	'POSTED_ON_DATE'		=> 'لە',
	'POSTS'					=> 'بەشدارییەکان',
	'POSTS_UNAPPROVED'		=> 'نزیکەی بەشدارییەک هەیە لەم بابەتە کە پەسەند نەکراوە.',
	'POSTS_UNAPPROVED_FORUM'=> 'نزیکەی بابەتێک هەیە لەم سەکۆیە کە پەسەند نەکراوە.',
	'POST_BY_AUTHOR'		=> 'لەلایەن',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, ئەوەی لە لیستی پشتگوێ خراوەکانتە, ئەم بەشدارییەی نووسی.',
	'POST_DISPLAY'			=> '%1$sبینینی ئەم بابەتە%2$s.',
	'POST_DAY'				=> '%.2f بەشداری لە هەر ڕۆژێکدا',
	'POST_DELETED_ACTION'	=> 'بەشداری سڕاوە:',
	'POST_DELETED'			=> 'ئە بەشدارییە هاتە سڕینەوە.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> بەشدارییەکە هاتە سڕینەوە لەلایەن <strong>%1$s</strong> لە %3 $s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> بەشدارییەکە هاتە سڕینەوە لەلایەن <strong>%1$s</strong> لە %3 $s لەبەر ئەم هۆکارە: %4 $s',
	'POST_DETAILS'			=> 'دڕێژەی بەشداری',
	'POST_NEW_TOPIC'		=> 'ناردنی بابەتێکی نوێ',
	'POST_PCT'				=> '%.2f%% لە سەرجەم بەشدارییەکان',
	'POST_PCT_ACTIVE'		=> '%.2f%% لە بەشداری ئەندامان',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% لە بەشدارییەکانت',
	'POST_REPLY'			=> 'زیادکردنی وەڵام',
	'POST_REPORTED'			=> 'کرتە بکە بۆ بینینی ئاگەداری',
	'POST_SUBJECT'			=> 'ناونیشانی بابەت',
	'POST_TIME'				=> 'بەرواری ناردن',
	'POST_TOPIC'			=> 'ناردنی بابەتی نوێ',
	'POST_UNAPPROVED_ACTION'	=> 'بەشدارییەکانی لە چاوەڕوانی پەسەند کردن:',
	'POST_UNAPPROVED'		=> 'ئەم بەشدارییە چاوەڕێی پەسەند کردنە.',
	'POWERED_BY'			=> 'وەشاندراوە لەلایەن %s',
	'PREVIEW'				=> 'پێشبینین',
	'PREVIOUS'				=> 'پێشتر',		// Used in pagination
	'PREVIOUS_STEP'			=> 'پێشتر',
	'PRIVACY'				=> 'ڕامیاری تایبەتێتی',
	'PRIVATE_MESSAGE'		=> 'پەیامی تایبەتی ',
	'PRIVATE_MESSAGES'		=> 'پەیامە تایبەتییەکان',
	'PRIVATE_MESSAGING'		=> 'نێردراوی تایبەت',
	'PROFILE'				=> 'پەڕەی ئەندام',

	'QUICK_LINKS'			=> 'بەستەری خێرا',

	'RANK'						=> 'پلە',
	'READING_FORUM'				=> 'سەیری بابەت دەکات لە %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'ڕاگەیاندنی گشتی دەخوێنتەوە',
	'READING_LINK'				=> 'بەدوای ئەم بەستەرە کەوتووە %s',
	'READING_TOPIC'				=> 'بابەت دەخوێنتەوە لە %s',
	'READ_PROFILE'				=> 'زانیاریی تایبەتی',
	'REASON'					=> 'هۆکار',
	'RECORD_ONLINE_USERS'		=> 'زۆرترین‌ ژماره‌ی ئاماده‌بوان له‌یه‌ك‌ کاتدا <strong>%1$s</strong> کەس بوون. له‌ ڕێکەوتی %2$s',
	'REDIRECT'					=> 'گواستنەوە',
	'REDIRECTS'					=> 'سەرجەم گواستراوەکان',
	'REGISTER'					=> 'خۆتۆمارکردن',
	'REGISTERED_USERS'			=> 'ئەندامە ئامادەبووەکان:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'ئێستا %2$s ئەندام و %1$d بەکارهێنەر لەسەر هێلن',
		2	=> 'ئێستا %2$s ئەندام و %1$d بەکارهێنەر لەسەر هێلن',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d ئەندام',
		2	=> '%d ئەندامەکان',
	),
	'REMOVE'					=> 'سڕینەوە',
	'REMOVE_INSTALL'			=> 'تکایە بسڕەوە، بگوازەوە یاخود ناوی ڕێڕەوی install بگۆڕە پێش ئەوەی تەختەکەت بەکاربێنی، ئەگەر ئەم ڕێڕەوە هێشتا ماوە، تەنها بەڕێوەبەران دەتوانن چارەسەری بکەن.',
	'REPLIES'					=> 'وەڵامەکان',
	'REPLY_WITH_QUOTE'			=> 'وەڵام دانەوە لەگەل دەق',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'وەڵام دانەوەی ڕاگەیاندنی گشتی',
	'REPLYING_MESSAGE'			=> 'وەڵام دانەوەی پەیام لە %s',
	'REPORT_BY'					=> 'ئاگەداریی لەلایەن',
	'REPORT_POST'				=> 'ئاگەدارکردنەوەی ئەم بەشدارییە',
	'REPORTING_POST'			=> 'ئاگەدارکردنەوەی بەشداری',
	'RESEND_ACTIVATION'			=> 'دووبارە ناردنەوەی پۆستی ئەلیکترۆنی دڵنیاکردنەوە',
	'RESET'						=> 'ڕێکخستنەوه',
	'RESTORE_PERMISSIONS'		=> 'گەڕاندنەوەی مۆڵەتپیدانەکان',
	'RETURN_INDEX'				=> '%s گەڕانەوە بۆ پەڕەی سەرەکی%s',
	'RETURN_FORUM'				=> '%sگەڕانەوە بۆ ئەو سەکۆییەی کە دوایین جار سەردانت کرد%s',
	'RETURN_PAGE'				=> '%sگەڕانەوە بۆ پەڕەی پێشووتر%s',
	'RETURN_TOPIC'				=> '%sگەڕانەوە بۆ ئەو بابەتەی کە دوایین جار سەردانت کرد%s',
	'RETURN_TO'					=> 'گەڕانەوە بۆ “%s”',
	'RETURN_TO_INDEX'			=> 'گەڕانەوە بۆ لیستی سەکۆکان',
	'FEED'						=> 'دان پێدان - Feed',
	'FEED_NEWS'					=> 'هەواڵ - News',
	'FEED_TOPICS_ACTIVE'		=> 'بابەتە چاڵاکەکان',
	'FEED_TOPICS_NEW'			=> 'بابەتە نوێیەکان',
	'RULES_ATTACH_CAN'			=> ' <strong>دەتوانی</strong> هاوپێچ دابنێیت لەم سەکۆیە ',
	'RULES_ATTACH_CANNOT'		=> ' <strong>ناتوانیت</strong> هاوپێچ دابنێیت لەم سەکۆیە',
	'RULES_DELETE_CAN'			=> ' <strong>دەتوانیت</strong> بەشدارییەکانت بسڕیتەوە لەم سەکۆیە',
	'RULES_DELETE_CANNOT'		=> ' <strong>ناتوانیت</strong> بەشدارییەکانت بسڕیتەوە لەم سەکۆیە',
	'RULES_DOWNLOAD_CAN'		=> ' <strong>دەتوانیت</strong> هاوپێچەکانی ناو ئەم سەکۆیە داگریت',
	'RULES_DOWNLOAD_CANNOT'		=> ' <strong>ناتوانیت</strong> هاوپێچەکانی ناو ئەم سەکۆیە داگریت',
	'RULES_EDIT_CAN'			=> ' <strong>دەتوانیت</strong> دەستکاری بەشدارییەکانت بکەی لەم سەکۆیە',
	'RULES_EDIT_CANNOT'			=> ' <strong>ناتوانیت</strong> دەستکاری بەشدارییەکانت بکەی لەم سەکۆیە',
	'RULES_LOCK_CAN'			=> ' <strong>دەتوانیت</strong> بابەتەکانت دابخەی لەم سەکۆیە',
	'RULES_LOCK_CANNOT'			=> ' <strong>ناتوانیت</strong> بابەتەکانت دابخەی لەم سەکۆیە',
	'RULES_POST_CAN'			=> ' <strong>دەتوانیت</strong> بابەتی نوێ دابنێیت لەم سەکۆییە',
	'RULES_POST_CANNOT'			=> ' <strong>ناتوانیت</strong> بابەتی نوێ دابنێیت لەم سەکۆییە',
	'RULES_REPLY_CAN'			=> ' <strong>دەتوانیت</strong> وەڵامی بابەتەکان بدەی لەم سەکۆیە',
	'RULES_REPLY_CANNOT'		=> ' <strong>ناتوانیت</strong> وەڵامی بابەتەکان بدەی لەم سەکۆیە',
	'RULES_VOTE_CAN'			=> ' <strong>دەتوانیت</strong> دەنگ بدەیت لە ڕاپرسییەکانی ناو ئەم سەکۆیە',
	'RULES_VOTE_CANNOT'			=> ' <strong>ناتوانیت</strong> دەنگ بدەیت لە ڕاپرسییەکانی ناو ئەم سەکۆییە',

	'SEARCH'					=> 'گەڕان',
	'SEARCH_MINI'				=> 'گەڕان…',
	'SEARCH_ADV'				=> 'گەڕانی پێشکەوتوو',
	'SEARCH_ADV_EXPLAIN'		=> 'پیشاندانی هەلبژاردنەکانی گەڕانی پێشکەوتوو',
	'SEARCH_KEYWORDS'			=> 'گەڕان لە کلیلە ووشە',
	'SEARCHING_FORUMS'			=> 'گەڕان لە سەکۆ',
	'SEARCH_ACTIVE_TOPICS'		=> 'بابەتەکانی چاڵاک',
	'SEARCH_FOR'				=> 'گەڕان لە',
	'SEARCH_FORUM'				=> 'گەڕان ناو ئەم سەکۆییە…',
	'SEARCH_NEW'				=> 'بەشداری نوێ',
	'SEARCH_POSTS_BY'			=> 'گەڕان لە بەشدارییەکان بەپێی',
	'SEARCH_SELF'				=> 'بەشدارییەکانی خۆت',
	'SEARCH_TOPIC'				=> 'گەڕان ناو ئەم بابەتە…',
	'SEARCH_UNANSWERED'			=> 'بەشدارییە وەڵام نەدراوەکان',
	'SEARCH_UNREAD'				=> 'بەشدارییە نەخوێندراوەکان',
	'SEARCH_USER_POSTS'			=> 'گەڕان لە بەشدارییەکانی ئەندام',
	'SECONDS'					=> 'چرکەکان',
	'SEE_ALL'					=> 'بینینی هەموو',
	'SELECT'					=> 'دەست نیشانکردن',
	'SELECT_ALL_CODE'			=> 'دەست نیشانکردن هەموو',
	'SELECT_DESTINATION_FORUM'	=> 'تکایە جێی مەبەست بۆ سەکۆ هەلبژێرە',
	'SELECT_FORUM'				=> 'هەلبژاردنی سەکۆ',
	'SEND_EMAIL'				=> 'ناردنی پۆستی ئەلیکترۆنی',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'ناردنی پۆستی ئەلیکترۆنی بۆ %s',
	'SEND_PRIVATE_MESSAGE'		=> 'ناردنی پەیامی تایبەتی',
	'SETTINGS'					=> 'ڕێکخستنەکان',
	'SIGNATURE'					=> 'واژوو',
	'SKIP'						=> 'پەڕینەوە بەسەر ناوەڕۆک',
	'SKYPE'						=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'ڕاژەی SMTP پاڵپشتی ئەم دەسڵاتە ناکات.',
	'SORRY_AUTH_READ'			=> 'تۆ دەسەڵاتی خوێندنەوەی ئەم سەکۆیەت نییە.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'تۆ دەسەڵاتی داگرتنی ئەم هاوپێچەت نییە.',
	'SORT_BY'					=> 'ڕێزکردن بەپێی',
	'SORT_JOINED'				=> 'ڕێکەوتی بەئەندام بوون',
	'SORT_LOCATION'				=> 'شوێن',
	'SORT_RANK'					=> 'پلە',
	'SORT_POSTS'				=> 'بەشدارییەکان',
	'SORT_TOPIC_TITLE'			=> 'ناونیشانی بابەت',
	'SORT_USERNAME'				=> 'ناوی بەکارهێنەر',
	'SPLIT_TOPIC'				=> 'دابەشکردنی بابەت',
	'SQL_ERROR_OCCURRED'		=> 'هەلەی SQL ڕوویدا لە کاتی بانگکردنی پەڕە. ئەگەر هەلەکە بەردەوام بوو تکایە پەیوەندی بە %sبەڕێوەبەری سەکۆ%s بکە دەربارەی ئەم کێشەیە',
	'STATISTICS'				=> 'ئامارەکان',
	'START_WATCHING_FORUM'		=> 'هاوبەشی کردنی سەکۆ',
	'START_WATCHING_TOPIC'		=> 'هاوبەشی کردنی بابەت',
	'STOP_WATCHING_FORUM'		=> 'هاوبەشی نەکردنی سەکۆ',
	'STOP_WATCHING_TOPIC'		=> 'هاوبەشی نەکردنی بابەت',
	'STRING_LIST_MULTI'			=> '%1$s, و %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s و %2$s',
	'SUBFORUM'					=> 'سەکۆی ناوخۆ',
	'SUBFORUMS'					=> 'سەکۆ ناخۆییەکان',
	'SUBJECT'					=> 'ناونیشان',
	'SUBMIT'					=> 'نــــاردن',

	'TB'				=> 'تێرابایت',
	'TERMS_USE'			=> 'مەرجەکانی بەکارهێنان',
	'TEST_CONNECTION'	=> 'تاقیکردنەوەی پەیوەندی',
	'THE_TEAM'			=> 'دەستەی سەکۆ',
	'TIB'				=> 'TiB',
	'TIME'				=> 'کات',
	'TIMEOUT_PROCESSING_REQ'			=> 'ماوەی جێ بەجێکردن تەواوبوو.',

	'TOO_LARGE'						=> 'بەهای دانراو زۆر گەورەیە.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'بەهای <strong> بەرزترین ئاستی ڕێگە پێدراو لە ژمارەی وەرگرەکان بۆ بەیامی تایبەتی </strong> زۆر درێژە .',

	'TOO_LONG'						=> 'بەهای دانراو زۆر درێژە.',

	'TOO_LONG_CONFIRM_CODE'			=> 'کۆدی دڵنیاکردنەوە زۆر درێژە.',
	'TOO_LONG_DATEFORMAT'			=> 'شێوازی ڕێکخستنی بەروار زۆر درێژە.',
	'TOO_LONG_JABBER'				=> 'ناوی هەژماری Jabberـەکەت زۆر درێژە.',
	'TOO_LONG_NEW_PASSWORD'			=> 'تێپەڕەووشەکەت زۆر درێژە.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'تێپەڕەووشەی دڵنیاکردنەوە زۆر درێژە.',
	'TOO_LONG_USER_PASSWORD'		=> 'تێپەڕەووشەکەت زۆر درێژە.',
	'TOO_LONG_USERNAME'				=> 'ناوی بەکارهێنەرت زۆر درێژە.',
	'TOO_LONG_EMAIL'				=> 'پۆستی ئەلیکترۆنیت زۆر کورتە.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'هەولتدا دەنگ بە ژمارەیەکی زۆر لە هەلبژاردنەکان بدەی.',

	'TOO_SHORT'						=> 'بەهای دانراو زۆر کوریە.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'کۆدی دڵنیاکردنەوە زۆر کورتە.',
	'TOO_SHORT_DATEFORMAT'			=> 'شێوازی ڕێکخستنی بەروار زۆر کورتە.',
	'TOO_SHORT_JABBER'				=> 'ناوی هەژماری Jabberـەکەت زۆر کورتە.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'تێپەڕەووشەی دانراو زۆر کورتە.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'تێپەڕەووشەی دڵنیاکردنەوە زۆر کورتە.',
	'TOO_SHORT_USER_PASSWORD'		=> 'تێپەڕەووشەکەت زۆر کورتە.',
	'TOO_SHORT_USERNAME'			=> 'ناوی بەکارهێنەر زۆر کورتە.',
	'TOO_SHORT_EMAIL'				=> 'پۆستی ئەلیکترۆنی زۆر کورتە.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'پۆستی ئەلیکترۆنی دڵنیاکردنەوە زۆر کورتە.',
	'TOO_SMALL'						=> 'ئەو بەهایەی داتناوە زۆر کورتە.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'بەهای <strong> بەرزترین ئاستی ڕێگە پێدراو لە ژمارەی وەرگرەکان بۆ بەیامی تایبەتی </strong> زۆر کورتە .',

	'TOPIC'				=> 'بابەت',
	'TOPICS'			=> 'بابەتەکان',
	'TOPICS_UNAPPROVED'	=> 'بابەتێک هەیە هێشتا پەسەند نەکراوە.',
	'TOPIC_ICON'		=> 'وێنۆچکەی بابەت',
	'TOPIC_LOCKED'		=> 'ئەم بابەتە داخراوە, ناتوانیت دەستکاری بکەیت یان وەڵام بنووسیت.',
	'TOPIC_LOCKED_SHORT'=> 'بابەت داخراوە',
	'TOPIC_MOVED'		=> 'بابەت گواستراوەتەوە',
	'TOPIC_REVIEW'		=> 'پێداچوونەوەی بابەت',
	'TOPIC_TITLE'		=> 'ناونیشانی بابەت',
	'TOPIC_UNAPPROVED'	=> 'ئەم بابەتە پەسەند نەکراوە.',
	'TOPIC_DELETED'		=> 'ئەم بابەتە هاتە سڕینەوە.',
	'TOTAL_ATTACHMENTS'	=> 'هاوپێچ',
	'TOTAL_LOGS'		=> array(
		1	=> '%d تۆمار',
		2	=> '%d تۆمارەکان',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d پەیامێکی تایبەتی لە سەرجەمی گشتی',
		2	=> '%d پەیامی تایبەتی لەسەرجەمی گشتی',
	),
	'TOPIC_POLL'		=> 'ئەم بابەتە ڕاپرسی لەگەل دایە.',
	'TOTAL_POSTS'		=> 'سەرجەم بەشدارییەکان',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'سەرجەم بەشدارییەکان <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'ئەم بابەتە هاتە ئاگەدارکردنەوە',
	'TOTAL_TOPICS'		=> array(
		2	=> 'سەرجەم بابەتەکان <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'سەرجەم ئەندامان <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'هەلەکانی شوێنکەوتوی PHP: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'نەتوانرا مەودای وێنە دیاری بکرێت، تکایە پێداچونەوەی بەستەرەکە بکە.',
	'UNABLE_TO_DELIVER_FILE'=> 'ناتوانێت بگاتە پەڕگە.',
	'UNKNOWN_BROWSER'		=> 'وێبگەڕی نەناسراو',
	'UNMARK_ALL'			=> 'لابردنی نیشانەکراوەکان',
	'UNREAD_MESSAGES'		=> 'پەیامە نەخوێندراوەکان',
	'UNREAD_POST'			=> 'بەشداری نەخوێندراو',
	'UNREAD_POSTS'			=> 'بەشدارییە نەخوێندراوەکان',
	'UNWATCH_FORUM_CONFIRM'		=> 'ئایە تۆ دڵنیایت کە ناتەوێ هاوبەشی ئەم سەکۆیە بکەیت ؟',
	'UNWATCH_FORUM_DETAILED'	=> 'ئایە تۆ دڵنیایت کە ناتەوێ هاوبەشی بکەیت لە سەکۆی “%s” ؟',
	'UNWATCH_TOPIC_CONFIRM'		=> 'ئایە تۆ دڵنیایت کە ناتەوێ هاوبەشی ئەم بابەتە بکەیت ؟',
	'UNWATCH_TOPIC_DETAILED'	=> 'ئایە تۆ دڵنیایت کە ناتەوێ هاوبەشی بکەیت لە بابەت “%s” ؟',
	'UNWATCHED_FORUMS'			=> 'لەمەو دوا هاوبەش نیت لەو سەکۆیانەی کە دیاریت کرد.',
	'UNWATCHED_TOPICS'			=> 'لەمەو دوا هاوبەش نیت لەو بابەتانەی کە دیاریت کرد.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'لەمەو دوا هاوبەش نیت لەو بابەت و سەکۆیانەی کە دیاریت کرد.',
	
	'UPDATE'				=> 'نوێکردنەوە',
	'UPLOAD_IN_PROGRESS'	=> 'ئێستا لە بارکردن دایە.',
	'URL_REDIRECT'			=> 'ئەگەر وێبگەڕەکەت پالپشتی گواستنەوەی خۆکارانە ناکات تکایە %sئێرە%s داگرە بۆ گواستنەوە.',
	'USERGROUPS'			=> 'گرووپەکان',
	'USERNAME'				=> 'ناوی بەکارهێنەر',
	'USERNAMES'				=> 'ناوی بەکارهێنەران',
	'USER_AVATAR'			=> 'وێنۆچکەی ئەندام',
	'USER_CANNOT_READ'		=> 'ناتوانیت بەشدارییەکان بخوێنیتەوە لەم سەکۆتە.',
	'USER_POSTS'			=> array(
		1	=> '%d بەشداری',
		2	=> '%d بەشدارییەکان',
	),
	'USERS'					=> 'بەکارهێنەران',
	'USE_PERMISSIONS'		=> 'تاقیکردنەوەی دەسەڵاتەکانی ئەم ئەندامە',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'ببورە، دەسەڵاتی بەکارهێنانی ئەم تایبەتمەندییەت نییە. لەوانەیە تۆ ئەندامێکی نوێ بیت لە سەکۆ و پێویستت بە بەشداری زیاتر هەبێت بۆ گەیشتن بەم تایبەتمەندییە.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'بينيى',
	'VIEWED_COUNTS'		=> array(
		0	=> 'هێشتا نەبینراوە',
		1	=> 'بینراوە %d جار',
		2	=> 'بینراوە %d جار',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'سەیری پەڕەی پەیوەندی بە بەڕێوەبەر دەکات',
	'VIEWING_FAQ'				=> 'سەیری پرسیارە دووبارەبووەکان دەکات',
	'VIEWING_MEMBERS'			=> 'سەیری لیستی ئەندامان دەکات',
	'VIEWING_ONLINE'			=> 'سەیری ئامادەبوانی ئێستا دەکات',
	'VIEWING_MCP'				=> 'بینینی پەڕەی سەرپەرشتیار',
	'VIEWING_MEMBER_PROFILE'	=> 'سەیری پەڕەی ئەندامێک دەکات',
	'VIEWING_PRIVATE_MESSAGES'	=> 'سەیری پەیامی تایبەتی دەکات',
	'VIEWING_REGISTER'			=> 'هەژمار تۆمار دەکات',
	'VIEWING_UCP'				=> 'سەیری پەڕەی ئەندام دەکات',
	'VIEWS'						=> 'جاری بینراو',
	'VIEW_BOOKMARKS'			=> 'بینینی نیشانکەرەکان',
	'VIEW_FORUM_LOGS'			=> 'بینینی تۆمارەکان',
	'VIEW_LATEST_POST'			=> 'بینینی دوایین بەشداری',
	'VIEW_NEWEST_POST'			=> 'بینینی نوێترین بەشداری',
	'VIEW_NOTES'				=> 'بینینی تێبینی ئەندامان',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'ئەم زانیارییانە گرنگی بە ئەندامە چاڵاکەکانی ماوەی %d خولەکی ڕابردوو دەدات',
		2	=> 'ئەم زانیارییانە گرنگی بە ئەندامە چاڵاکەکانی ماوەی %d خولەکی ڕابردوو دەدات',
	),
	'VIEW_TOPIC'				=> 'بینینی بابەت',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'ڕاگەیاندن: ',
	'VIEW_TOPIC_GLOBAL'			=> 'ڕاگەیاندنی گشتی: ',
	'VIEW_TOPIC_LOCKED'			=> 'داخراوە: ',
	'VIEW_TOPIC_LOGS'			=> 'بینینی تۆمارەکان',
	'VIEW_TOPIC_MOVED'			=> 'گواستراوەتەوە: ',
	'VIEW_TOPIC_POLL'			=> 'ڕاپرسی: ',
	'VIEW_TOPIC_STICKY'			=> 'جێگیر: ',
	'VISIT_WEBSITE'				=> 'سەردانی وێبگە',

	'WARNINGS'			=> 'ئاگەدارییەکان',
	'WARN_USER'			=> 'ئاگەدارکردنەوەی ئەندام',
	'WATCH_FORUM_CONFIRM'	=> 'ئایە تۆ دڵنیایت کە دەتەوێت هاوبەشی لەم سەکۆیە بکەی ؟',
	'WATCH_FORUM_DETAILED'	=> 'ئایە تۆ دڵنیایت کە دەتەوێت هاوبەشی لەم سەکۆیە بکەی “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'ئایە تۆ دڵنیایت کە دەتەوێت هاوبەشی لەم بابەتە بکەی?',
	'WATCH_TOPIC_DETAILED'	=> 'ئایە تۆ دڵنیایت کە دەتەوێت هاوبەشی لەم بابەتە بکەی “%s”?',
	'WELCOME_SUBJECT'	=> 'بەخێربێیت بۆ %s سەکۆ',
	'WEBSITE'			=> 'WWW',
	'WHOIS'				=> 'Whois',
	'WHO_IS_ONLINE'		=> 'ئامادەبوانی ئێستا',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	=> 'تێپەڕەووشەیەکی هەلەت بەکارهێنا.',

	'WRONG_DATA_COLOUR'			=> 'کۆد ڕەنگی نوسراو هەلەیە.',
	'WRONG_DATA_JABBER'			=> 'ناوی نووسراو هەلەیە Jabber ناوی هەژمار.',
	'WRONG_DATA_LANG'			=> 'زمانی دەستنیشانکراو بەردەست نییە.',
	'WRONG_DATA_POST_SD'		=> 'ڕێڕەوی ڕێزکردنی بەشداریەکان کە دیاریت کرددوە هەلەیە.',
	'WRONG_DATA_POST_SK'		=> 'هەلبژاردنی ڕێزکردنی بەشدارییەکانی کە دیاریت کردووە هەلەیە.',
	'WRONG_DATA_TOPIC_SD'		=> 'ڕێڕەوی ڕێزکردنی بابەتەکان کە دیاریت کردووە هەلەیە.',
	'WRONG_DATA_TOPIC_SK'		=> 'هەلبژاردنی ڕێزکردنی بابەتەکان کە دیاریت کردووە هەلەیە.',
	'WROTE'						=> 'نووسيى',

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'				=> 'ساڵ',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> 'بەلێ',
	'YOU_LAST_VISIT'	=> 'دواین سەردان: %s',

	'datetime'			=> array(
		'TODAY'		=> 'ئەمڕۆ',
		'TOMORROW'	=> 'دوێنی',
		'YESTERDAY'	=> 'پێرێ',
		'AGO'		=> array(
			0		=> ' کەمتر لە یەک خولەکی ڕابردوو',
			1		=> '%d خولەکی ڕابردوو',
			2		=> '%d خولەکی ڕابردو',
		),

		'Sunday'	=> 'یەک شەممە',
		'Monday'	=> 'دوو شەممە',
		'Tuesday'	=> 'سێ شەممە',
		'Wednesday'	=> 'چوار شەممە',
		'Thursday'	=> 'پێنج شەممە',
		'Friday'	=> 'هەینی',
		'Saturday'	=> 'شەممە',

		'Sun'		=> 'یەک شەممە',
		'Mon'		=> 'دوو شەممە',
		'Tue'		=> 'سێ شەممە',
		'Wed'		=> 'چوار شەممە',
		'Thu'		=> 'پێنج شەممە',
		'Fri'		=> 'هەینی',
		'Sat'		=> 'شەممە',

		'January'	=> 'کانوونی دووەم',
		'February'	=> 'شوبات',
		'March'		=> 'ئازار',
		'April'		=> 'نیسان',
		'May'		=> 'ئایار',
		'June'		=> 'حوزەیران',
		'July'		=> 'تەمموز',
		'August'	=> 'ئاب',
		'September' => 'ئەیلول',
		'October'	=> 'تشرینی یەکەم',
		'November'	=> 'تشرینی دووسەم',
		'December'	=> 'کانوونی یەکەم',

		'Jan'		=> ' کانوونی دووەم',
		'Feb'		=> 'شوبات',
		'Mar'		=> 'ئازار',
		'Apr'		=> 'نیسان',
		'May_short'	=> 'ئایار',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'حوزەیران',
		'Jul'		=> 'تەممووز',
		'Aug'		=> 'ئاب',
		'Sep'		=> 'ئەیلوول',
		'Oct'		=> ' تشرینی یەکەم',
		'Nov'		=> ' تشرینی دووەم',
		'Dec'		=> 'کانوونی یەکەم',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'کاتی جیهانی',
		'UTC_OFFSET'			=> 'کاتی جیهانی%1$s',
		'UTC_OFFSET_CURRENT'	=> 'کاتی جیهانی%1$s - %2$s',

		'Etc/GMT-12'	=> 'کاتی جیهانی+12',
		'Etc/GMT-11'	=> 'کاتی جیهانی+11',
		'Etc/GMT-10'	=> 'کاتی جیهانی+10',
		'Etc/GMT-9'		=> 'کاتی جیهانی+9',
		'Etc/GMT-8'		=> 'کاتی جیهانی+8',
		'Etc/GMT-7'		=> 'کاتی جیهانی+7',
		'Etc/GMT-6'		=> 'کاتی جیهانی+6',
		'Etc/GMT-5'		=> 'کاتی جیهانی+5',
		'Etc/GMT-4'		=> 'کاتی جیهانی+4',
		'Etc/GMT-3'		=> 'کاتی جیهانی+3',
		'Etc/GMT-2'		=> 'کاتی جیهانی+2',
		'Etc/GMT-1'		=> 'کاتی جیهانی+1',
		'Etc/GMT+1'		=> 'کاتی جیهانی-1',
		'Etc/GMT+2'		=> 'کاتی جیهانی-2',
		'Etc/GMT+3'		=> 'کاتی جیهانی-3',
		'Etc/GMT+4'		=> 'کاتی جیهانی-4',
		'Etc/GMT+5'		=> 'کاتی جیهانی-5',
		'Etc/GMT+6'		=> 'کاتی جیهانی-6',
		'Etc/GMT+7'		=> 'کاتی جیهانی-7',
		'Etc/GMT+8'		=> 'کاتی جیهانی-8',
		'Etc/GMT+9'		=> 'کاتی جیهانی-9',
		'Etc/GMT+10'	=> 'کاتی جیهانی-10',
		'Etc/GMT+11'	=> 'کاتی جیهانی-11',
		'Etc/GMT+12'	=> 'کاتی جیهانی-12',

		'Africa/Abidjan'	=> 'ئەفریقا/ئەبیدجان',
		'Africa/Accra'		=> 'ئەفریقا/ئەکرا',
		'Africa/Addis_Ababa'	=> 'ئەفریقا/ئەدیس ئەبابا',
		'Africa/Algiers'	=> 'ئەفریقا/جەزائیر',
		'Africa/Asmara'		=> 'ئەفریقا/ئەسمەرە',
		'Africa/Bamako'		=> 'ئەفریقا/باماکۆ',
		'Africa/Bangui'		=> 'ئەفریقا/بانگی',
		'Africa/Banjul'		=> 'ئەفریقا/بانجول',
		'Africa/Bissau'		=> 'ئەفریقوا/بیسا',
		'Africa/Blantyre'	=> 'ئەفریقا/بلانتیر',
		'Africa/Brazzaville'	=> 'ئەفریقا/برازاڤیل',
		'Africa/Bujumbura'	=> 'ئەفریقا/بوجومبرا',
		'Africa/Cairo'		=> 'ئەفریقا/قاهیرە',
		'Africa/Casablanca'	=> 'ئەفریقا/دارل بەیزاء',
		'Africa/Ceuta'		=> 'ئەفریقا/سبەتە',
		'Africa/Conakry'	=> 'ئەفریقا/کۆناکری',
		'Africa/Dakar'		=> 'ئەفریقا/داکار',
		'Africa/Dar_es_Salaam'	=> 'ئەفریقا/دار سەلام',
		'Africa/Djibouti'	=> 'ئەفریقا/جیبۆوتی',
		'Africa/Douala'		=> 'ئەفریقا/دۆوالا',
		'Africa/El_Aaiun'	=> 'ئەفریقا/ئەلعیون',
		'Africa/Freetown'	=> 'ئەفریقا/فریتاون',
		'Africa/Gaborone'	=> 'ئەفریقا/گابۆرۆن',
		'Africa/Harare'		=> 'ئەفریقا/هەراری',
		'Africa/Johannesburg'	=> 'ئەفریقا/جۆهانسبێرگ',
		'Africa/Juba'		=> 'ئەفریقا/جوبا',
		'Africa/Kampala'	=> 'ئەفریقا/کەمپالا',
		'Africa/Khartoum'	=> 'ئەفریقا/خەرتوم',
		'Africa/Kigali'		=> 'ئەفریقا/کیگالی',
		'Africa/Kinshasa'	=> 'ئەفریقا/كينشاسا',
		'Africa/Lagos'		=> 'ئەفریقا/دەریاکان',
		'Africa/Libreville'	=> 'ئەفریقا/لیبریڤیل',
		'Africa/Lome'		=> 'ئەفریقا/لۆمی',
		'Africa/Luanda'		=> 'ئەفریقا/لواندا',
		'Africa/Lubumbashi'	=> 'ئەفریقا/لوبومباشی',
		'Africa/Lusaka'		=> 'ئەفریقا/لوساكا',
		'Africa/Malabo'		=> 'ئەفریقا/مالابۆ',
		'Africa/Maputo'		=> 'ئەفریقا/ماپوتۆ',
		'Africa/Maseru'		=> 'ئەفریقا/ماسيرو',
		'Africa/Mbabane'	=> 'ئەفریقا/مبابان',
		'Africa/Mogadishu'	=> 'ئەفریقا/مەگەدیشو',
		'Africa/Monrovia'	=> 'ئەفریقا/مونروفيا',
		'Africa/Nairobi'	=> 'ئەفریقا/نەیرۆبی',
		'Africa/Ndjamena'	=> 'ئەفریقا/نجامينا',
		'Africa/Niamey'		=> 'ئەفریقا/نیامی',
		'Africa/Nouakchott'	=> 'ئەفریقا/نواكشۆت',
		'Africa/Ouagadougou'	=> 'ئەفریقا/واگادۆگۆو',
		'Africa/Porto-Novo'	=> 'ئەفریقا/پۆرتۆ-نۆڤۆ',
		'Africa/Sao_Tome'	=> 'ئەفریقا/ساو تۆمی',
		'Africa/Tripoli'	=> 'ئەفریقا/تریپۆلی',
		'Africa/Tunis'		=> 'ئەفریقا/تونس',
		'Africa/Windhoek'	=> 'أفريقيا/ويندهۆك',
		'Africa/Abidjan'	=> 'ئەفریقا/ئەبیدجان',
		'Africa/Accra'		=> 'ئەفریقا/ئەکرا',
		'Africa/Addis_Ababa'	=> 'ئەفریقا/ئەدیس ئەبابا',
		'Africa/Algiers'	=> 'ئەفریقا/جەزائیر',
		'Africa/Asmara'		=> 'ئەفریقا/ئەسمەرە',
		'Africa/Bamako'		=> 'ئەفریقا/باماکۆ',
		'Africa/Bangui'		=> 'ئەفریقا/بانگی',
		'Africa/Banjul'		=> 'ئەفریقا/بانجول',
		'Africa/Bissau'		=> 'ئەفریقا/بیساو',
		'Africa/Blantyre'	=> 'ئەفریقا/بلانتیری',
		'Africa/Brazzaville'	=> 'ئەفریقا/برازاڤیل',
		'Africa/Bujumbura'	=> 'ئەفریقا/بوجومبورا',
		'Africa/Cairo'		=> 'ئەفریقا/قاهیرە',
		'Africa/Casablanca'	=> 'ئەفریقا/دار ئەلەبەیزا',
		'Africa/Ceuta'		=> 'ئەفریقا/سبتە',
		'Africa/Conakry'	=> 'ئەفریقا/کۆناکری',
		'Africa/Dakar'		=> 'ئەفریقا/داکار',
		'Africa/Dar_es_Salaam'	=> 'ئەفریقا/دار ئەلسەلام',
		'Africa/Djibouti'	=> 'ئەفریقا/جیبۆتی',
		'Africa/Douala'		=> 'ئەفریقا/دۆوالا',
		'Africa/El_Aaiun'	=> 'ئەفریقا/ ئەل عیون',
		'Africa/Freetown'	=> 'ئەفریقا/فری تاون',
		'Africa/Gaborone'	=> 'ئەفریقا/گابۆرۆن',
		'Africa/Harare'		=> 'ئەفریقا/هەراری',
		'Africa/Johannesburg'	=> 'ئەفریقا/جۆهانسبێرگ',
		'Africa/Juba'		=> 'ئەفریقا/جوبا',
		'Africa/Kampala'	=> 'ئەفریقا/کمپالا',
		'Africa/Khartoum'	=> 'ئەفریقا/خەرتوم',
		'Africa/Kigali'		=> 'ئەفریقا/کیگالی',
		'Africa/Kinshasa'	=> 'ئەفریقا/کینساشا',
		'Africa/Lagos'		=> 'ئەفریقا/دەریاکان',
		'Africa/Libreville'	=> 'ئەفریقا/لبیرڤیل',
		'Africa/Lome'		=> 'ئەفریقا/لۆمی',
		'Africa/Luanda'		=> 'ئەفریقا/لواندا',
		'Africa/Lubumbashi'	=> 'ئەفریقا/لوبومباشی',
		'Africa/Lusaka'		=> 'ئەفریقا/لوساکا',
		'Africa/Malabo'		=> 'ئەفریقا/مالابۆ',
		'Africa/Maputo'		=> 'ئەفریقا/ماپوتۆ',
		'Africa/Maseru'		=> 'ئەفریقا/ماسیرۆ',
		'Africa/Mbabane'	=> 'ئەفریقا/مبابان',
		'Africa/Mogadishu'	=> 'ئەفریقا/مەگدیشۆ',
		'Africa/Monrovia'	=> 'ئەفریقا/مۆنرۆڤیا',
		'Africa/Nairobi'	=> 'ئەفریقا/نیرۆبی',
		'Africa/Ndjamena'	=> 'ئەفریقا/نامینا',
		'Africa/Niamey'		=> 'ئەفریقا/نیامی',
		'Africa/Nouakchott'	=> 'ئەفریقا/نواکشۆت',
		'Africa/Ouagadougou'	=> 'ئەفریقا/واگادۆگۆ',
		'Africa/Porto-Novo'	=> 'ئەفریقا/پۆرتۆ-نۆڤۆ',
		'Africa/Sao_Tome'	=> 'ئەفریقا/ساو تۆمی',
		'Africa/Tripoli'	=> 'ئەفریقا/تریپلۆی',
		'Africa/Tunis'		=> 'ئەفریقا/تونس',
		'Africa/Windhoek'	=> 'ئەفریقا/ویندهۆک',

		'America/Adak'		=> 'ئەمریکا/ئەداک',
		'America/Anchorage'	=> 'ئەمریکا/ئەنکۆریج',
		'America/Anguilla'	=> 'ئەمریکا/ئەنگیڵا',
		'America/Antigua'	=> 'ئەمریکا/ئەنتیگوا',
		'America/Araguaina'	=> 'ئەمریکا/ئاراگواینا',

		'America/Argentina/Buenos_Aires'	=> 'ئەمریکا/ئەرژەنتین/بوینس ئایرس ',
		'America/Argentina/Catamarca'	=> 'ئەمریکا/ئەرژەنتین/کاتامارا',
		'America/Argentina/Cordoba'		=> 'ئەمریکا/ئەرژەنتین/کۆردۆبا',
		'America/Argentina/Jujuy'		=> 'ئەمریکا/ئەرژەنتین/خوخوی',
		'America/Argentina/La_Rioja'	=> 'ئەمریکا/ئەرژەنتین/لا ڕیۆخا',
		'America/Argentina/Mendoza'		=> 'ئەمریکا/ئەرژەنتین/میندۆزا',
		'America/Argentina/Rio_Gallegos'	=> 'ئەمریکا/ئەرژەنتین/ڕیۆ گاڵیگۆس',
		'America/Argentina/Salta'		=> 'ئەمریکا/ئەرژەنتین/سالتا',
		'America/Argentina/San_Juan'	=> 'ئەمریکا/ئەرژەنتین/سان خوان',
		'America/Argentina/San_Luis'	=> 'ئەمریکا/ئەرژەنتین/سان لویس',
		'America/Argentina/Tucuman'		=> 'ئەمریکا/ئەرژەنتین/توکومان',
		'America/Argentina/Ushuaia'		=> 'ئەمریکا/ئەرژەنتین/ئوشوایا',

		'America/Aruba'			=> 'ئەمریکا/ئەروبا',
		'America/Asuncion'		=> 'ئەمریکا/ئەسونسیۆن',
		'America/Atikokan'		=> 'ئەمریکا/ئەتیکۆکان',
		'America/Bahia'			=> 'ئەمریکا/باهیا',
		'America/Bahia_Banderas'	=> 'ئەمریکا/باهیا باندیراس',
		'America/Barbados'		=> 'ئەمریکا/بەربادۆس',
		'America/Belem'			=> 'ئەمریکا/بیلیم',
		'America/Belize'		=> 'ئەمریکا/بیلیز',
		'America/Blanc-Sablon'	=> 'ئەمریکا/بلانک-سابلۆن',
		'America/Boa_Vista'		=> 'ئەمریکا/بۆوا ڤیستا',
		'America/Bogota'		=> 'ئەمریکا/بۆگۆتا',
		'America/Boise'			=> 'ئەمریکا/بۆیز',
		'America/Cambridge_Bay'	=> 'ئەمریکا/فورگەی کامبریج Bay',
		'America/Campo_Grande'	=> 'ئەمریکا/کامپۆ گراندی',
		'America/Cancun'		=> 'ئەمریکا/کانکوم',
		'America/Caracas'		=> 'ئەمریکا/کەراکاس',
		'America/Cayenne'		=> 'ئەمریکا/کایین',
		'America/Cayman'		=> 'ئەمریکا/کایمان',
		'America/Chicago'		=> 'ئەمریکا/شیکاگۆ',
		'America/Chihuahua'		=> 'ئەمریکا/شیواوا',
		'America/Costa_Rica'	=> 'ئەمریکا/کۆستا ریکا ',
		'America/Creston'		=> 'ئەمریکا/کریستۆن',
		'America/Cuiaba'		=> 'ئەمریکا/کویایا',
		'America/Curacao'		=> 'ئەمریکا/کوراکاو',
		'America/Danmarkshavn'	=> 'ئەمریکا/دانمارکشاڤن',
		'America/Dawson'		=> 'ئەمریکا/داوسن',
		'America/Dawson_Creek'	=> 'ئەمریکا/داوسن کریک',
		'America/Denver'		=> 'ئەمریکا/دینڤر',
		'America/Detroit'		=> 'ئەمریکا/دیترۆیت',
		'America/Dominica'		=> 'ئەمریکا/دۆمینیکا',
		'America/Edmonton'		=> 'ئەمریکا/ئیدمۆنتۆن',
		'America/Eirunepe'		=> 'ئەمریکا/ئیرونیپ',
		'America/El_Salvador'	=> 'ئەمریکا/سلڤادۆر',
		'America/Fortaleza'		=> 'ئەمریکا/فۆرتالیزا',
		'America/Glace_Bay'		=> 'ئەمریکا/دورگەی گلیس ',
		'America/Godthab'		=> 'ئەمریکا/گادتاب',
		'America/Goose_Bay'		=> 'ئەمریکا/دورگەی گوس ',
		'America/Grand_Turk'	=> 'ئەمریکا/گراند تورک',
		'America/Grenada'		=> 'ئەمریکا/گرینادا',
		'America/Guadeloupe'	=> 'ئەمریکا/گوادیلۆپ',
		'America/Guatemala'		=> 'ئەمریکائەمریکا/گواتیمالا',
		'America/Guayaquil'		=> 'ئەمریکا/گوایاکیل',
		'America/Guyana'		=> 'ئەمریکا/گیانا',
		'America/Halifax'		=> 'ئەمریکا/هالیفاکس',
		'America/Havana'		=> 'ئەمریکا/هاڤانا',
		'America/Hermosillo'		=> 'ئەمریکا/هیرمۆسیلۆ',
		'America/Indiana/Indianapolis'	=> 'ئەمریکا/ئیندیانا/ئیندیاناپۆلیس',
		'America/Indiana/Knox'		=> 'ئەمریکا/ئیندیانا/نوکس',
		'America/Indiana/Marengo'	=> 'ئەمریکا/ئیندیانا/مارینگۆ',
		'America/Indiana/Petersburg'	=> 'ئەمریکا/ئیندیانا/پیترسبرگ',
		'America/Indiana/Tell_City'	=> 'ئەمریکا/ئیندیانا/شاری تیل',
		'America/Indiana/Vevay'		=> 'ئەمریکا/ئیندیانا/ڤیڤای',
		'America/Indiana/Vincennes'	=> 'ئەمریکا/ئیندیانا/ڤینسین',
		'America/Indiana/Winamac'	=> 'ئەمریکا/ئیندیانا/ویناماک',
		'America/Inuvik'		=> 'ئەمریکا/ئینوڤیک',
		'America/Iqaluit'		=> 'ئەمریکا/ئیکالویت',
		'America/Jamaica'		=> 'ئەمریکا/جامایکا',
		'America/Juneau'		=> 'ئەمریکا/جونو',
		'America/Kentucky/Louisville'	=> 'ئەمریکا/کنتاکی/لویزڤیل',
		'America/Kentucky/Monticello'	=> 'ئەمریکا/کنتاکی/مونتیشیلو',
		'America/Kralendijk'	=> 'ئەمریکا/کرالندیک',
		'America/La_Paz'		=> 'ئەمریکا/لا پاز',
		'America/Lima'			=> 'ئەمریکا/لیما',
		'America/Los_Angeles'	=> 'ئەمریکا/لۆس ئەنجلۆس',
		'America/Lower_Princes'	=> 'ئەمریکا/لاور پرینسس',
		'America/Maceio'		=> 'ئەمریکا/ماسیۆ',
		'America/Managua'		=> 'ئەمریکا/ماناگوا',
		'America/Manaus'		=> 'ئەمریکا/ماناوس',
		'America/Marigot'		=> 'ئەمریکا/ماریگۆت',
		'America/Martinique'	=> 'ئەمریکا/مارتینیک',
		'America/Matamoros'		=> 'ئەمریکا/ماتاموروس',
		'America/Mazatlan'		=> 'ئەمریکا/مازاتلان',
		'America/Menominee'		=> 'ئەمریکا/مینومینی',
		'America/Merida'		=> 'ئەمریکا/میریدا',
		'America/Metlakatla'	=> 'ئەمریکا/میتلاکاتلا',
		'America/Mexico_City'	=> 'ئەمریکا/مەکسیکۆ سیتی ',
		'America/Miquelon'		=> 'ئەمریکا/میکلۆن',
		'America/Moncton'		=> 'ئەمریکا/مۆنکتۆن',
		'America/Monterrey'		=> 'ئەمریکا/مۆنتیری',
		'America/Montevideo'	=> 'ئەمریکا/مۆنتیڤیدیۆ',
		'America/Montreal'		=> 'ئەمریکا/مۆنتریرال',
		'America/Montserrat'	=> 'ئەمریکا/مۆنتسیرات',
		'America/Nassau'		=> 'ئەمریکا/ناسو',
		'America/New_York'		=> 'ئەمریکا/نیۆرک ',
		'America/Nipigon'		=> 'ئەمریکا/نیپیگۆن',
		'America/Nome'			=> 'ئەمریکا/نۆم',
		'America/Noronha'		=> 'ئەمریکا/نۆرۆنها',
		'America/North_Dakota/Beulah'		=> 'ئەمریکا/داکوتای باشور/بیولا',
		'America/North_Dakota/Center'		=> 'ئەمریکا/داکوتای باشور/سینتەر',
		'America/North_Dakota/New_Salem'	=> 'ئەمریکا/داکوتای باشور/نیو سالیم',
		'America/Ojinaga'		=> 'ئەمریکا/ئۆجیناگا',
		'America/Panama'		=> 'ئەمریکا/پەنەما',
		'America/Pangnirtung'	=> 'ئەمریکا/پانگنیرتونگ',
		'America/Paramaribo'	=> 'ئەمریکا/پاراماریبۆ',
		'America/Phoenix'		=> 'ئەمریکا/ڤینیکس',
		'America/Port-au-Prince'	=> 'ئەمریکا/پۆرت-ئەو-پرینس',
		'America/Port_of_Spain'	=> 'ئەمریکا/بەندەری ئیسپانیان',
		'America/Porto_Velho'	=> 'ئەمریکا/پۆرتۆ ڤیلهۆ',
		'America/Puerto_Rico'	=> 'ئەمریکا/پیرتۆ ڕیکۆ',
		'America/Rainy_River'	=> 'ئەمریکا/ڕەنینی ڕیڤەر',
		'America/Rankin_Inlet'	=> 'ئەمریکا/ڕانکین ئنلینت Inlet',
		'America/Recife'		=> 'ئەمریکا/ریسیف',
		'America/Regina'		=> 'ئەمریکا/ڕیگینا',
		'America/Resolute'		=> 'ئەمریکا/ریزۆلیوت',
		'America/Rio_Branco'	=> 'ئەمریکا/ڕیۆ برانکۆ',
		'America/Santa_Isabel'	=> 'ئەمریکا/سانتا ئیزابیل',
		'America/Santarem'		=> 'ئەمریکا/سانتاریم',
		'America/Santiago'		=> 'ئەمریکا/سانتیاگۆ',
		'America/Santo_Domingo'	=> 'ئەمریکا/سانتۆ دۆمینگۆ',
		'America/Sao_Paulo'		=> 'ئەمریکا/ساو پاولۆ',
		'America/Scoresbysund'	=> 'ئەمریکا/سکۆریسبیسوند',
		'America/Shiprock'		=> 'ئەمریکا/شیپرۆک',
		'America/Sitka'			=> 'ئەمریکا/سیتکا',
		'America/St_Barthelemy'	=> 'ئەمریکا/سانت. بارسیلمی',
		'America/St_Johns'		=> 'ئەمریکا/سانت. جۆنز',
		'America/St_Kitts'		=> 'ئەمریکا/سانت. کیتس',
		'America/St_Lucia'		=> 'ئەمریکا/سانت. لوسیا',
		'America/St_Thomas'		=> 'ئەمریکا/سانت. تۆماس',
		'America/St_Vincent'	=> 'ئەمریکا/سانت. ڤینسینت',
		'America/Swift_Current'	=> 'ئەمریکا/سویفت کارنت',
		'America/Tegucigalpa'	=> 'ئەمریکا/تیگویسیگالپا',
		'America/Thule'			=> 'ئەمریکا/سول',
		'America/Thunder_Bay'	=> 'ئەمریکا/دورگەی سوندەر ',
		'America/Tijuana'		=> 'ئەمریکا/تیجوانا',
		'America/Toronto'		=> 'ئەمریکا/تۆرنتۆ',
		'America/Tortola'		=> 'ئەمریکا/تۆرتۆلا',
		'America/Vancouver'		=> 'ئەمریکا/ڤانکۆڤیر',
		'America/Whitehorse'	=> 'ئەمریکا/وایتهۆرس',
		'America/Winnipeg'		=> 'ئەمریکا/وینیپیگ',
		'America/Yakutat'		=> 'ئەمریکا/یاکوتات',
		'America/Yellowknife'	=> 'ئەمریکا/یلونایف',

		'Antarctica/Casey'		=> 'ئەنتارکتیکا/کەیسی',
		'Antarctica/Davis'		=> 'ئەنتارکتیکا/داڤیس',
		'Antarctica/DumontDUrville'	=> 'ئەنتارکتیکا/دومۆن دورڤیل',
		'Antarctica/Macquarie'	=> 'ئەنتارکتیکا/ماکواری',
		'Antarctica/Mawson'		=> 'ئەنتارکتیکا/ماوسۆن',
		'Antarctica/McMurdo'	=> 'ئەنتارکتیکا/موردۆ',
		'Antarctica/Palmer'		=> 'ئەنتارکتیکا/پالمر',
		'Antarctica/Rothera'	=> 'ئەنتارکتیکا/رۆسیرا',
		'Antarctica/South_Pole'	=> 'ئەنتارکتیکا/خەمسەری باکور',
		'Antarctica/Syowa'		=> 'ئەنتارکتیکا/سیۆوا',
		'Antarctica/Vostok'		=> 'ئەنتارکتیکا/ڤۆستۆک',

		'Arctic/Longyearbyen'	=> 'جەمسەری باشور/لۆنگیاربین',

		'Asia/Aden'			=> 'ئاسیا/عەدەن',
		'Asia/Almaty'		=> 'ئاسیا/ئەلماتی',
		'Asia/Amman'		=> 'ئاسیا/عەمان',
		'Asia/Anadyr'		=> 'ئاسیا/ئەنادیر',
		'Asia/Aqtau'		=> 'ئاسیا/ئەکتا',
		'Asia/Aqtobe'		=> 'ئاسیا/ئەکتۆبی',
		'Asia/Ashgabat'		=> 'ئاسیا/ئەشق ئاباد',
		'Asia/Baghdad'		=> 'ئاسیا/بەغداد',
		'Asia/Bahrain'		=> 'ئاسیا/بەحرەین',
		'Asia/Baku'			=> 'ئاسیا/باکو',
		'Asia/Bangkok'		=> 'ئاسیا/بانکۆک',
		'Asia/Beirut'		=> 'ئاسیا/بەیروت',
		'Asia/Bishkek'		=> 'ئاسیا/بیشکیک',
		'Asia/Brunei'		=> 'ئاسیا/برونای',
		'Asia/Choibalsan'	=> 'ئاسیا/شویبالسان',
		'Asia/Chongqing'	=> 'ئاسیا/چۆنگقینگ',
		'Asia/Colombo'		=> 'ئاسیا/کۆلۆبۆ',
		'Asia/Damascus'		=> 'ئاسیا/دیمەشق',
		'Asia/Dhaka'		=> 'ئاسیا/دەکا',
		'Asia/Dili'			=> 'ئاسیا/دیلی',
		'Asia/Dubai'		=> 'ئاسیا/دوبەی',
		'Asia/Dushanbe'		=> 'ئاسیا/دوشەنبە',
		'Asia/Gaza'			=> 'ئاسیا/غەزە',
		'Asia/Harbin'		=> 'ئاسیا/هاربین',
		'Asia/Hebron'		=> 'ئاسیا/هیبرۆن',
		'Asia/Ho_Chi_Minh'	=> 'ئاسیا/هۆ چی مینهـ',
		'Asia/Hong_Kong'	=> 'ئاسیا/هۆنگ کۆنگ',
		'Asia/Hovd'			=> 'ئاسیا/گوود',
		'Asia/Irkutsk'		=> 'ئاسیا/ئیرکۆتسک',
		'Asia/Jakarta'		=> 'ئاسیا/جاکارتا',
		'Asia/Jayapura'		=> 'ئاسیا/جایابورا',
		'Asia/Jerusalem'	=> 'ئاسیا/قودس',
		'Asia/Kabul'		=> 'ئاسیا/کابول',
		'Asia/Kamchatka'	=> 'ئاسیا/کەمەچەتکا',
		'Asia/Karachi'		=> 'ئاسیا/کراشی',
		'Asia/Kashgar'		=> 'ئاسیا/کاشگەر',
		'Asia/Kathmandu'	=> 'ئاسیا/کاتماندو',
		'Asia/Khandyga'		=> 'ئاسیا/خاندیگە',
		'Asia/Kolkata'		=> 'ئاسیا/کالکتە',
		'Asia/Krasnoyarsk'	=> 'ئاسیا/کراسنۆیارسک',
		'Asia/Kuala_Lumpur'	=> 'ئاسیا/کوالا لەمپور',
		'Asia/Kuching'		=> 'ئاسیا/کوچینگ',
		'Asia/Kuwait'		=> 'ئاسیا/کوێت',
		'Asia/Macau'		=> 'ئاسیا/مەککە',
		'Asia/Magadan'		=> 'ئاسیا/ماگادان',
		'Asia/Makassar'		=> 'ئاسیا/ماکاسار',
		'Asia/Manila'		=> 'ئاسیا/مایلا',
		'Asia/Muscat'		=> 'ئاسیا/مەسقەت',
		'Asia/Nicosia'		=> 'ئاسیا/نیقۆسیا',
		'Asia/Novokuznetsk'	=> 'ئاسیا/نۆڤۆکۆزینتسک',
		'Asia/Novosibirsk'	=> 'ئاسیا/نۆڤیسبیرسک',
		'Asia/Omsk'			=> 'ئاسیا/ئۆمسک',
		'Asia/Oral'			=> 'ئاسیا/ئۆڕال',
		'Asia/Phnom_Penh'	=> 'ئاسیا/پنۆم پینە',
		'Asia/Pontianak'	=> 'ئاسیا/پۆنتیاناک',
		'Asia/Pyongyang'	=> 'ئاسیا/پیۆنگ یانگ',
		'Asia/Qatar'		=> 'ئاسیا/قەتەر',
		'Asia/Qyzylorda'	=> 'ئاسیا/قیزیلۆردا',
		'Asia/Rangoon'		=> 'ئاسیا/رانگوون',
		'Asia/Riyadh'		=> 'ئاسیا/ڕیاز',
		'Asia/Sakhalin'		=> 'ئاسیا/سەخالین',
		'Asia/Samarkand'	=> 'ئاسیا/سەمەرقەند',
		'Asia/Seoul'		=> 'ئاسیا/سیۆل',
		'Asia/Shanghai'		=> 'ئاسیا/شانگهای',
		'Asia/Singapore'	=> 'ئاسیا/سەنگافور',
		'Asia/Taipei'		=> 'ئاسیا/تایپی',
		'Asia/Tashkent'		=> 'ئاسیا/تەشکند',
		'Asia/Tbilisi'		=> 'ئاسیا/تبلیسی',
		'Asia/Tehran'		=> 'ئاسیا/تاران',
		'Asia/Thimphu'		=> 'ئاسیا/تیمفو',
		'Asia/Tokyo'		=> 'ئاسیا/تۆکیۆ',
		'Asia/Ulaanbaatar'	=> 'ئاسیا/ئولانباتار',
		'Asia/Urumqi'		=> 'ئاسیا/ئورومچی',
		'Asia/Ust-Nera'		=> 'ئاسیا/ئوست-نیرا',
		'Asia/Vientiane'	=> 'ئاسیا/ڤینتیان',
		'Asia/Vladivostok'	=> 'ئاسیا/ڤلادیڤۆستۆک',
		'Asia/Yakutsk'		=> 'ئاسیا/یاکوتسک',
		'Asia/Yekaterinburg'	=> 'ئاسیا/یکاترینبیرگ',
		'Asia/Yerevan'		=> 'ئاسیا/یریڤان',

		'Atlantic/Azores'		=> 'زەریای ئەتلەس/ئەزۆریس',
		'Atlantic/Bermuda'		=> 'زەریای ئەتلەس/بەرمودا',
		'Atlantic/Canary'		=> 'زەریای ئەتلەس/کەناری',
		'Atlantic/Cape_Verde'	=> 'زەریای ئەتلەس/دەماخە سەوز',
		'Atlantic/Faroe'		=> 'زەریای ئەتلەس/فارۆ',
		'Atlantic/Madeira'		=> 'زەریای ئەتلەس/مادیرا',
		'Atlantic/Reykjavik'	=> 'زەریای ئەتلەس/ریکیاڤیک',
		'Atlantic/South_Georgia'	=> 'زەریای ئەتلەس/جۆرجیای باکور',
		'Atlantic/St_Helena'	=> 'زەریای ئەتلەس/سانت هیلینا',
		'Atlantic/Stanley'		=> 'زەریای ئەتلەس/ستانللی',

		'Australia/Adelaide'	=> 'ئوسترالیا/ئەدیلەید',
		'Australia/Brisbane'	=> 'ئوسترالیا/بریزبین',
		'Australia/Broken_Hill'	=> 'ئوسترالیا/برۆکن هێل',
		'Australia/Currie'		=> 'ئوسترالیا/کاری',
		'Australia/Darwin'		=> 'ئوسترالیا/داروین',
		'Australia/Eucla'		=> 'ئوسترالیا/یوکلا',
		'Australia/Hobart'		=> 'ئوسترالیا/هۆبارت',
		'Australia/Lindeman'	=> 'ئوسترالیا/لیندمان',
		'Australia/Lord_Howe'	=> 'ئوسترالیا/لۆرد هاو',
		'Australia/Melbourne'	=> 'ئوسترالیا/ملبۆرن',
		'Australia/Perth'		=> 'ئوسترالیا/پیرس',
		'Australia/Sydney'		=> 'ئوسترالیا/سیدنی',

		'Europe/Amsterdam'	=> 'ئەوروپا/ئەمستردام',
		'Europe/Andorra'	=> 'ئەوروپا/ئەندۆڕا',
		'Europe/Athens'		=> 'ئەوروپا/ئەسینا',
		'Europe/Belgrade'	=> 'ئەوروپا/بیلگراد',
		'Europe/Berlin'		=> 'ئەوروپا/بەرلین',
		'Europe/Bratislava'	=> 'ئەوروپا/براتیسڤالا',
		'Europe/Brussels'	=> 'ئەوروپا/بروسلیس',
		'Europe/Bucharest'	=> 'ئەوروپا/بوخارست',
		'Europe/Budapest'	=> 'ئەوروپا/بوداپیست',
		'Europe/Busingen'	=> 'ئەوروپا/بوسینگن',
		'Europe/Chisinau'	=> 'ئەوروپا/کیشیناو',
		'Europe/Copenhagen'	=> 'ئەوروپا/کۆپنهاگن',
		'Europe/Dublin'		=> 'ئەوروپا/دبلن',
		'Europe/Gibraltar'	=> 'ئەوروپا/جەبەل تارق',
		'Europe/Guernsey'	=> 'ئەوروپا/گویرنسی',
		'Europe/Helsinki'	=> 'ئەوروپا/هیلسنکی',
		'Europe/Isle_of_Man'	=> 'ئەوروپا/ئایک ئۆف مان',
		'Europe/Istanbul'	=> 'ئەوروپا/ئیستەنبول',
		'Europe/Jersey'		=> 'ئەوروپا/جیرسی',
		'Europe/Kaliningrad'	=> 'ئەوروپا/کالینیگراد',
		'Europe/Kiev'		=> 'ئەوروپا/کییف',
		'Europe/Lisbon'		=> 'ئەوروپا/لیشبۆن',
		'Europe/Ljubljana'	=> 'ئەوروپا/لیوبلیانا',
		'Europe/London'		=> 'ئەوروپا/لەندەن',
		'Europe/Luxembourg'	=> 'ئەوروپا/لوکسمبۆرگ',
		'Europe/Madrid'		=> 'ئەوروپا/مەدرید',
		'Europe/Malta'		=> 'ئەوروپا/مەلتا',
		'Europe/Mariehamn'	=> 'ئەوروپا/ماریهامن',
		'Europe/Minsk'		=> 'ئەوروپا/مینسک',
		'Europe/Monaco'		=> 'ئەوروپا/مۆناکۆ',
		'Europe/Moscow'		=> 'ئەوروپا/مۆسکۆ',
		'Europe/Oslo'		=> 'ئەوروپا/ئۆسلۆ',
		'Europe/Paris'		=> 'ئەوروپا/پاریس',
		'Europe/Podgorica'	=> 'ئەوروپا/پوتگۆریشا',
		'Europe/Prague'		=> 'ئەوروپا/براگ',
		'Europe/Riga'		=> 'ئەوروپا/ریگا',
		'Europe/Rome'		=> 'ئەوروپا/ڕۆما',
		'Europe/Samara'		=> 'ئەوروپا/سەمارا',
		'Europe/San_Marino'	=> 'ئەوروپا/سان مارینۆ',
		'Europe/Sarajevo'	=> 'ئەوروپا/سەراییڤۆ',
		'Europe/Simferopol'	=> 'ئەوروپا/سیمفیرپۆل',
		'Europe/Skopje'		=> 'ئەوروپا/سکۆپی',
		'Europe/Sofia'		=> 'ئەوروپا/سۆفیا',
		'Europe/Stockholm'	=> 'ئەوروپا/ستۆکهۆلم',
		'Europe/Tallinn'	=> 'ئەوروپا/تالین',
		'Europe/Tirane'		=> 'ئەوروپا/تیرانا',
		'Europe/Uzhgorod'	=> 'ئەوروپا/ئوزگۆرۆد',
		'Europe/Vaduz'		=> 'ئەوروپا/ڤادوز',
		'Europe/Vatican'	=> 'ئەوروپا/ڤاتیکان',
		'Europe/Vienna'		=> 'ئەوروپا/ڤییەنا',
		'Europe/Vilnius'	=> 'ئەوروپا/ڤیلنیوس',
		'Europe/Volgograd'	=> 'ئەوروپا/ڤۆلگۆگراد',
		'Europe/Warsaw'		=> 'ئەوروپا/وارسەو',
		'Europe/Zagreb'		=> 'ئەوروپا/زەگریب',
		'Europe/Zaporozhye'	=> 'ئەوروپا/زاپۆرۆژی',
		'Europe/Zurich'		=> 'ئەوروپا/زیورخ',

		'Indian/Antananarivo'	=> 'زەریای هیندی/ئەنتاناناریڤۆ',
		'Indian/Chagos'		=> 'زەریای هیندی/چاگۆس',
		'Indian/Christmas'	=> 'زەریای هیندی/کریسماس',
		'Indian/Cocos'		=> 'زەریای هیندی/کۆکۆس',
		'Indian/Comoro'		=> 'زەریای هیندی/کۆمۆرۆس',
		'Indian/Kerguelen'	=> 'زەریای هیندی/کیرگولین',
		'Indian/Mahe'		=> 'زەریای هیندی/ماهی',
		'Indian/Maldives'	=> 'زەریای هیندی/مالدیڤ',
		'Indian/Mauritius'	=> 'زەریای هیندی/موریشیوس',
		'Indian/Mayotte'	=> 'زەریای هیندی/مایۆت',
		'Indian/Reunion'	=> 'زەریای هیندی/ڕیونیۆن',

		'Pacific/Apia'		=> 'زەریای هێمن/ئاپیا',
		'Pacific/Auckland'	=> 'زەریای هێمن/ئوکلاند',
		'Pacific/Chatham'	=> 'زەریای هێمن/چاتام',
		'Pacific/Chuuk'		=> 'زەریای هێمن/چوک',
		'Pacific/Easter'	=> 'زەریای هێمن/ئەوپەڕی ڕۆژهەلات',
		'Pacific/Efate'		=> 'زەریای هێمن/ئیفاتی',
		'Pacific/Enderbury'	=> 'زەریای هێمن/ئیندربوری',
		'Pacific/Fakaofo'	=> 'زەریای هێمن/فاکاوفۆ',
		'Pacific/Fiji'		=> 'زەریای هێمن/فیجی',
		'Pacific/Funafuti'	=> 'زەریای هێمن/فونافوتی',
		'Pacific/Galapagos'	=> 'زەریای هێمن/گالاپاگوس',
		'Pacific/Gambier'	=> 'زەریای هێمن/گامبیر',
		'Pacific/Guadalcanal'	=> 'زەریای هێمن/گوادالکەنال',
		'Pacific/Guam'		=> 'زەریای هێمن/گوام',
		'Pacific/Honolulu'	=> 'زەریای هێمن/هۆنۆلولو',
		'Pacific/Johnston'	=> 'زەریای هێمن/جۆنستۆن',
		'Pacific/Kiritimati'	=> 'زەریای هێمن/کیریتیماتی',
		'Pacific/Kosrae'	=> 'زەریای هێمن/کۆسرای',
		'Pacific/Kwajalein'	=> 'زەریای هێمن/کواجالین',
		'Pacific/Majuro'	=> 'زەریای هێمن/ماجورۆ',
		'Pacific/Marquesas'	=> 'زەریای هێمن/مارکێز',
		'Pacific/Midway'	=> 'زەریای هێمن/میدوای',
		'Pacific/Nauru'		=> 'زەریای هێمن/ناورو',
		'Pacific/Niue'		=> 'زەریای هێمن/نیوی',
		'Pacific/Norfolk'	=> 'زەریای هێمن/نۆفۆلک',
		'Pacific/Noumea'	=> 'زەریای هێمن/نۆمیا',
		'Pacific/Pago_Pago'	=> 'زەریای هێمن/پاگۆ پاگۆ',
		'Pacific/Palau'		=> 'زەریای هێمن/پالاو',
		'Pacific/Pitcairn'	=> 'زەریای هێمن/پیتکایرن',
		'Pacific/Pohnpei'	=> 'زەریای هێمن/پۆهنبای',
		'Pacific/Port_Moresby'	=> 'زەریای هێمن/بەندەری مۆرسبی',
		'Pacific/Rarotonga'	=> 'زەریای هێمن/ڕاڕۆتۆنگا',
		'Pacific/Saipan'	=> 'زەریای هێمن/سایپان',
		'Pacific/Tahiti'	=> 'زەریای هێمن/تاهیتی',
		'Pacific/Tarawa'	=> 'زەریای هێمن/تاراوا',
		'Pacific/Tongatapu'	=> 'زەریای هێمن/تۆنگاتاپو',
		'Pacific/Wake'		=> 'زەریای هێمن/ویک',
		'Pacific/Wallis'	=> 'زەریای هێمن/والیس',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 کانوونی دووەم 2007, 13:37',
		'd M Y H:i'				=> '01 کانوونی دووەم 2007 13:37',
		'M jS, \'y, H:i'		=> 'کانوونی دووەم, \'07, 13:37',
		'D M d, Y g:i a'		=> 'کانوونی دووەم 01, 2007 1:37 ئێوارە',
		'F jS, Y, g:i a'		=> 'کانوونی دووەم, 2007, 1:37 ئێوارە',
		'|d M Y|, H:i'			=> 'ئەمڕۆ, 13:37 / 01 کانوونی دووەم 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 ئێوارە / کانونی دووەم, 2007, 1:37 ئێوارە',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
