<?php
/**
*
* mcp.php [Sorani Kurdish]
*
* @package language
* @version $Id: $
* @copyright (c) 2008 phpBB Group
* @author 2008-12-13 - Chawg.org Group
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACTION'	=> 'چالاکی',
	'ACTION_NOTE'	=> 'چالاکی/ تێبینی',
	'ADD_FEEDBACK'	=> 'لێدوانمان بۆ بدە',
	'ADD_FEEDBACK_EXPLAIN'	=> 'ئەگەر خوازیاریت بەزیادکردنی ڕاپۆرتێک تکایە ئەم فۆڕمەی خوارەوە پڕبکەوە تەنها دەقی تەخت بەکارببە، HTML، BBCode، ڕێ پێ نەدراوە.',
	'ADD_WARNING'	=> 'ئاگاداری زیاد بکە',
	'ADD_WARNING_EXPLAIN'	=> 'بۆ ئاگادار کردنەوەی ئەم بەکارهێنەرە تکایە ئەم فۆڕمەی خوارەوە پڕ بکەوە تەنها دەقی تەخت بەکار ببە؛ HTML، BBCode، ڕێ پێ نەدراوە.',
	'ALL_ENTRIES'	=> 'هەموو دانەکان',
	'ALL_NOTES_DELETED'	=> 'هەموو سەرنجەکانی بەکارهێنەر بە سەرکەوتوویی لابران.',
	'ALL_REPORTS'	=> 'هەموو ڕاپۆرتەکان',
	'ALREADY_REPORTED'	=> 'ئەم پەیامە پێشتر ڕاپۆرتکراوە.',
	'ALREADY_REPORTED_PM'	=> 'ئەم پەیامە تایبەتە پێشتر ڕاپۆرتکراوە.',
	'ALREADY_WARNED'	=> 'پێشتر ئاگادارییەک هاتووە بۆ ئەم پەیامە',
	'APPROVE'	=> 'پەسەندکردن',
	'APPROVE_POST'	=> 'پەیام پەسەند بکە',
	'APPROVE_POST_CONFIRM'	=> 'دڵنیایت لە پەسەند کردنی ئەم پەیامە؟',
	'APPROVE_POSTS'	=> 'پەیامەکان پەسەند بکە',
	'APPROVE_POSTS_CONFIRM'	=> 'دڵنیایت لە پەسەند کردنی پەیامە دیاریکراوەکان؟',
	'CANNOT_MOVE_SAME_FORUM'	=> 'ناتوانیت بابەتێک بگوازییتەوە بۆ مەکۆیەک کە خۆی لەوێدایە.',
	'CANNOT_WARN_ANONYMOUS'	=> 'ناتوانیت بەکارهێنەرە میوانە خۆ تۆمار نەکردووەکان ئاگادار بکەیتەوە.',
	'CANNOT_WARN_SELF'	=> 'ناتوانی خۆت ئاگادار بکەیتەوە',
	'CAN_LEAVE_BLANK'	=> 'ئەمە ئەتوانرێت بە بەتاڵی جێبهێڵدرێت.',
	'CHANGE_POSTER'	=> 'نووسەر بگۆڕە',
	'CLOSE_PM_REPORT'		=> 'ڕاپۆرتی پەیامی تایبەت دابخە',
	'CLOSE_PM_REPORT_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتی پەیامی تایبەتی دیاریکراو؟',
	'CLOSE_PM_REPORTS'		=> 'ڕاپۆرتەکانی پەیامی تایبەت دابخە',
	'CLOSE_PM_REPORTS_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتی پەیامە تایبەتییە دیاریکراوەکان؟',
	'CLOSE_REPORT'	=> 'ڕاپۆرت دابخە',
	'CLOSE_REPORT_CONFIRM'	=> 'دڵنیات لە داخستنی ئەم ڕاپۆرتە دیاریکراوە؟',
	'CLOSE_REPORTS'	=> 'ڕاپۆرتەکان دابخە',
	'CLOSE_REPORTS_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتە دیاریکراوەکان؟',
	'DELETE_PM_REPORT'	=> 'ڕاپۆرتی پەیامی تایبەت دابخە',
	'DELETE_PM_REPORT_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی پەیامی تایبەتی دیاریکراو؟',
	'DELETE_PM_REPORTS'			=> 'ڕاپۆرتەکانی پەیامی تایبەت بسڕەوە',
	'DELETE_PM_REPORTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی پەیامە تایبەتییە دیاریکراوەکان؟',
	'DELETE_POSTS'	=> 'پەیامەکان بسڕەوە',
	'DELETE_POSTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم پەیامانە؟',
	'DELETE_POST_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم پەیامە؟',
	'DELETE_REPORT'	=> 'ڕاپۆرت بسڕەوە',
	'DELETE_REPORT_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی دیاریکراو؟',
	'DELETE_REPORTS'	=> 'ڕاپۆرتەکان بسڕەوە',
	'DELETE_REPORTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتە دیاریکراوەکان؟',
	'DELETE_SHADOW_TOPIC'	=> 'بابەتی سێبر بسڕەوە',
	'DELETE_TOPICS'	=> 'بابەتە دیاریکراوەکان بسڕەوە',
	'DELETE_TOPICS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم بابەتانە؟',
	'DELETE_TOPIC_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم بابەتە؟',
	'DISAPPROVE'	=> 'ناپەسەندکردن',
	'DISAPPROVE_REASON'	=> 'هۆکاری ناپەسەندکردن',
	'DISAPPROVE_POST'	=> 'پەیام ناپەسەند بکە',
	'DISAPPROVE_POST_CONFIRM'	=> 'دڵنیات لە پەسەند نەکردنی ئەم پەیامە؟',
	'DISAPPROVE_POSTS'	=> 'پەیامەکان پەسەند مەکە',
	'DISAPPROVE_POSTS_CONFIRM'	=> 'دڵنیایت لە پەسەند نەکردنی پەیامە دیاریکراوەکان؟',
	'DISPLAY_LOG'	=> 'پەیامەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_OPTIONS'	=> 'هەڵبژاردنەکانی پیشاندان',
	'EMPTY_REPORT'	=> 'پێویستە پەسنێک بنووسیت لە کاتی دیاریکردنی ئەم هۆکارە.',
	'EMPTY_TOPICS_REMOVED_WARNING'	=> 'تکایە سەرنجی ئەوە بدە کە یەکێک یان چەند بابەتێک لە بنکەدراوەکەمان لابراوە لەبەر ئەوە بەتاڵ بوون.',
	'FEEDBACK'	=> 'Feedback',
	'FORK'	=> 'ڕوونووس',
	'FORK_TOPIC'	=> 'بابەت ڕوونووس بکە',
	'FORK_TOPIC_CONFIRM'	=> 'دڵنیات لە ڕوونووسکردنی ئەم پەیامە؟',
	'FORK_TOPICS'	=> 'پەیامە دیاریکراوەکان ڕوونووس بکە',
	'FORK_TOPICS_CONFIRM'	=> 'دڵنیایت لە ڕوونووسکردنی پەیامە دیاریکراوەکان؟',
	'FORUM_DESC'	=> 'پەسن',
	'FORUM_NAME'	=> 'ناوی مەکۆ',
	'FORUM_NOT_EXIST'	=> 'ئەو مەکۆیەی دیاریت کردووە بوونی نییە',
	'FORUM_NOT_POSTABLE'	=> 'ناتوانرێت ئەو مەکۆیەی دیاریت کردووە پەیامی بۆ بنێردرێت.',
	'FORUM_STATUS'	=> 'دۆخی مەکۆ',
	'FORUM_STYLE'	=> 'ڕووخساری مەکۆ',
	'GLOBAL_ANNOUNCEMENT'	=> 'ئاگاداری گشتیی',
	'IP_INFO'	=> 'زانیاریی ناونیشانی IP',
	'IPS_POSTED_FROM'	=> 'ئەو ناونیشانی IP ـیانەی ئەم بەکارهێنەرە پەیامی لێیەوە ناردووە',
	'LATEST_LOGS'	=> 'دوا ٥ چالاکی چوونە ژوورەوە',
	'LATEST_REPORTED'	=> 'دوا ٥ ڕاپۆرتەکان',
	'LATEST_REPORTED_PMS'		=> 'دوا ٥ ڕاپۆرتی پەیامی تایبەت',
	'LATEST_UNAPPROVED'	=> 'دوا ٥ پەیام کە چاوەڕوانی پەسەندکردنن',
	'LATEST_WARNING_TIME'	=> 'دوا ئاگادارییەکان',
	'LATEST_WARNINGS'	=> 'دوا ٥ ئاگادارییەکان',
	'LEAVE_SHADOW'	=> 'بابەتی سێبەراوی لە جێی خۆیدا بهێڵەوە',
	'LIST_REPORT'	=> '1 ڕاپۆرت',
	'LIST_REPORTS'	=> '%d ڕاپۆرت',
	'LOCK'	=> 'داخستن',
	'LOCK_POST_POST'	=> 'داخستنی پەیام',
	'LOCK_POST_POST_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی ئەم پەیامە لە دەستکاریکردن؟',
	'LOCK_POST_POSTS'	=> 'پەیامە دیاریکراوەکان دابخە',
	'LOCK_POST_POSTS_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی پەیامە دیاریکراوەکان لە دەستکاریکردن؟',
	'LOCK_TOPIC_CONFIRM'	=> 'دڵنیایت لە داخستنی ئەم بابەتە؟',
	'LOCK_TOPICS'	=> 'بابەتە دیاریکراوەکان دابخە',
	'LOCK_TOPICS_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی هەموو بابەتە دیاریکراوەکان؟',
	'LOGS_CURRENT_TOPIC'	=> 'هەنووکە لۆگەکانی ئەمە دەبینیت:',
	'LOGIN_EXPLAIN_MCP'	=> 'بۆ چاودێریکردنی ئەم مەکۆیە پێویستە بچیتە ژوورەوە.',
	'LOGVIEW_VIEWTOPIC'	=> 'بینینی بابەت',
	'LOGVIEW_VIEWLOGS'	=> 'لۆگی بابەت ببینە',
	'LOGVIEW_VIEWFORUM'	=> 'بینینی مەکۆ',
	'LOOKUP_ALL'	=> 'سەیری هەموو IP ـیەکان بکە',
	'LOOKUP_IP'	=> 'سەیری IP بکە',
	'MARKED_NOTES_DELETED'	=> 'بە سەرکەوتوویی هەموو سەرنجە نیشانەکراوەکانی بەکارهێنەر لابران.',
	'MCP_ADD'	=> 'ئاگادارییەک دابنێ',
	'MCP_BAN'	=> 'ڕاگرتن',
	'MCP_BAN_EMAILS'	=> 'ڕاگرتنی ئیمەیل',
	'MCP_BAN_IPS'	=> 'ڕاگرتنی IP',
	'MCP_BAN_USERNAMES'	=> 'ڕاگرتنی بەکارهێنەران',
	'MCP_LOGS'	=> 'لۆگەکانی چاودێر',
	'MCP_LOGS_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_LOGS_FORUM_VIEW'	=> 'لۆگەکانی مەکۆ',
	'MCP_LOGS_TOPIC_VIEW'	=> 'لۆگەکانی بابەت',
	'MCP_MAIN'	=> 'سەرەکی',
	'MCP_MAIN_FORUM_VIEW'	=> 'مەکۆ ببینە',
	'MCP_MAIN_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_MAIN_POST_DETAILS'	=> 'وردەکارییەکانی پەیام',
	'MCP_MAIN_TOPIC_VIEW'	=> 'بابەت ببینە',
	'MCP_MAKE_ANNOUNCEMENT'	=> 'بیگۆڕە بۆ "ئاگاداری"',
	'MCP_MAKE_ANNOUNCEMENT_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "ئاگاداری"؟',
	'MCP_MAKE_ANNOUNCEMENTS'	=> 'بیانگۆڕە بۆ "ئاگاداری"',
	'MCP_MAKE_ANNOUNCEMENTS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "ئاگاداری"؟',
	'MCP_MAKE_GLOBAL'	=> 'بیگۆڕە بۆ "ئاگاداری گشتی"',
	'MCP_MAKE_GLOBAL_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "ئاگاداری گشتی"؟',
	'MCP_MAKE_GLOBALS'	=> 'بیانگۆڕە بۆ "ئاگاداری گشتی"',
	'MCP_MAKE_GLOBALS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "ئاگاداری گشتی"؟',
	'MCP_MAKE_STICKY'	=> 'بیگۆڕە بۆ "جێگیر"',
	'MCP_MAKE_STICKY_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "جێگیر"؟',
	'MCP_MAKE_STICKIES'	=> 'بیانگۆڕە بۆ "جێگیر"',
	'MCP_MAKE_STICKIES_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "جێگیر"؟',
	'MCP_MAKE_NORMAL'	=> 'بیگۆڕە بۆ "بابەتی ئاسایی"',
	'MCP_MAKE_NORMAL_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "بابەتی ئاسایی"؟',
	'MCP_MAKE_NORMALS'	=> 'بیانگۆڕە بۆ "بابەتی ئاسایی"',
	'MCP_MAKE_NORMALS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "بابەتی ئاسایی"؟',
	'MCP_NOTES'	=> 'سەرنجەکانی بەکارهێنەر',
	'MCP_NOTES_FRONT'	=> 'پەرەی سەرەتا',
	'MCP_NOTES_USER'	=> 'وردەکارییەکانی بەکارهێنەر',
	'MCP_POST_REPORTS'	=> 'ڕاپۆرتە هاتووەکانی ئەم پەیامە',
	'MCP_PM_REPORTS'				=> 'پەیامە تایبەتە ڕاپۆرتکراوەکان',
	'MCP_PM_REPORT_DETAILS'			=> 'وردەکارییەکانی ڕاپۆرتکردنی پەیامی تایبەت',
	'MCP_PM_REPORTS_CLOSED'			=> 'ڕاپۆرتە داخراوەکانی پەیامی تایبەت',
	'MCP_PM_REPORTS_CLOSED_EXPLAIN'	=> 'ئەمە لیستێکی پەیامە تایبەتییە ڕاپۆرتکراوەکانە کە بەم نزیکانە چارەسەر کراون.',
	'MCP_PM_REPORTS_OPEN'			=> 'ڕاپۆرتە کراوەکانی پەیامی تایبەت',
	'MCP_PM_REPORTS_OPEN_EXPLAIN'	=> 'ئەمە لیستێکی پەیامە تایبەتییە ڕاپۆرتکراوەکانە کە هێشتا چارەسەر نەکراون.',

	'MCP_REPORTS'					=> 'پەیامە ڕاپۆرتکراوکان',
	'MCP_REPORT_DETAILS'	=> 'وردەکارییەکان ڕاپۆرت بکە',
	'MCP_REPORTS_CLOSED'	=> 'ڕاپۆرتە داخراوەکان',
	'MCP_REPORTS_CLOSED_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامە ڕاپۆرتکراوانەن کە بەم دواییە چارەسەرکراون.',
	'MCP_REPORTS_OPEN'	=> 'ڕاپۆرتە کراوەکان',
	'MCP_REPORTS_OPEN_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامە ڕاپۆرتکراوانەن کە تا ئێستا پێویستە چاویان لێ بکرێت.',
	'MCP_QUEUE'	=> 'نۆرەی چاودێری',
	'MCP_QUEUE_APPROVE_DETAILS'	=> 'وردەکارییەکان پەسەند بکە',
	'MCP_QUEUE_UNAPPROVED_POSTS'	=> 'ئەو پەیامانەی چاوەڕێی پەسەندکردنن',
	'MCP_QUEUE_UNAPPROVED_POSTS_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامانەن کە پێویستە پەسەند بکرێن پێش ئەوەی پیشان بدرێن بۆ ئەندامان.',
	'MCP_QUEUE_UNAPPROVED_TOPICS'	=> 'ئەو بابەتانەی چاوەڕێی پەسەندکردنن',
	'MCP_QUEUE_UNAPPROVED_TOPICS_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو بابەتانەن کە پێویستە پەسەند بکرێن پێش ئەوەی پیشان بدرێن بۆ ئەندامان.',
	'MCP_VIEW_USER'	=> 'ئامارەکانی بەکارهێنەرێکی دیاریکراو ببینە',
	'MCP_WARN'	=> 'ئاگادارییەکان',
	'MCP_WARN_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_WARN_LIST'	=> 'ئاگادارییەکان لیست بکە',
	'MCP_WARN_POST'	=> 'ئاگاداری بکەوە بۆ بابەتێکی دیاریکراو',
	'MCP_WARN_USER'	=> 'بەکارهێنەر ئاگادار بکەوە',
	'MERGE_POSTS'	=> 'پەیامەکان پێکەوە بلکێنە',
	'MERGE_POSTS_CONFIRM'	=> 'دڵنیایت لە لکاندنی پەیامە دیاریکراوەکان پێکەوە؟',
	'MERGE_TOPIC_EXPLAIN'	=> 'ئەم فۆڕمەی خوارەوە بەکار ببە ئەتوانیت پەیامە دیاریکراوەکان بلکێنیت بە بابەتێکی ترەوە. ئەم پەیامانە ڕیز ناکرێنەوە وەک ئەوە دەردەکەون کە بەکارهێنەران لە بنەڕەتەوە ئەو پەیامانەیان بۆ ئەو بابەتە نووسیبێت.<br />تکایە ID ـی بابەتی مەبەست بنووسە یان کرتە لە "دیاریکردنی بابەت" بکە بۆ گەڕان بۆ یەکێک.',
	'MERGE_TOPIC_ID'	=> 'ژمارەی ناسنامەی بابەتی مەبەست',
	'MERGE_TOPICS'	=> 'بابەتەکان پێکەوە بلکێنە',
	'MERGE_TOPICS_CONFIRM'	=> 'دڵنیایت لە لکاندنی بابەتە دیاریکراوەکان پێکەوە؟',
	'MODERATE_FORUM'	=> 'چاودێری مەکۆ بکە',
	'MODERATE_TOPIC'	=> 'چاودێری بابەت بکە',
	'MODERATE_POST'	=> 'چاودێری پەیام بکە',
	'MOD_OPTIONS'	=> 'هەڵبژاردنەکانی چاودێر',
	'MORE_INFO'	=> 'زانیاریی زیاتر',
	'MOST_WARNINGS'	=> 'بەکارهێنەرە زۆر ئاگادار کراوەکان',
	'MOVE_TOPIC_CONFIRM'	=> 'دڵنیایت لە گواستنەوەی بابەت بۆ مەکۆیەکی نوێ؟',
	'MOVE_TOPICS'	=> 'بابەتە دیاریکراوکان بگوازەوە',
	'MOVE_TOPICS_CONFIRM'	=> 'دڵنیایت لە گواستنەوەی بابەتە دیاریکراوەکان بۆ مەکۆیەکی نوێ؟',
	'NOTIFY_POSTER_APPROVAL'	=> 'نووسەر لە بارەی پەسەندکردنەوە ئاگادار بکرێتەوە؟',
	'NOTIFY_POSTER_DISAPPROVAL'	=> 'نووسەر لە بارەی پەسەند نەکردنەوە ئاگادار بکرێتەوە؟',
	'NOTIFY_USER_WARN'	=> 'بەکارهێنەر ئاگادار بکرێتەوە لە ئاگاداری؟',
	'NOT_MODERATOR'	=> 'تۆ چاودێری ئەم مەکۆیە نیت.',
	'NO_DESTINATION_FORUM'	=> 'تکایە مەکۆیەک دیاری بکە بۆ مەبەست',
	'NO_DESTINATION_FORUM_FOUND'	=> 'هیچ مەکۆیەکی مەبەست دیاری نەکراوە.',
	'NO_ENTRIES'	=> 'هیچ لۆگێک نییە بۆ ئەم ماوەیە.',
	'NO_FEEDBACK'	=> 'هیچ لێدوانێک نییە لەم بەکارهێنەرەوە.',
	'NO_FINAL_TOPIC_SELECTED'	=> 'پێویستە بابەتی مەبەست دیاری بکەیت بۆ لکاندنی پەیامەکان.',
	'NO_MATCHES_FOUND'	=> 'هیچ ئەنجامێک نەدۆزرایەوە',
	'NO_POST'	=> 'پێویستە پەیامێک دیاری بکەیت بۆ ئاگادار کردنەوەی بەکارهێنەر لەو پەیامە.',
	'NO_POST_REPORT'	=> 'ئەم پەیامە ڕاپۆرتی لەسەر نەنووسراوە.',
	'NO_POST_SELECTED'	=> 'پێویستە لانی کەم پەیامێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_REASON_DISAPPROVAL'	=> 'تکایە هۆکارێکی گونجاو بنووسە بۆ پەسەند نەکردن.',
	'NO_REPORT'	=> 'هیچ ڕاپۆرتێک نەدۆزرایەوە',
	'NO_REPORTS'	=> 'هیچ ڕاپۆرتێک نەدۆزرایەوە',
	'NO_REPORT_SELECTED'	=> 'پێویستە لانی کەم ڕاپۆرتێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_TOPIC_ICON'	=> 'هیچ',
	'NO_TOPIC_SELECTED'	=> 'پێویستە لانی کەم بابەتێکێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_TOPICS_QUEUE'	=> 'هیچ بابەتێک چاوەڕوانی پەسەندکردن نییە',
	'ONLY_TOPIC'	=> 'تەنها بابەتی "%s"',
	'OTHER_USERS'	=> 'بەکارهێنەرانی تر کە لەم IP ـیەوە پەیامیان نووسیوە',
	'PM_REPORT_CLOSED_SUCCESS'	=> 'پەیامە تایبەتە ڕاپۆرتکراوە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'PM_REPORT_DELETED_SUCCESS'	=> 'پەیامە تایبەتە ڕاپۆرتکراوە دیاریکراوەکان بە سەرکەوتوویی سڕدرانەوە.',
	'PM_REPORTED_SUCCESS'		=> 'ئەم پەیامە تایبەتە بە سەرکەوتوویی ڕاپۆرت کرا.',
	'PM_REPORT_TOTAL'			=> 'کۆی گشتی <strong>١</strong> پەیامی تایبەت ڕاپۆرتکراوە بۆ پیاداچوونەوە.',
	'PM_REPORTS_CLOSED_SUCCESS'	=> 'The selected PM reports have been closed successfully.',
	'PM_REPORTS_DELETED_SUCCESS'=> 'The selected PM reports have been deleted successfully.',
	'PM_REPORTS_TOTAL'			=> 'کۆی گشتی <strong>%d</strong> پەیامی تایبەت ڕاپۆرتکراون بۆ پیاداچوونەوە.',
	'PM_REPORTS_ZERO_TOTAL'		=> 'هیچ پەیامێکی تایبەت ڕاپۆرت نەکراوە بۆ پیاداچوونەوە.',
	'PM_REPORT_DETAILS'			=> 'وردەکارییەکانی ڕاپۆرتی پەیامی تایبەت',
	'POSTER'	=> 'نووسەر',
	'POSTS_APPROVED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پەسەندکران.',
	'POSTS_DELETED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی لە بنکەدراوە سڕدرانەوە.',
	'POSTS_DISAPPROVED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پەسەند نەکران.',
	'POSTS_LOCKED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'POSTS_MERGED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پێکەوە لکێندران.',
	'POSTS_UNLOCKED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی کرانەوە.',
	'POSTS_PER_PAGE'	=> 'پەیامەکان بۆ هەر پەڕەیەک',
	'POSTS_PER_PAGE_EXPLAIN'	=> '(0 بنووسە بۆ بینینی هەموو پەیامەکان.)',
	'POST_APPROVED_SUCCESS'	=> 'پەیامی دیاریکراو پەسەند کرا.',
	'POST_DELETED_SUCCESS'	=> 'پەیامی دیاریکراو بە سەرکەوتوویی لە بنکەدراوە سڕدرایەوە.',
	'POST_DISAPPROVED_SUCCESS'	=> 'پەیامی دیاریکراو پەسەند نەکرا.',
	'POST_LOCKED_SUCCESS'	=> 'پەیام بە سەرکەوتوویی داخرا.',
	'POST_NOT_EXIST'	=> 'ئەو پەیامەی داوات کردووە بوونی نییە.',
	'POST_REPORTED_SUCCESS'	=> 'ئەم پەیامە بە سەرکەوتوویی ڕاپۆرت کرا.',
	'POST_UNLOCKED_SUCCESS'	=> 'پەیام بە سەرکەوتوویی کرایەوە.',
	'READ_USERNOTES'	=> 'سەرنجەکانی بەکارهێنەر',
	'READ_WARNINGS'	=> 'ئاگادارییەکانی بەکارهێنەر',
	'REPORTER'	=> 'ڕاپۆرتنووس',
	'REPORTED'	=> 'ڕاپۆرتکراوە لە',
	'REPORTED_BY'	=> 'ڕاپۆرتکراوە لەلایەن',
	'REPORTED_ON_DATE'	=> 'لە',
	'REPORTS_CLOSED_SUCCESS'	=> 'ڕاپۆرتە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'REPORTS_DELETED_SUCCESS'	=> 'ڕاپۆرتە دیاریکراوەکان بە سەرکەوتوویی سڕدرانەوە.',
	'REPORTS_TOTAL'	=> 'کۆی گشتی <strong>%d</strong> ڕاپۆرت هەیە بۆ پیاچوونەوە.',
	'REPORTS_ZERO_TOTAL'	=> 'هیچ ڕاپۆرتێک نییە بۆ پیاچوونەوە.',
	'REPORT_CLOSED'	=> 'ئەم ڕاپۆرتە پێشتر داخراوە.',
	'REPORT_CLOSED_SUCCESS'	=> 'ڕاپۆرتی دیاریکراو بە سەرکەوتوویی داخرا.',
	'REPORT_DELETED_SUCCESS'	=> 'ڕاپۆرتی دیاریکراو بە سەرکەوتوویی سڕدرایەوە.',
	'REPORT_DETAILS'	=> 'وردەکارییەکان ڕاپۆرت بکە',
	'REPORT_MESSAGE'	=> 'ئەم پەیامە ڕاپۆرت بکە',
	'REPORT_MESSAGE_EXPLAIN'	=> 'ئەم فۆڕمە بەکار ببە بۆ ڕاپۆرتکردنی پەیامی تایبەتی دیاریکراو. ڕاپۆرتکردن تەنها لە کاتێکدا پێویستە کە پەیامەکە یاساکانی مەکۆی شکاندبێت. <strong>ڕاپۆرتکردنی پەیامێکی تایبەت وا دەکات کە ناوەڕۆکەکەی ئاشکرا بێت بۆ هەموو چاودێران.</strong>',
	'REPORT_NOTIFY'	=> 'ئاگادارم بکەوە',
	'REPORT_NOTIFY_EXPLAIN'	=> 'ئاگادارت ئەکاتەوە کاتێک ڕاپۆرتەکەت لێکۆڵینەوەی لەسەر کرا.',
	'REPORT_POST_EXPLAIN'	=> 'ئەم فۆڕمە بەکار ببە بۆ ڕاپۆرتکردنی پەیامی دیاریکراو بۆ چاودێران و بەڕێوەبەرانی مەکۆ. ڕاپۆرتکردن تەنها لە کاتێکدا پێویستە کە پەیامەکە یاساکانی مەکۆی شکاندبێت. ',
	'REPORT_REASON'	=> 'هۆکاری ڕاپۆرت',
	'REPORT_TIME'	=> 'کاتی ڕاپۆرت',
	'REPORT_TOTAL'	=> 'کۆی گشتی <strong>1</strong> ڕاپۆرت هەیە بۆ پیاچوونەوە.',
	'RESYNC'	=> 'Resync',
	'RETURN_MESSAGE'	=> '%sبگەڕێوە بۆ پەیامەکە%s',
	'RETURN_NEW_FORUM'	=> '%sبڕۆ بۆ مەکۆکە%s',
	'RETURN_NEW_TOPIC'	=> '%sبڕۆ بۆ بابەتە نوێیەکە%s',
	'RETURN_PM'		=> '%sبگەڕێوە بۆ پەیامە تایبەتییەکان%s',
	'RETURN_POST'	=> '%sبگەڕێوە بۆ پەیامەکە%s',
	'RETURN_QUEUE'	=> '%sبگەڕێوە بۆ نۆرەکە%s',
	'RETURN_REPORTS'	=> '%sبگەڕێوە بۆ راپۆرتەکان%s',
	'RETURN_TOPIC_SIMPLE'	=> '%sبگەڕێوە بۆ بابەتەکە%s',
	'SEARCH_POSTS_BY_USER'	=> 'لە پەیامەکان بگەڕێ بە',
	'SELECT_ACTION'	=> 'چالاکی ویستراو دیاری بکە',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENT'	=> 'تکایە ئەو مەکۆیە دیاری بکە کە ئەتەوێت ئەم ئاگادارییە گشتییەی لێ پیشان بدرێت.',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENTS'	=> 'یەکێک یان زیاتر لە بابەتە گشتییەکان ئاگاداری گشتییە. تکایە ئەو مەکۆیە دیاری بکە کە ئەتەوێت ئەمانەی لێ دەربکەوێت.',
	'SELECT_MERGE'	=> 'دیاری بکە بۆ لکاندن',
	'SELECT_TOPICS_FROM'	=> 'بابەتەکان دیاری بکە',
	'SELECT_TOPIC'	=> 'بابەت دیاری بکە',
	'SELECT_USER'	=> 'بەکارهێنەر دیاری بکە',
	'SORT_ACTION'	=> 'چالاکی لۆگ',
	'SORT_DATE'	=> 'ڕێکەوت',
	'SORT_IP'	=> 'ناونیشانی IP',
	'SORT_WARNINGS'	=> 'ئاگادارییەکان',
	'SPLIT_AFTER'	=> 'بابەت بەش بکە لە پەیامی دیاریکراوەوە تا دوایی',
	'SPLIT_FORUM'	=> 'مەکۆ بۆ بابەتی نوێ',
	'SPLIT_POSTS'	=> 'پەیامە دیاریکراوکان بەش بکە',
	'SPLIT_SUBJECT'	=> 'ناونیشانی بابەتی نوێ',
	'SPLIT_TOPIC_ALL'	=> 'بابەت بەش بکە لە پەیامە دیاریکراوەکانەوە',
	'SPLIT_TOPIC_ALL_CONFIRM'	=> 'دڵنیایت لە بەشکردنی ئەم بابەتە؟',
	'SPLIT_TOPIC_BEYOND'	=> 'بابەت بەش بکە لەسەر بابەتی دیاریکراوەوە',
	'SPLIT_TOPIC_BEYOND_CONFIRM'	=> 'دڵنیایت لە بەشکردنی ئەم بابەتە لەسەر پەیامی دیاریکراوەوە؟',
	'SPLIT_TOPIC_EXPLAIN'	=> 'بە بەکارهێنانی ئەم فۆڕمەی خوارەوە ئەتوانیت بابەتێک بەش بکەیت بۆ دوان، یان بە دیاریکردنی پەیامەکان تاک تاک یان بە بەشکردن لە پەیامێکی دیاریکراوەوە.',
	'THIS_PM_IP'				=> 'IP for this private message',
	'THIS_POST_IP'	=> 'IP بۆ ئەم پەیامە',
	'TOPICS_APPROVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان پەسەندکران.',
	'TOPICS_DELETED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی لە بنکەدراوە سڕدرانەوە.',
	'TOPICS_DISAPPROVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان پەسەند نەکران.',
	'TOPICS_FORKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی ڕوونووسکران.',
	'TOPICS_LOCKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان داخران.',
	'TOPICS_MOVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی گواسترانەوە.',
	'TOPICS_RESYNC_SUCCESS'	=> 'The selected topics have been resynchronised.',
	'TOPICS_TYPE_CHANGED'	=> 'جۆرەکانی بابەت بە سەرکەوتوویی گۆڕدرا.',
	'TOPICS_UNLOCKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان کرانەوە.',
	'TOPIC_APPROVED_SUCCESS'	=> 'بابەتی دیاریکراو پەسەندکرا.',
	'TOPIC_DELETED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی لە بنکەدراوە سڕدرایەوە.',
	'TOPIC_DISAPPROVED_SUCCESS'	=> 'بابەتی دیاریکراو پەسەند نەکرا.',
	'TOPIC_FORKED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی ڕوونووسکرا.',
	'TOPIC_LOCKED_SUCCESS'	=> 'بابەتی دیاریکراو داخرا.',
	'TOPIC_MOVED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی گواسترایەوە.',
	'TOPIC_NOT_EXIST'	=> 'ئەو بابەتەی دیاریت کردووە بوونی نییە.',
	'TOPIC_RESYNC_SUCCESS'	=> 'The selected topic has been resynchronised.',
	'TOPIC_SPLIT_SUCCESS'	=> 'بابەتی دیاریکرا بە سەرکەوتوویی بەشکرا.',
	'TOPIC_TIME'	=> 'کاتی بابەت',
	'TOPIC_TYPE_CHANGED'	=> 'جۆری بابەت بە سەرکەوتوویی گۆڕدرا.',
	'TOPIC_UNLOCKED_SUCCESS'	=> 'بابەتی دیاریکراو کرایەوە.',
	'TOTAL_WARNINGS'	=> 'سەرجەم ئاگادارییەکان',
	'UNAPPROVED_POSTS_TOTAL'	=> 'کۆی گشتی <strong>%d</strong> پەیام چاوەڕوانی پەسەندکردنن.',
	'UNAPPROVED_POSTS_ZERO_TOTAL'	=> 'هیچ پەیامێک چاوەڕوانی پەسەندکردن نییە',
	'UNAPPROVED_POST_TOTAL'	=> 'کۆی گشتی <strong>1</strong> پەیام چاوەڕوانی پەسەندکردنن.',
	'UNLOCK'	=> 'کردنەوە',
	'UNLOCK_POST'	=> 'کردنەوەی پەیام',
	'UNLOCK_POST_EXPLAIN'	=> 'ڕێدان بە دەستکاریکردن',
	'UNLOCK_POST_POST'	=> 'پەیام بکەرەوە',
	'UNLOCK_POST_POST_CONFIRM'	=> 'دڵنیایت لە ڕێدان بە دەستکاریکردنی ئەم پەیامە؟',
	'UNLOCK_POST_POSTS'	=> 'پەیامە دیاریکراوەکان بکەرەوە',
	'UNLOCK_POST_POSTS_CONFIRM'	=> 'دڵنیایت لە ڕێدان بە دەستکاریکردنی پەیامە دیاریکراوەکان؟',
	'UNLOCK_TOPIC'	=> 'بابەت بکەرەوە',
	'UNLOCK_TOPIC_CONFIRM'	=> 'دڵنیایت لە کردنەوەی ئەم بابەتە؟',
	'UNLOCK_TOPICS'	=> 'بابەتە دیاریکراوەکان بکەرەوە',
	'UNLOCK_TOPICS_CONFIRM'	=> 'دڵنیایت لە کردنەوەی هەموو بابەتە دیاریکراوەکان؟',
	'USER_CANNOT_POST'	=> 'ناتوانیت لەم مەکۆیە پەیام بنووسیت.',
	'USER_CANNOT_REPORT'	=> 'ناتوانیت لەم مەکۆیە پەیام ڕاپۆرت بکەیت.',
	'USER_FEEDBACK_ADDED'	=> 'لێدوانی بەکارهێنەر بە سەرکەوتوویی زیادکرا.',
	'USER_WARNING_ADDED'	=> 'بەکارهێنەر بە سەرکەوتوویی ئاگادارکرایەوە.',
	'VIEW_DETAILS'	=> 'بینینی وردەکارییەکان',
	'VIEW_PM'	=> 'پەیامی تایبەت ببینە',
	'VIEW_POST'	=> 'بینینی پەیام',
	'WARNED_USERS'	=> 'بەکارهێنەرە ئاگادارکراوەکان',
	'WARNED_USERS_EXPLAIN'	=> 'ئەمە لیستی ئەو بەکارهێنەرانەیە کە ئاگاداریی بەسەرنەچوویان بۆ هاتووە.',
	'WARNING_PM_BODY'	=> 'ئەمەی خوارەوە ئاگادارییەکە کە بۆت هاتووە لەلایەن بەڕێوەبەر یان چاودێرێکەوە لە ماڵپەڕ.quote]%s[/quote]',
	'WARNING_PM_SUBJECT'	=> 'ئاگاداری مەکۆ هات',
	'WARNING_POST_DEFAULT'	=> 'ئەمە ئاگادارییەکە پەیوەست بەم پەیامەی خوارەوە کە تۆ نووسیوتە: %s.',
	'WARNINGS_ZERO_TOTAL'	=> 'هیچ ئاگادارییەک بوونی نییە.',
	'YOU_SELECTED_TOPIC'	=> 'تۆ دیاریت کرد بابەتی ژمارە %d: %s',

	'report_reasons'	=> array(

		'TITLE'	=> array(
			'WAREZ'	=> 'وارێز',
			'SPAM'	=> 'سپام',
			'OFF_TOPIC'	=> 'دەرچوون لە بابەت',
			'OTHER'	=> 'هیتر',
		),


		'DESCRIPTION'	=> array(
			'WAREZ'	=> 'پەیام بەستەری تیادایە بۆ پڕۆگرامی قاچاخ و نایاسایی.',
			'SPAM'	=> 'پەیامی ڕاپۆرتکراو مەبەست لە نووسینی تەنها پڕوپاگەندەیە بۆ ماڵپەڕ یان بەرهەمێک.',
			'OFF_TOPIC'	=> 'پەیامی ڕاپۆرتکراو لە بابەت دەرچووە.',
			'OTHER'	=> 'پەیامی ڕاپۆرتکراو لەگەڵ هیچ کام لەوانەی سەرەوە ناگونجێت، تکایە لەو خانەیەی خوارەوە بینووسە.',
		),

	),

));

?>
