<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACTION'	=> 'چالاکی',
	'ACTION_NOTE'	=> 'چالاکی/ تێبینی',
	'ADD_FEEDBACK'	=> 'لێدوانمان بۆ بدە',
	'ADD_FEEDBACK_EXPLAIN'	=> 'ئەگەر خوازیاریت بەزیادکردنی ڕاپۆرتێک تکایە ئەم فۆڕمەی خوارەوە پڕبکەوە تەنها دەقی تەخت بەکارببە، HTML، BBCode، ڕێ پێ نەدراوە.',
	'ADD_WARNING'	=> 'ئاگاداری زیاد بکە',
	'ADD_WARNING_EXPLAIN'	=> 'بۆ ئاگادار کردنەوەی ئەم بەکارهێنەرە تکایە ئەم فۆڕمەی خوارەوە پڕ بکەوە تەنها دەقی تەخت بەکار ببە؛ HTML، BBCode، ڕێ پێ نەدراوە.',
	'ALL_ENTRIES'	=> 'هەموو دانەکان',
	'ALL_NOTES_DELETED'	=> 'هەموو سەرنجەکانی بەکارهێنەر بە سەرکەوتوویی لابران.',
	'ALL_REPORTS'	=> 'هەموو ڕاپۆرتەکان',
	'ALREADY_REPORTED'	=> 'ئەم پەیامە پێشتر ڕاپۆرتکراوە.',
	'ALREADY_REPORTED_PM'	=> 'ئەم پەیامە تایبەتە پێشتر ڕاپۆرتکراوە.',
	'ALREADY_WARNED'	=> 'پێشتر ئاگادارییەک هاتووە بۆ ئەم پەیامە',
	'APPROVE'	=> 'پەسەندکردن',
	'APPROVE_POST'	=> 'پەیام پەسەند بکە',
	'APPROVE_POST_CONFIRM'	=> 'دڵنیایت لە پەسەند کردنی ئەم پەیامە؟',
	'APPROVE_POSTS'	=> 'پەیامەکان پەسەند بکە',
	'APPROVE_POSTS_CONFIRM'	=> 'دڵنیایت لە پەسەند کردنی پەیامە دیاریکراوەکان؟',
	'CANNOT_MOVE_SAME_FORUM'	=> 'ناتوانیت بابەتێک بگوازییتەوە بۆ مەکۆیەک کە خۆی لەوێدایە.',
	'CANNOT_WARN_ANONYMOUS'	=> 'ناتوانیت بەکارهێنەرە میوانە خۆ تۆمار نەکردووەکان ئاگادار بکەیتەوە.',
	'CANNOT_WARN_SELF'	=> 'ناتوانی خۆت ئاگادار بکەیتەوە',
	'CAN_LEAVE_BLANK'	=> 'ئەمە ئەتوانرێت بە بەتاڵی جێبهێڵدرێت.',
	'CHANGE_POSTER'	=> 'نووسەر بگۆڕە',
	'CLOSE_PM_REPORT'		=> 'ڕاپۆرتی پەیامی تایبەت دابخە',
	'CLOSE_PM_REPORT_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتی پەیامی تایبەتی دیاریکراو؟',
	'CLOSE_PM_REPORTS'		=> 'ڕاپۆرتەکانی پەیامی تایبەت دابخە',
	'CLOSE_PM_REPORTS_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتی پەیامە تایبەتییە دیاریکراوەکان؟',
	'CLOSE_REPORT'	=> 'ڕاپۆرت دابخە',
	'CLOSE_REPORT_CONFIRM'	=> 'دڵنیات لە داخستنی ئەم ڕاپۆرتە دیاریکراوە؟',
	'CLOSE_REPORTS'	=> 'ڕاپۆرتەکان دابخە',
	'CLOSE_REPORTS_CONFIRM'	=> 'دڵنیایت لە داخستنی ڕاپۆرتە دیاریکراوەکان؟',
	'DELETE_PM_REPORT'	=> 'ڕاپۆرتی پەیامی تایبەت دابخە',
	'DELETE_PM_REPORT_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی پەیامی تایبەتی دیاریکراو؟',
	'DELETE_PM_REPORTS'			=> 'ڕاپۆرتەکانی پەیامی تایبەت بسڕەوە',
	'DELETE_PM_REPORTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی پەیامە تایبەتییە دیاریکراوەکان؟',
	'DELETE_POSTS'	=> 'پەیامەکان بسڕەوە',
	'DELETE_POSTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم پەیامانە؟',
	'DELETE_POST_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم پەیامە؟',
	'DELETE_REPORT'	=> 'ڕاپۆرت بسڕەوە',
	'DELETE_REPORT_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتی دیاریکراو؟',
	'DELETE_REPORTS'	=> 'ڕاپۆرتەکان بسڕەوە',
	'DELETE_REPORTS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ڕاپۆرتە دیاریکراوەکان؟',
	'DELETE_SHADOW_TOPIC'	=> 'بابەتی سێبر بسڕەوە',
	'DELETE_TOPICS'	=> 'بابەتە دیاریکراوەکان بسڕەوە',
	'DELETE_TOPICS_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم بابەتانە؟',
	'DELETE_TOPIC_CONFIRM'	=> 'دڵنیایت لە سڕینەوەی ئەم بابەتە؟',
	'DISAPPROVE'	=> 'ناپەسەندکردن',
	'DISAPPROVE_REASON'	=> 'هۆکاری ناپەسەندکردن',
	'DISAPPROVE_POST'	=> 'پەیام ناپەسەند بکە',
	'DISAPPROVE_POST_CONFIRM'	=> 'دڵنیات لە پەسەند نەکردنی ئەم پەیامە؟',
	'DISAPPROVE_POSTS'	=> 'پەیامەکان پەسەند مەکە',
	'DISAPPROVE_POSTS_CONFIRM'	=> 'دڵنیایت لە پەسەند نەکردنی پەیامە دیاریکراوەکان؟',
	'DISPLAY_LOG'	=> 'پەیامەکان لە پێشووەوە پیشان بدە',
	'DISPLAY_OPTIONS'	=> 'هەڵبژاردنەکانی پیشاندان',
	'EMPTY_REPORT'	=> 'پێویستە پەسنێک بنووسیت لە کاتی دیاریکردنی ئەم هۆکارە.',
	'EMPTY_TOPICS_REMOVED_WARNING'	=> 'تکایە سەرنجی ئەوە بدە کە یەکێک یان چەند بابەتێک لە بنکەدراوەکەمان لابراوە لەبەر ئەوە بەتاڵ بوون.',
	'FEEDBACK'	=> 'Feedback',
	'FORK'	=> 'ڕوونووس',
	'FORK_TOPIC'	=> 'بابەت ڕوونووس بکە',
	'FORK_TOPIC_CONFIRM'	=> 'دڵنیات لە ڕوونووسکردنی ئەم پەیامە؟',
	'FORK_TOPICS'	=> 'پەیامە دیاریکراوەکان ڕوونووس بکە',
	'FORK_TOPICS_CONFIRM'	=> 'دڵنیایت لە ڕوونووسکردنی پەیامە دیاریکراوەکان؟',
	'FORUM_DESC'	=> 'پەسن',
	'FORUM_NAME'	=> 'ناوی مەکۆ',
	'FORUM_NOT_EXIST'	=> 'ئەو مەکۆیەی دیاریت کردووە بوونی نییە',
	'FORUM_NOT_POSTABLE'	=> 'ناتوانرێت ئەو مەکۆیەی دیاریت کردووە پەیامی بۆ بنێردرێت.',
	'FORUM_STATUS'	=> 'دۆخی مەکۆ',
	'FORUM_STYLE'	=> 'ڕووخساری مەکۆ',
	'GLOBAL_ANNOUNCEMENT'	=> 'ئاگاداری گشتیی',
	'IP_INFO'	=> 'زانیاریی ناونیشانی IP',
	'IPS_POSTED_FROM'	=> 'ئەو ناونیشانی IP ـیانەی ئەم بەکارهێنەرە پەیامی لێیەوە ناردووە',
	'LATEST_LOGS'	=> 'دوا ٥ چالاکی چوونە ژوورەوە',
	'LATEST_REPORTED'	=> 'دوا ٥ ڕاپۆرتەکان',
	'LATEST_REPORTED_PMS'		=> 'دوا ٥ ڕاپۆرتی پەیامی تایبەت',
	'LATEST_UNAPPROVED'	=> 'دوا ٥ پەیام کە چاوەڕوانی پەسەندکردنن',
	'LATEST_WARNING_TIME'	=> 'دوا ئاگادارییەکان',
	'LATEST_WARNINGS'	=> 'دوا ٥ ئاگادارییەکان',
	'LEAVE_SHADOW'	=> 'بابەتی سێبەراوی لە جێی خۆیدا بهێڵەوە',
	'LIST_REPORT'	=> '1 ڕاپۆرت',
	'LIST_REPORTS'	=> '%d ڕاپۆرت',
	'LOCK'	=> 'داخستن',
	'LOCK_POST_POST'	=> 'داخستنی پەیام',
	'LOCK_POST_POST_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی ئەم پەیامە لە دەستکاریکردن؟',
	'LOCK_POST_POSTS'	=> 'پەیامە دیاریکراوەکان دابخە',
	'LOCK_POST_POSTS_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی پەیامە دیاریکراوەکان لە دەستکاریکردن؟',
	'LOCK_TOPIC_CONFIRM'	=> 'دڵنیایت لە داخستنی ئەم بابەتە؟',
	'LOCK_TOPICS'	=> 'بابەتە دیاریکراوەکان دابخە',
	'LOCK_TOPICS_CONFIRM'	=> 'دڵنیایت لە قەدەغەکردنی هەموو بابەتە دیاریکراوەکان؟',
	'LOGS_CURRENT_TOPIC'	=> 'هەنووکە لۆگەکانی ئەمە دەبینیت:',
	'LOGIN_EXPLAIN_MCP'	=> 'بۆ چاودێریکردنی ئەم مەکۆیە پێویستە بچیتە ژوورەوە.',
	'LOGVIEW_VIEWTOPIC'	=> 'بینینی بابەت',
	'LOGVIEW_VIEWLOGS'	=> 'لۆگی بابەت ببینە',
	'LOGVIEW_VIEWFORUM'	=> 'بینینی مەکۆ',
	'LOOKUP_ALL'	=> 'سەیری هەموو IP ـیەکان بکە',
	'LOOKUP_IP'	=> 'سەیری IP بکە',
	'MARKED_NOTES_DELETED'	=> 'بە سەرکەوتوویی هەموو سەرنجە نیشانەکراوەکانی بەکارهێنەر لابران.',
	'MCP_ADD'	=> 'ئاگادارییەک دابنێ',
	'MCP_BAN'	=> 'ڕاگرتن',
	'MCP_BAN_EMAILS'	=> 'ڕاگرتنی ئیمەیل',
	'MCP_BAN_IPS'	=> 'ڕاگرتنی IP',
	'MCP_BAN_USERNAMES'	=> 'ڕاگرتنی بەکارهێنەران',
	'MCP_LOGS'	=> 'لۆگەکانی چاودێر',
	'MCP_LOGS_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_LOGS_FORUM_VIEW'	=> 'لۆگەکانی مەکۆ',
	'MCP_LOGS_TOPIC_VIEW'	=> 'لۆگەکانی بابەت',
	'MCP_MAIN'	=> 'سەرەکی',
	'MCP_MAIN_FORUM_VIEW'	=> 'مەکۆ ببینە',
	'MCP_MAIN_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_MAIN_POST_DETAILS'	=> 'وردەکارییەکانی پەیام',
	'MCP_MAIN_TOPIC_VIEW'	=> 'بابەت ببینە',
	'MCP_MAKE_ANNOUNCEMENT'	=> 'بیگۆڕە بۆ "ئاگاداری"',
	'MCP_MAKE_ANNOUNCEMENT_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "ئاگاداری"؟',
	'MCP_MAKE_ANNOUNCEMENTS'	=> 'بیانگۆڕە بۆ "ئاگاداری"',
	'MCP_MAKE_ANNOUNCEMENTS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "ئاگاداری"؟',
	'MCP_MAKE_GLOBAL'	=> 'بیگۆڕە بۆ "ئاگاداری گشتی"',
	'MCP_MAKE_GLOBAL_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "ئاگاداری گشتی"؟',
	'MCP_MAKE_GLOBALS'	=> 'بیانگۆڕە بۆ "ئاگاداری گشتی"',
	'MCP_MAKE_GLOBALS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "ئاگاداری گشتی"؟',
	'MCP_MAKE_STICKY'	=> 'بیگۆڕە بۆ "جێگیر"',
	'MCP_MAKE_STICKY_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "جێگیر"؟',
	'MCP_MAKE_STICKIES'	=> 'بیانگۆڕە بۆ "جێگیر"',
	'MCP_MAKE_STICKIES_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "جێگیر"؟',
	'MCP_MAKE_NORMAL'	=> 'بیگۆڕە بۆ "بابەتی ئاسایی"',
	'MCP_MAKE_NORMAL_CONFIRM'	=> 'دڵنیایت لە گۆڕینی ئەم بابەتە بۆ "بابەتی ئاسایی"؟',
	'MCP_MAKE_NORMALS'	=> 'بیانگۆڕە بۆ "بابەتی ئاسایی"',
	'MCP_MAKE_NORMALS_CONFIRM'	=> 'دڵنیایت لە گۆڕینی بابەتە دیاریکراوەکان بۆ "بابەتی ئاسایی"؟',
	'MCP_NOTES'	=> 'سەرنجەکانی بەکارهێنەر',
	'MCP_NOTES_FRONT'	=> 'پەرەی سەرەتا',
	'MCP_NOTES_USER'	=> 'وردەکارییەکانی بەکارهێنەر',
	'MCP_POST_REPORTS'	=> 'ڕاپۆرتە هاتووەکانی ئەم پەیامە',
	'MCP_PM_REPORTS'				=> 'پەیامە تایبەتە ڕاپۆرتکراوەکان',
	'MCP_PM_REPORT_DETAILS'			=> 'وردەکارییەکانی ڕاپۆرتکردنی پەیامی تایبەت',
	'MCP_PM_REPORTS_CLOSED'			=> 'ڕاپۆرتە داخراوەکانی پەیامی تایبەت',
	'MCP_PM_REPORTS_CLOSED_EXPLAIN'	=> 'ئەمە لیستێکی پەیامە تایبەتییە ڕاپۆرتکراوەکانە کە بەم نزیکانە چارەسەر کراون.',
	'MCP_PM_REPORTS_OPEN'			=> 'ڕاپۆرتە کراوەکانی پەیامی تایبەت',
	'MCP_PM_REPORTS_OPEN_EXPLAIN'	=> 'ئەمە لیستێکی پەیامە تایبەتییە ڕاپۆرتکراوەکانە کە هێشتا چارەسەر نەکراون.',

	'MCP_REPORTS'					=> 'پەیامە ڕاپۆرتکراوکان',
	'MCP_REPORT_DETAILS'	=> 'وردەکارییەکان ڕاپۆرت بکە',
	'MCP_REPORTS_CLOSED'	=> 'ڕاپۆرتە داخراوەکان',
	'MCP_REPORTS_CLOSED_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامە ڕاپۆرتکراوانەن کە بەم دواییە چارەسەرکراون.',
	'MCP_REPORTS_OPEN'	=> 'ڕاپۆرتە کراوەکان',
	'MCP_REPORTS_OPEN_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامە ڕاپۆرتکراوانەن کە تا ئێستا پێویستە چاویان لێ بکرێت.',
	'MCP_QUEUE'	=> 'نۆرەی چاودێری',
	'MCP_QUEUE_APPROVE_DETAILS'	=> 'وردەکارییەکان پەسەند بکە',
	'MCP_QUEUE_UNAPPROVED_POSTS'	=> 'ئەو پەیامانەی چاوەڕێی پەسەندکردنن',
	'MCP_QUEUE_UNAPPROVED_POSTS_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو پەیامانەن کە پێویستە پەسەند بکرێن پێش ئەوەی پیشان بدرێن بۆ ئەندامان.',
	'MCP_QUEUE_UNAPPROVED_TOPICS'	=> 'ئەو بابەتانەی چاوەڕێی پەسەندکردنن',
	'MCP_QUEUE_UNAPPROVED_TOPICS_EXPLAIN'	=> 'ئەمە لیستێکی هەموو ئەو بابەتانەن کە پێویستە پەسەند بکرێن پێش ئەوەی پیشان بدرێن بۆ ئەندامان.',
	'MCP_VIEW_USER'	=> 'ئامارەکانی بەکارهێنەرێکی دیاریکراو ببینە',
	'MCP_WARN'	=> 'ئاگادارییەکان',
	'MCP_WARN_FRONT'	=> 'پەڕەی سەرەتا',
	'MCP_WARN_LIST'	=> 'ئاگادارییەکان لیست بکە',
	'MCP_WARN_POST'	=> 'ئاگاداری بکەوە بۆ بابەتێکی دیاریکراو',
	'MCP_WARN_USER'	=> 'بەکارهێنەر ئاگادار بکەوە',
	'MERGE_POSTS'	=> 'پەیامەکان بگوازەوە',
	'MERGE_POSTS_CONFIRM'	=> 'دڵنیایت لە گواستنەوەی پەیامە دیاریکراوەکان؟',
	'MERGE_TOPIC_EXPLAIN'	=> 'ئەم فۆڕمەی خوارەوە بەکارببە ئەتوانیت پەیامە دیاریکراوەکان بگوازیتەوە بۆناو بابەتێکی دیکە. ئەم پەیامانە ڕیز ناکرێنەوە وەک ئەوە دەردەکەون کە بەکارهێنەران لە بنەڕەتەوە ئەو پەیامانەیان بۆ ئەو بابەتە نووسیبێت.<br />تکایە ID ـی بابەتی مەبەست بنووسە یان کرتە لە "دیاریکردنی بابەت" بکە بۆ گەڕان بۆ یەکێک.',
	'MERGE_TOPIC_ID'	=> 'ژمارەی ناسنامەی بابەتی مەبەست',
	'MERGE_TOPICS'	=> 'بابەتەکان پێکەوە بلکێنە',
	'MERGE_TOPICS_CONFIRM'	=> 'دڵنیایت لە لکاندنی بابەتە دیاریکراوەکان پێکەوە؟',
	'MODERATE_FORUM'	=> 'چاودێری مەکۆ بکە',
	'MODERATE_TOPIC'	=> 'چاودێری بابەت بکە',
	'MODERATE_POST'	=> 'چاودێری پەیام بکە',
	'MOD_OPTIONS'	=> 'هەڵبژاردنەکانی چاودێر',
	'MORE_INFO'	=> 'زانیاریی زیاتر',
	'MOST_WARNINGS'	=> 'بەکارهێنەرە زۆر ئاگادار کراوەکان',
	'MOVE_TOPIC_CONFIRM'	=> 'دڵنیایت لە گواستنەوەی بابەت بۆ مەکۆیەکی نوێ؟',
	'MOVE_TOPICS'	=> 'بابەتە دیاریکراوکان بگوازەوە',
	'MOVE_TOPICS_CONFIRM'	=> 'دڵنیایت لە گواستنەوەی بابەتە دیاریکراوەکان بۆ مەکۆیەکی نوێ؟',
	'NOTIFY_POSTER_APPROVAL'	=> 'نووسەر لە بارەی پەسەندکردنەوە ئاگادار بکرێتەوە؟',
	'NOTIFY_POSTER_DISAPPROVAL'	=> 'نووسەر لە بارەی پەسەند نەکردنەوە ئاگادار بکرێتەوە؟',
	'NOTIFY_USER_WARN'	=> 'بەکارهێنەر ئاگادار بکرێتەوە لە ئاگاداری؟',
	'NOT_MODERATOR'	=> 'تۆ چاودێری ئەم مەکۆیە نیت.',
	'NO_DESTINATION_FORUM'	=> 'تکایە مەکۆیەک دیاری بکە بۆ مەبەست',
	'NO_DESTINATION_FORUM_FOUND'	=> 'هیچ مەکۆیەکی مەبەست دیاری نەکراوە.',
	'NO_ENTRIES'	=> 'هیچ لۆگێک نییە بۆ ئەم ماوەیە.',
	'NO_FEEDBACK'	=> 'هیچ لێدوانێک نییە لەم بەکارهێنەرەوە.',
	'NO_FINAL_TOPIC_SELECTED'	=> 'پێویستە بابەتی مەبەست دیاری بکەیت بۆ لکاندنی پەیامەکان.',
	'NO_MATCHES_FOUND'	=> 'هیچ ئەنجامێک نەدۆزرایەوە',
	'NO_POST'	=> 'پێویستە پەیامێک دیاری بکەیت بۆ ئاگادار کردنەوەی بەکارهێنەر لەو پەیامە.',
	'NO_POST_REPORT'	=> 'ئەم پەیامە ڕاپۆرتی لەسەر نەنووسراوە.',
	'NO_POST_SELECTED'	=> 'پێویستە لانی کەم پەیامێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_REASON_DISAPPROVAL'	=> 'تکایە هۆکارێکی گونجاو بنووسە بۆ پەسەند نەکردن.',
	'NO_REPORT'	=> 'هیچ ڕاپۆرتێک نەدۆزرایەوە',
	'NO_REPORTS'	=> 'هیچ ڕاپۆرتێک نەدۆزرایەوە',
	'NO_REPORT_SELECTED'	=> 'پێویستە لانی کەم ڕاپۆرتێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_TOPIC_ICON'	=> 'هیچ',
	'NO_TOPIC_SELECTED'	=> 'پێویستە لانی کەم بابەتێکێک دیاری بکەیت بۆ ئەنجامدانی ئەم کارە.',
	'NO_TOPICS_QUEUE'	=> 'هیچ بابەتێک چاوەڕوانی پەسەندکردن نییە',
	'ONLY_TOPIC'	=> 'تەنها بابەتی "%s"',
	'OTHER_USERS'	=> 'بەکارهێنەرانی تر کە لەم IP ـیەوە پەیامیان نووسیوە',
	'PM_REPORT_CLOSED_SUCCESS'	=> 'پەیامە تایبەتە ڕاپۆرتکراوە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'PM_REPORT_DELETED_SUCCESS'	=> 'پەیامە تایبەتە ڕاپۆرتکراوە دیاریکراوەکان بە سەرکەوتوویی سڕدرانەوە.',
	'PM_REPORTED_SUCCESS'		=> 'ئەم پەیامە تایبەتە بە سەرکەوتوویی ڕاپۆرت کرا.',
	'PM_REPORT_TOTAL'			=> 'کۆی گشتی <strong>١</strong> پەیامی تایبەت ڕاپۆرتکراوە بۆ پیاداچوونەوە.',
	'PM_REPORTS_CLOSED_SUCCESS'	=> 'ڕاپۆرتەکانی پەیامی تایبەتی دەستنیشانکراو بە سەرکەوتووی داخرا',
	'PM_REPORTS_DELETED_SUCCESS'=> 'ڕاپۆرتەکانی پەیامی تایبەتی دەستنیشانکراو بە سەرکەوتووی سڕایەوە',
	'PM_REPORTS_TOTAL'			=> 'کۆی گشتی <strong>%d</strong> پەیامی تایبەت ڕاپۆرتکراون بۆ پیاداچوونەوە.',
	'PM_REPORTS_ZERO_TOTAL'		=> 'هیچ پەیامێکی تایبەت ڕاپۆرت نەکراوە بۆ پیاداچوونەوە.',
	'PM_REPORT_DETAILS'			=> 'وردەکارییەکانی ڕاپۆرتی پەیامی تایبەت',
	'POSTER'	=> 'نووسەر',
	'POSTS_APPROVED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پەسەندکران.',
	'POSTS_DELETED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی لە بنکەدراوە سڕدرانەوە.',
	'POSTS_DISAPPROVED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پەسەند نەکران.',
	'POSTS_LOCKED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'POSTS_MERGED_SUCCESS'	=> 'پەیامە دیاریکراوەکان پێکەوە لکێندران.',
	'POSTS_UNLOCKED_SUCCESS'	=> 'پەیامە دیاریکراوەکان بە سەرکەوتوویی کرانەوە.',
	'POSTS_PER_PAGE'	=> 'پەیامەکان بۆ هەر پەڕەیەک',
	'POSTS_PER_PAGE_EXPLAIN'	=> '(0 بنووسە بۆ بینینی هەموو پەیامەکان.)',
	'POST_APPROVED_SUCCESS'	=> 'پەیامی دیاریکراو پەسەند کرا.',
	'POST_DELETED_SUCCESS'	=> 'پەیامی دیاریکراو بە سەرکەوتوویی لە بنکەدراوە سڕدرایەوە.',
	'POST_DISAPPROVED_SUCCESS'	=> 'پەیامی دیاریکراو پەسەند نەکرا.',
	'POST_LOCKED_SUCCESS'	=> 'پەیام بە سەرکەوتوویی داخرا.',
	'POST_NOT_EXIST'	=> 'ئەو پەیامەی داوات کردووە بوونی نییە.',
	'POST_REPORTED_SUCCESS'	=> 'ئەم پەیامە بە سەرکەوتوویی ڕاپۆرت کرا.',
	'POST_UNLOCKED_SUCCESS'	=> 'پەیام بە سەرکەوتوویی کرایەوە.',
	'READ_USERNOTES'	=> 'سەرنجەکانی بەکارهێنەر',
	'READ_WARNINGS'	=> 'ئاگادارییەکانی بەکارهێنەر',
	'REPORTER'	=> 'ڕاپۆرتنووس',
	'REPORTED'	=> 'ڕاپۆرتکراوە لە',
	'REPORTED_BY'	=> 'ڕاپۆرتکراوە لەلایەن',
	'REPORTED_ON_DATE'	=> 'لە',
	'REPORTS_CLOSED_SUCCESS'	=> 'ڕاپۆرتە دیاریکراوەکان بە سەرکەوتوویی داخران.',
	'REPORTS_DELETED_SUCCESS'	=> 'ڕاپۆرتە دیاریکراوەکان بە سەرکەوتوویی سڕدرانەوە.',
	'REPORTS_TOTAL'	=> 'کۆی گشتی <strong>%d</strong> ڕاپۆرت هەیە بۆ پیاچوونەوە.',
	'REPORTS_ZERO_TOTAL'	=> 'هیچ ڕاپۆرتێک نییە بۆ پیاچوونەوە.',
	'REPORT_CLOSED'	=> 'ئەم ڕاپۆرتە پێشتر داخراوە.',
	'REPORT_CLOSED_SUCCESS'	=> 'ڕاپۆرتی دیاریکراو بە سەرکەوتوویی داخرا.',
	'REPORT_DELETED_SUCCESS'	=> 'ڕاپۆرتی دیاریکراو بە سەرکەوتوویی سڕدرایەوە.',
	'REPORT_DETAILS'	=> 'وردەکارییەکان ڕاپۆرت بکە',
	'REPORT_MESSAGE'	=> 'ئەم پەیامە ڕاپۆرت بکە',
	'REPORT_MESSAGE_EXPLAIN'	=> 'ئەم فۆڕمە بەکار ببە بۆ ڕاپۆرتکردنی پەیامی تایبەتی دیاریکراو. ڕاپۆرتکردن تەنها لە کاتێکدا پێویستە کە پەیامەکە یاساکانی مەکۆی شکاندبێت. <strong>ڕاپۆرتکردنی پەیامێکی تایبەت وا دەکات کە ناوەڕۆکەکەی ئاشکرا بێت بۆ هەموو چاودێران.</strong>',
	'REPORT_NOTIFY'	=> 'ئاگادارم بکەوە',
	'REPORT_NOTIFY_EXPLAIN'	=> 'ئاگادارت ئەکاتەوە کاتێک ڕاپۆرتەکەت لێکۆڵینەوەی لەسەر کرا.',
	'REPORT_POST_EXPLAIN'	=> 'ئەم فۆڕمە بەکار ببە بۆ ڕاپۆرتکردنی پەیامی دیاریکراو بۆ چاودێران و بەڕێوەبەرانی مەکۆ. ڕاپۆرتکردن تەنها لە کاتێکدا پێویستە کە پەیامەکە یاساکانی مەکۆی شکاندبێت. ',
	'REPORT_REASON'	=> 'هۆکاری ڕاپۆرت',
	'REPORT_TIME'	=> 'کاتی ڕاپۆرت',
	'REPORT_TOTAL'	=> 'کۆی گشتی <strong>1</strong> ڕاپۆرت هەیە بۆ پیاچوونەوە.',
	'RESYNC'	=> 'Resync',
	'RETURN_MESSAGE'	=> '%sبگەڕێوە بۆ پەیامەکە%s',
	'RETURN_NEW_FORUM'	=> '%sبڕۆ بۆ مەکۆکە%s',
	'RETURN_NEW_TOPIC'	=> '%sبڕۆ بۆ بابەتە نوێیەکە%s',
	'RETURN_PM'		=> '%sبگەڕێوە بۆ پەیامە تایبەتییەکان%s',
	'RETURN_POST'	=> '%sبگەڕێوە بۆ پەیامەکە%s',
	'RETURN_QUEUE'	=> '%sبگەڕێوە بۆ نۆرەکە%s',
	'RETURN_REPORTS'	=> '%sبگەڕێوە بۆ راپۆرتەکان%s',
	'RETURN_TOPIC_SIMPLE'	=> '%sبگەڕێوە بۆ بابەتەکە%s',
	'SEARCH_POSTS_BY_USER'	=> 'لە پەیامەکان بگەڕێ بە',
	'SELECT_ACTION'	=> 'چالاکی ویستراو دیاری بکە',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENT'	=> 'تکایە ئەو مەکۆیە دیاری بکە کە ئەتەوێت ئەم ئاگادارییە گشتییەی لێ پیشان بدرێت.',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENTS'	=> 'یەکێک یان زیاتر لە بابەتە گشتییەکان ئاگاداری گشتییە. تکایە ئەو مەکۆیە دیاری بکە کە ئەتەوێت ئەمانەی لێ دەربکەوێت.',
	'SELECT_MERGE'	=> 'دیاری بکە بۆ لکاندن',
	'SELECT_TOPICS_FROM'	=> 'بابەتەکان دیاری بکە',
	'SELECT_TOPIC'	=> 'بابەت دیاری بکە',
	'SELECT_USER'	=> 'بەکارهێنەر دیاری بکە',
	'SORT_ACTION'	=> 'چالاکی لۆگ',
	'SORT_DATE'	=> 'ڕێکەوت',
	'SORT_IP'	=> 'ناونیشانی IP',
	'SORT_WARNINGS'	=> 'ئاگادارییەکان',
	'SPLIT_AFTER'	=> 'بابەت بەش بکە لە پەیامی دیاریکراوەوە تا دوایی',
	'SPLIT_FORUM'	=> 'مەکۆ بۆ بابەتی نوێ',
	'SPLIT_POSTS'	=> 'پەیامە دیاریکراوکان بەش بکە',
	'SPLIT_SUBJECT'	=> 'ناونیشانی بابەتی نوێ',
	'SPLIT_TOPIC_ALL'	=> 'بابەت بەش بکە لە پەیامە دیاریکراوەکانەوە',
	'SPLIT_TOPIC_ALL_CONFIRM'	=> 'دڵنیایت لە بەشکردنی ئەم بابەتە؟',
	'SPLIT_TOPIC_BEYOND'	=> 'بابەت بەش بکە لەسەر بابەتی دیاریکراوەوە',
	'SPLIT_TOPIC_BEYOND_CONFIRM'	=> 'دڵنیایت لە بەشکردنی ئەم بابەتە لەسەر پەیامی دیاریکراوەوە؟',
	'SPLIT_TOPIC_EXPLAIN'	=> 'بە بەکارهێنانی ئەم فۆڕمەی خوارەوە ئەتوانیت بابەتێک بەش بکەیت بۆ دوان، یان بە دیاریکردنی پەیامەکان تاک تاک یان بە بەشکردن لە پەیامێکی دیاریکراوەوە.',
	'THIS_PM_IP'				=> 'ئایپی بۆ ئەو پەیامە تایبەتە',
	'THIS_POST_IP'	=> 'IP بۆ ئەم پەیامە',
	'TOPICS_APPROVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان پەسەندکران.',
	'TOPICS_DELETED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی لە بنکەدراوە سڕدرانەوە.',
	'TOPICS_DISAPPROVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان پەسەند نەکران.',
	'TOPICS_FORKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی ڕوونووسکران.',
	'TOPICS_LOCKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان داخران.',
	'TOPICS_MOVED_SUCCESS'	=> 'بابەتە دیاریکراوەکان بە سەرکەوتوویی گواسترانەوە.',
	'TOPICS_RESYNC_SUCCESS'	=> 'بابەتە دەستنیشانکراوەکان زامنکرانەوە',
	'TOPICS_TYPE_CHANGED'	=> 'جۆرەکانی بابەت بە سەرکەوتوویی گۆڕدرا.',
	'TOPICS_UNLOCKED_SUCCESS'	=> 'بابەتە دیاریکراوەکان کرانەوە.',
	'TOPIC_APPROVED_SUCCESS'	=> 'بابەتی دیاریکراو پەسەندکرا.',
	'TOPIC_DELETED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی لە بنکەدراوە سڕدرایەوە.',
	'TOPIC_DISAPPROVED_SUCCESS'	=> 'بابەتی دیاریکراو پەسەند نەکرا.',
	'TOPIC_FORKED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی ڕوونووسکرا.',
	'TOPIC_LOCKED_SUCCESS'	=> 'بابەتی دیاریکراو داخرا.',
	'TOPIC_MOVED_SUCCESS'	=> 'بابەتی دیاریکراو بە سەرکەوتوویی گواسترایەوە.',
	'TOPIC_NOT_EXIST'	=> 'ئەو بابەتەی دیاریت کردووە بوونی نییە.',
	'TOPIC_RESYNC_SUCCESS'	=> 'بابەتە دەسنیشانکراوەکان زامنکرانەوە',
	'TOPIC_SPLIT_SUCCESS'	=> 'بابەتی دیاریکرا بە سەرکەوتوویی بەشکرا.',
	'TOPIC_TIME'	=> 'کاتی بابەت',
	'TOPIC_TYPE_CHANGED'	=> 'جۆری بابەت بە سەرکەوتوویی گۆڕدرا.',
	'TOPIC_UNLOCKED_SUCCESS'	=> 'بابەتی دیاریکراو کرایەوە.',
	'TOTAL_WARNINGS'	=> 'سەرجەم ئاگادارییەکان',
	'UNAPPROVED_POSTS_TOTAL'	=> 'کۆی گشتی <strong>%d</strong> پەیام چاوەڕوانی پەسەندکردنن.',
	'UNAPPROVED_POSTS_ZERO_TOTAL'	=> 'هیچ پەیامێک چاوەڕوانی پەسەندکردن نییە',
	'UNAPPROVED_POST_TOTAL'	=> 'کۆی گشتی <strong>1</strong> پەیام چاوەڕوانی پەسەندکردنن.',
	'UNLOCK'	=> 'کردنەوە',
	'UNLOCK_POST'	=> 'کردنەوەی پەیام',
	'UNLOCK_POST_EXPLAIN'	=> 'ڕێدان بە دەستکاریکردن',
	'UNLOCK_POST_POST'	=> 'پەیام بکەرەوە',
	'UNLOCK_POST_POST_CONFIRM'	=> 'دڵنیایت لە ڕێدان بە دەستکاریکردنی ئەم پەیامە؟',
	'UNLOCK_POST_POSTS'	=> 'پەیامە دیاریکراوەکان بکەرەوە',
	'UNLOCK_POST_POSTS_CONFIRM'	=> 'دڵنیایت لە ڕێدان بە دەستکاریکردنی پەیامە دیاریکراوەکان؟',
	'UNLOCK_TOPIC'	=> 'بابەت بکەرەوە',
	'UNLOCK_TOPIC_CONFIRM'	=> 'دڵنیایت لە کردنەوەی ئەم بابەتە؟',
	'UNLOCK_TOPICS'	=> 'بابەتە دیاریکراوەکان بکەرەوە',
	'UNLOCK_TOPICS_CONFIRM'	=> 'دڵنیایت لە کردنەوەی هەموو بابەتە دیاریکراوەکان؟',
	'USER_CANNOT_POST'	=> 'ناتوانیت لەم مەکۆیە پەیام بنووسیت.',
	'USER_CANNOT_REPORT'	=> 'ناتوانیت لەم مەکۆیە پەیام ڕاپۆرت بکەیت.',
	'USER_FEEDBACK_ADDED'	=> 'لێدوانی بەکارهێنەر بە سەرکەوتوویی زیادکرا.',
	'USER_WARNING_ADDED'	=> 'بەکارهێنەر بە سەرکەوتوویی ئاگادارکرایەوە.',
	'VIEW_DETAILS'	=> 'بینینی وردەکارییەکان',
	'VIEW_PM'	=> 'پەیامی تایبەت ببینە',
	'VIEW_POST'	=> 'بینینی پەیام',
	'WARNED_USERS'	=> 'بەکارهێنەرە ئاگادارکراوەکان',
	'WARNED_USERS_EXPLAIN'	=> 'ئەمە لیستی ئەو بەکارهێنەرانەیە کە ئاگاداریی بەسەرنەچوویان بۆ هاتووە.',
	'WARNING_PM_BODY'	=> 'ئەمەی خوارەوە ئاگادارییەکە کە بۆت هاتووە لەلایەن بەڕێوەبەر یان چاودێرێکەوە لە ماڵپەڕ.quote]%s[/quote]',
	'WARNING_PM_SUBJECT'	=> 'ئاگاداری مەکۆ هات',
	'WARNING_POST_DEFAULT'	=> 'ئەمە ئاگادارییەکە پەیوەست بەم پەیامەی خوارەوە کە تۆ نووسیوتە: %s.',
	'WARNINGS_ZERO_TOTAL'	=> 'هیچ ئاگادارییەک بوونی نییە.',
	'YOU_SELECTED_TOPIC'	=> 'تۆ دیاریت کرد بابەتی ژمارە %d: %s',

	'report_reasons'	=> array(

		'TITLE'	=> array(
			'WAREZ'	=> 'وارێز',
			'SPAM'	=> 'سپام',
			'OFF_TOPIC'	=> 'دەرچوون لە بابەت',
			'OTHER'	=> 'هیتر',
		),

	'FEEDBACK'				=> 'Feedback',
	'FORK'					=> 'Copy',
	'FORK_TOPIC'			=> 'Copy topic',
	'FORK_TOPIC_CONFIRM'	=> 'Are you sure you want to copy this topic?',
	'FORK_TOPICS'			=> 'Copy selected topics',
	'FORK_TOPICS_CONFIRM'	=> 'Are you sure you want to copy the selected topics?',
	'FORUM_DESC'			=> 'Description',
	'FORUM_NAME'			=> 'Forum name',
	'FORUM_NOT_EXIST'		=> 'The forum you selected does not exist.',
	'FORUM_NOT_POSTABLE'	=> 'The forum you selected cannot be posted to.',
	'FORUM_STATUS'			=> 'Forum status',
	'FORUM_STYLE'			=> 'Forum style',

		'DESCRIPTION'	=> array(
			'WAREZ'	=> 'پەیام بەستەری تیادایە بۆ پڕۆگرامی قاچاخ و نایاسایی.',
			'SPAM'	=> 'پەیامی ڕاپۆرتکراو مەبەست لە نووسینی تەنها پڕوپاگەندەیە بۆ ماڵپەڕ یان بەرهەمێک.',
			'OFF_TOPIC'	=> 'پەیامی ڕاپۆرتکراو لە بابەت دەرچووە.',
			'OTHER'	=> 'پەیامی ڕاپۆرتکراو لەگەڵ هیچ کام لەوانەی سەرەوە ناگونجێت، تکایە لەو خانەیەی خوارەوە بینووسە.',
		),

	'IP_INFO'				=> 'IP address information',
	'IPS_POSTED_FROM'		=> 'IP addresses this user has posted from',

	'LATEST_LOGS'				=> 'Latest 5 logged actions',
	'LATEST_REPORTED'			=> 'Latest 5 reports',
	'LATEST_REPORTED_PMS'		=> 'Latest 5 PM reports',
	'LATEST_UNAPPROVED'			=> 'Latest 5 posts awaiting approval',
	'LATEST_WARNING_TIME'		=> 'Latest warning issued',
	'LATEST_WARNINGS'			=> 'Latest 5 warnings',
	'LEAVE_SHADOW'				=> 'Leave shadow topic in place',
	'LIST_REPORTS'				=> array(
		1	=> '%d report',
		2	=> '%d reports',
	),
	'LOCK'						=> 'Lock',
	'LOCK_POST_POST'			=> 'Lock post',
	'LOCK_POST_POST_CONFIRM'	=> 'Are you sure you want to prevent editing this post?',
	'LOCK_POST_POSTS'			=> 'Lock selected posts',
	'LOCK_POST_POSTS_CONFIRM'	=> 'Are you sure you want to prevent editing the selected posts?',
	'LOCK_TOPIC_CONFIRM'		=> 'Are you sure you want to lock this topic?',
	'LOCK_TOPICS'				=> 'Lock selected topics',
	'LOCK_TOPICS_CONFIRM'		=> 'Are you sure you want to lock all selected topics?',
	'LOGS_CURRENT_TOPIC'		=> 'Currently viewing logs of:',
	'LOGIN_EXPLAIN_MCP'			=> 'To moderate this forum you must login.',
	'LOGVIEW_VIEWTOPIC'			=> 'View topic',
	'LOGVIEW_VIEWLOGS'			=> 'View topic log',
	'LOGVIEW_VIEWFORUM'			=> 'View forum',
	'LOOKUP_ALL'				=> 'Look up all IPs',
	'LOOKUP_IP'					=> 'Look up IP',

	'MARKED_NOTES_DELETED'		=> 'Successfully removed all marked user notes.',

	'MCP_ADD'						=> 'Add a warning',

	'MCP_BAN'					=> 'Banning',
	'MCP_BAN_EMAILS'			=> 'Ban emails',
	'MCP_BAN_IPS'				=> 'Ban IPs',
	'MCP_BAN_USERNAMES'			=> 'Ban Usernames',

	'MCP_LOGS'						=> 'Moderator logs',
	'MCP_LOGS_FRONT'				=> 'Front page',
	'MCP_LOGS_FORUM_VIEW'			=> 'Forum logs',
	'MCP_LOGS_TOPIC_VIEW'			=> 'Topic logs',

	'MCP_MAIN'						=> 'Main',
	'MCP_MAIN_FORUM_VIEW'			=> 'View forum',
	'MCP_MAIN_FRONT'				=> 'Front page',
	'MCP_MAIN_POST_DETAILS'			=> 'Post details',
	'MCP_MAIN_TOPIC_VIEW'			=> 'View topic',
	'MCP_MAKE_ANNOUNCEMENT'			=> 'Modify to “Announcement”',
	'MCP_MAKE_ANNOUNCEMENT_CONFIRM'	=> 'Are you sure you want to change this topic to an “Announcement”?',
	'MCP_MAKE_ANNOUNCEMENTS'		=> 'Modify to “Announcements”',
	'MCP_MAKE_ANNOUNCEMENTS_CONFIRM'=> 'Are you sure you want to change the selected topics to “Announcements”?',
	'MCP_MAKE_GLOBAL'				=> 'Modify to “Global announcement”',
	'MCP_MAKE_GLOBAL_CONFIRM'		=> 'Are you sure you want to change this topic to a “Global announcement”?',
	'MCP_MAKE_GLOBALS'				=> 'Modify to “Global announcements”',
	'MCP_MAKE_GLOBALS_CONFIRM'		=> 'Are you sure you want to change the selected topics to “Global announcements”?',
	'MCP_MAKE_STICKY'				=> 'Modify to “Sticky”',
	'MCP_MAKE_STICKY_CONFIRM'		=> 'Are you sure you want to change this topic to a “Sticky”?',
	'MCP_MAKE_STICKIES'				=> 'Modify to “Stickies”',
	'MCP_MAKE_STICKIES_CONFIRM'		=> 'Are you sure you want to change the selected topics to “Stickies”?',
	'MCP_MAKE_NORMAL'				=> 'Modify to “Standard Topic”',
	'MCP_MAKE_NORMAL_CONFIRM'		=> 'Are you sure you want to change this topic to a “Standard Topic”?',
	'MCP_MAKE_NORMALS'				=> 'Modify to “Standard Topics”',
	'MCP_MAKE_NORMALS_CONFIRM'		=> 'Are you sure you want to change the selected topics to “Standard Topics”?',

	'MCP_NOTES'						=> 'User notes',
	'MCP_NOTES_FRONT'				=> 'Front page',
	'MCP_NOTES_USER'				=> 'User details',

	'MCP_POST_REPORTS'				=> 'Reports issued on this post',

	'MCP_PM_REPORTS'				=> 'Reported PMs',
	'MCP_PM_REPORT_DETAILS'			=> 'PM Report details',
	'MCP_PM_REPORTS_CLOSED'			=> 'Closed PM reports',
	'MCP_PM_REPORTS_CLOSED_EXPLAIN'	=> 'This is a list of all reports about private messages which have previously been resolved.',
	'MCP_PM_REPORTS_OPEN'			=> 'Open PM reports',
	'MCP_PM_REPORTS_OPEN_EXPLAIN'	=> 'This is a list of all reported private messages which are still to be handled.',

	'MCP_REPORTS'					=> 'Reported messages',
	'MCP_REPORT_DETAILS'			=> 'Report details',
	'MCP_REPORTS_CLOSED'			=> 'Closed reports',
	'MCP_REPORTS_CLOSED_EXPLAIN'	=> 'This is a list of all reports about posts which have previously been resolved.',
	'MCP_REPORTS_OPEN'				=> 'Open reports',
	'MCP_REPORTS_OPEN_EXPLAIN'		=> 'This is a list of all reported posts which are still to be handled.',

	'MCP_QUEUE'								=> 'Moderation queue',
	'MCP_QUEUE_APPROVE_DETAILS'				=> 'Approve details',
	'MCP_QUEUE_UNAPPROVED_POSTS'			=> 'Posts awaiting approval',
	'MCP_QUEUE_UNAPPROVED_POSTS_EXPLAIN'	=> 'This is a list of all posts which require approving before they will be visible to users.',
	'MCP_QUEUE_UNAPPROVED_TOPICS'			=> 'Topics awaiting approval',
	'MCP_QUEUE_UNAPPROVED_TOPICS_EXPLAIN'	=> 'This is a list of all topics which require approving before they will be visible to users.',
	'MCP_QUEUE_DELETED_POSTS'				=> 'Deleted posts',
	'MCP_QUEUE_DELETED_POSTS_EXPLAIN'		=> 'This is a list of all soft deleted posts. You can restore or permanently delete the posts from this screen.',
	'MCP_QUEUE_DELETED_TOPICS'				=> 'Deleted topics',
	'MCP_QUEUE_DELETED_TOPICS_EXPLAIN'		=> 'This is a list of all soft deleted topics. You can restore or permanently delete the topics from this screen.',

	'MCP_VIEW_USER'			=> 'View warnings for a specific user',

	'MCP_WARN'				=> 'Warnings',
	'MCP_WARN_FRONT'		=> 'Front page',
	'MCP_WARN_LIST'			=> 'List warnings',
	'MCP_WARN_POST'			=> 'Warn for specific post',
	'MCP_WARN_USER'			=> 'Warn user',

	'MERGE_POSTS_CONFIRM'	=> 'Are you sure you want to move the selected posts?',
	'MERGE_TOPIC_EXPLAIN'	=> 'Using the form below you can move selected posts into another topic. The posts will be split from this topic and merged into the other topic. These posts will not be reordered and will appear as if the users posted them to the new topic.<br />Please enter the destination topic id or click on “Select topic” to search for one.',
	'MERGE_TOPIC_ID'		=> 'Destination topic identification number',
	'MERGE_TOPICS'			=> 'Merge topics',
	'MERGE_TOPICS_CONFIRM'	=> 'Are you sure you want to merge the selected topics?',
	'MODERATE_FORUM'		=> 'Moderate forum',
	'MODERATE_TOPIC'		=> 'Moderate topic',
	'MODERATE_POST'			=> 'Moderate post',
	'MOD_OPTIONS'			=> 'Moderator options',
	'MORE_INFO'				=> 'Further information',
	'MOST_WARNINGS'			=> 'Users with most warnings',
	'MOVE_TOPIC_CONFIRM'	=> 'Are you sure you want to move the topic into a new forum?',
	'MOVE_TOPICS'			=> 'Move selected topics',
	'MOVE_TOPICS_CONFIRM'	=> 'Are you sure you want to move the selected topics into a new forum?',

	'NOTIFY_POSTER_APPROVAL'		=> 'Notify poster about approval?',
	'NOTIFY_POSTER_DISAPPROVAL'		=> 'Notify poster about disapproval?',
	'NOTIFY_USER_WARN'				=> 'Notify user about warning?',
	'NOT_MODERATOR'					=> 'You are not a moderator of this forum.',
	'NO_DESTINATION_FORUM'			=> 'Please select a forum for destination.',
	'NO_DESTINATION_FORUM_FOUND'	=> 'There is no destination forum available.',
	'NO_ENTRIES'					=> 'No log entries for this period.',
	'NO_FEEDBACK'					=> 'No feedback exists for this user.',
	'NO_FINAL_TOPIC_SELECTED'		=> 'You have to select a destination topic for merging posts.',
	'NO_MATCHES_FOUND'				=> 'No matches found.',
	'NO_POST'						=> 'You have to select a post in order to warn the user for a post.',
	'NO_POST_REPORT'				=> 'This post was not reported.',
	'NO_POST_SELECTED'				=> 'You must select at least one post to perform this action.',
	'NO_POSTS_DELETED'				=> 'There are no deleted posts.',
	'NO_POSTS_QUEUE'				=> 'There are no posts waiting for approval.',
	'NO_REASON_DISAPPROVAL'			=> 'Please give an appropriate reason for disapproval.',
	'NO_REPORT'						=> 'No report found',
	'NO_REPORTS'					=> 'No reports found',
	'NO_REPORT_SELECTED'			=> 'You must select at least one report to perform this action.',
	'NO_TOPIC_ICON'					=> 'None',
	'NO_TOPIC_SELECTED'				=> 'You must select at least one topic to perform this action.',
	'NO_TOPICS_DELETED'				=> 'There are no deleted topics.',
	'NO_TOPICS_QUEUE'				=> 'There are no topics waiting for approval.',

	'ONLY_TOPIC'			=> 'Only topic “%s”',
	'OTHER_USERS'			=> 'Other users posting from this IP',

	'QUICKMOD_ACTION_NOT_ALLOWED' => "%s not allowed as quickmod",

	'PM_REPORT_CLOSED_SUCCESS'	=> 'The selected PM report has been closed successfully.',
	'PM_REPORT_DELETED_SUCCESS'	=> 'The selected PM report has been deleted successfully.',
	'PM_REPORTED_SUCCESS'		=> 'This private message has been successfully reported.',
	'PM_REPORTS_CLOSED_SUCCESS'	=> 'The selected PM reports have been closed successfully.',
	'PM_REPORTS_DELETED_SUCCESS'=> 'The selected PM reports have been deleted successfully.',
	'PM_REPORTS_TOTAL'			=> array(
		0	=> 'There are no PM reports to review.',
		1	=> 'In total there is <strong>1</strong> PM report to review.',
		2	=> 'In total there are <strong>%d</strong> PM reports to review.',
	),
	'PM_REPORT_DETAILS'			=> 'Private message report details',
	'POSTER'					=> 'Poster',
	'POSTS_APPROVED_SUCCESS'	=> 'The selected posts have been approved.',
	'POSTS_DELETED_SUCCESS'		=> 'The selected posts have been successfully removed from the database.',
	'POSTS_DISAPPROVED_SUCCESS'	=> 'The selected posts have been disapproved.',
	'POSTS_LOCKED_SUCCESS'		=> 'The selected posts have been locked successfully.',
	'POSTS_MERGED_SUCCESS'		=> 'The selected posts have been merged.',
	'POSTS_PER_PAGE'			=> 'Posts per page',
	'POSTS_PER_PAGE_EXPLAIN'	=> '(Set to 0 to view all posts.)',
	'POSTS_RESTORED_SUCCESS'	=> 'The selected posts have been restored successfully.',
	'POSTS_UNLOCKED_SUCCESS'	=> 'The selected posts have been unlocked successfully.',
	'POST_APPROVED_SUCCESS'		=> 'The selected post has been approved.',
	'POST_DELETED_SUCCESS'		=> 'The selected post has been successfully removed from the database.',
	'POST_DISAPPROVED_SUCCESS'	=> 'The selected post has been disapproved.',
	'POST_LOCKED_SUCCESS'		=> 'Post locked successfully.',
	'POST_NOT_EXIST'			=> 'The post you requested does not exist.',
	'POST_REPORTED_SUCCESS'		=> 'This post has been successfully reported.',
	'POST_RESTORED_SUCCESS'		=> 'This post has been restored successfully.',
	'POST_UNLOCKED_SUCCESS'		=> 'Post unlocked successfully.',

	'READ_USERNOTES'			=> 'User notes',
	'READ_WARNINGS'				=> 'User warnings',
	'REPORTER'					=> 'Reporter',
	'REPORTED'					=> 'Reported',
	'REPORTED_BY'				=> 'Reported by',
	'REPORTED_ON_DATE'			=> 'on',
	'REPORTS_CLOSED_SUCCESS'	=> 'The selected reports have been closed successfully.',
	'REPORTS_DELETED_SUCCESS'	=> 'The selected reports have been deleted successfully.',
	'REPORTS_TOTAL'				=> array(
		0	=> 'There are no reports to review.',
		1	=> 'In total there is <strong>1</strong> report to review.',
		2	=> 'In total there are <strong>%d</strong> reports to review.',
	),
	'REPORT_CLOSED'				=> 'This report has already been closed.',
	'REPORT_CLOSED_SUCCESS'		=> 'The selected report has been closed successfully.',
	'REPORT_DELETED_SUCCESS'	=> 'The selected report has been deleted successfully.',
	'REPORT_DETAILS'			=> 'Report details',
	'REPORT_MESSAGE'			=> 'Report this message',
	'REPORT_MESSAGE_EXPLAIN'	=> 'Use this form to report the selected private message. Reporting should generally be used only if the message breaks forum rules. <strong>Reporting a private message will make its contents visible to all moderators.</strong>',
	'REPORT_NOTIFY'				=> 'Notify me',
	'REPORT_NOTIFY_EXPLAIN'		=> 'Informs you when your report is dealt with.',
	'REPORT_POST_EXPLAIN'		=> 'Use this form to report the selected post to the forum moderators and board administrators. Reporting should generally be used only if the post breaks forum rules.',
	'REPORT_REASON'				=> 'Report reason',
	'REPORT_TIME'				=> 'Report time',
	'RESTORE'					=> 'Restore',
	'RESTORE_POST'				=> 'Restore post',
	'RESTORE_POST_CONFIRM'		=> 'Are you sure you want to restore this post?',
	'RESTORE_POSTS'				=> 'Restore posts',
	'RESTORE_POSTS_CONFIRM'		=> 'Are you sure you want to restore the selected posts?',
	'RESTORE_TOPIC'				=> 'Restore topic',
	'RESTORE_TOPIC_CONFIRM'		=> 'Are you sure you want to restore this topic?',
	'RESTORE_TOPICS'			=> 'Restore topics',
	'RESTORE_TOPICS_CONFIRM'	=> 'Are you sure you want to restore the selected topics?',
	'RESYNC'					=> 'Resync',
	'RETURN_MESSAGE'			=> '%sReturn to the message%s',
	'RETURN_NEW_FORUM'			=> '%sGo to the new forum%s',
	'RETURN_NEW_TOPIC'			=> '%sGo to the new topic%s',
	'RETURN_PM'					=> '%sReturn to the private message%s',
	'RETURN_POST'				=> '%sReturn to the post%s',
	'RETURN_QUEUE'				=> '%sReturn to the queue%s',
	'RETURN_REPORTS'			=> '%sReturn to the reports%s',
	'RETURN_TOPIC_SIMPLE'		=> '%sReturn to the topic%s',

	'SEARCH_POSTS_BY_USER'				=> 'Search posts by',
	'SELECT_ACTION'						=> 'Select desired action',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENT'	=> 'Please select the forum you wish this global announcement to be displayed.',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENTS'	=> 'One or more of the selected topics are global announcements. Please select the forum you wish these to be displayed.',
	'SELECT_MERGE'						=> 'Select for merge',
	'SELECT_TOPICS_FROM'				=> 'Select topics from',
	'SELECT_TOPIC'						=> 'Select topic',
	'SELECT_USER'						=> 'Select user',
	'SORT_ACTION'						=> 'Log action',
	'SORT_DATE'							=> 'Date',
	'SORT_IP'							=> 'IP address',
	'SORT_WARNINGS'						=> 'Warnings',
	'SPLIT_AFTER'						=> 'Split topic from selected post onwards',
	'SPLIT_FORUM'						=> 'Forum for new topic',
	'SPLIT_POSTS'						=> 'Split selected posts',
	'SPLIT_SUBJECT'						=> 'New topic title',
	'SPLIT_TOPIC_ALL'					=> 'Split topic from selected posts',
	'SPLIT_TOPIC_ALL_CONFIRM'			=> 'Are you sure you want to split this topic?',
	'SPLIT_TOPIC_BEYOND'				=> 'Split topic at selected post',
	'SPLIT_TOPIC_BEYOND_CONFIRM'		=> 'Are you sure you want to split this topic at the selected post?',
	'SPLIT_TOPIC_EXPLAIN'				=> 'Using the form below you can split a topic in two, either by selecting the posts individually or by splitting at a selected post.',

	'THIS_PM_IP'				=> 'IP for this private message',
	'THIS_POST_IP'				=> 'IP for this post',
	'TOPICS_APPROVED_SUCCESS'	=> 'The selected topics have been approved.',
	'TOPICS_DELETED_SUCCESS'	=> 'The selected topics have been successfully removed from the database.',
	'TOPICS_DISAPPROVED_SUCCESS'=> 'The selected topics have been disapproved.',
	'TOPICS_FORKED_SUCCESS'		=> 'The selected topics have been copied successfully.',
	'TOPICS_LOCKED_SUCCESS'		=> 'The selected topics have been locked.',
	'TOPICS_MOVED_SUCCESS'		=> 'The selected topics have been moved successfully.',
	'TOPICS_RESTORED_SUCCESS'	=> 'The selected topics have been restored successfully.',
	'TOPICS_RESYNC_SUCCESS'		=> 'The selected topics have been resynchronised.',
	'TOPICS_TYPE_CHANGED'		=> 'Topic types changed successfully.',
	'TOPICS_UNLOCKED_SUCCESS'	=> 'The selected topics have been unlocked.',
	'TOPIC_APPROVED_SUCCESS'	=> 'The selected topic has been approved.',
	'TOPIC_DELETED_SUCCESS'		=> 'The selected topic has been successfully removed from the database.',
	'TOPIC_DISAPPROVED_SUCCESS'	=> 'The selected topic has been disapproved.',
	'TOPIC_FORKED_SUCCESS'		=> 'The selected topic has been copied successfully.',
	'TOPIC_LOCKED_SUCCESS'		=> 'The selected topic has been locked.',
	'TOPIC_MOVED_SUCCESS'		=> 'The selected topic has been moved successfully.',
	'TOPIC_NOT_EXIST'			=> 'The topic you selected does not exist.',
	'TOPIC_RESTORED_SUCCESS'	=> 'The selected topic has been restored successfully.',
	'TOPIC_RESYNC_SUCCESS'		=> 'The selected topic has been resynchronised.',
	'TOPIC_SPLIT_SUCCESS'		=> 'The selected topic has been split successfully.',
	'TOPIC_TIME'				=> 'Topic time',
	'TOPIC_TYPE_CHANGED'		=> 'Topic type changed successfully.',
	'TOPIC_UNLOCKED_SUCCESS'	=> 'The selected topic has been unlocked.',
	'TOTAL_WARNINGS'			=> 'Total Warnings',

	'UNAPPROVED_POSTS_TOTAL'		=> array(
		0	=> 'There are no posts waiting for approval.',
		1	=> 'In total there is <strong>1</strong> post waiting for approval.',
		2	=> 'In total there are <strong>%d</strong> posts waiting for approval.',
	),
	'UNLOCK'						=> 'Unlock',
	'UNLOCK_POST'					=> 'Unlock post',
	'UNLOCK_POST_EXPLAIN'			=> 'Allow editing',
	'UNLOCK_POST_POST'				=> 'Unlock post',
	'UNLOCK_POST_POST_CONFIRM'		=> 'Are you sure you want to allow editing this post?',
	'UNLOCK_POST_POSTS'				=> 'Unlock selected posts',
	'UNLOCK_POST_POSTS_CONFIRM'		=> 'Are you sure you want to allow editing the selected posts?',
	'UNLOCK_TOPIC'					=> 'Unlock topic',
	'UNLOCK_TOPIC_CONFIRM'			=> 'Are you sure you want to unlock this topic?',
	'UNLOCK_TOPICS'					=> 'Unlock selected topics',
	'UNLOCK_TOPICS_CONFIRM'			=> 'Are you sure you want to unlock all selected topics?',
	'USER_CANNOT_POST'				=> 'You cannot post in this forum.',
	'USER_CANNOT_REPORT'			=> 'You cannot report posts in this forum.',
	'USER_FEEDBACK_ADDED'			=> 'User feedback added successfully.',
	'USER_WARNING_ADDED'			=> 'User warned successfully.',

	'VIEW_DETAILS'			=> 'View details',
	'VIEW_PM'				=> 'View private message',
	'VIEW_POST'				=> 'View post',

	'WARNED_USERS'			=> 'Warned users',
	'WARNED_USERS_EXPLAIN'	=> 'This is a list of users with unexpired warnings issued to them.',
	'WARNING_PM_BODY'		=> 'The following is a warning which has been issued to you by an administrator or moderator of this site.[quote]%s[/quote]',
	'WARNING_PM_SUBJECT'	=> 'Board warning issued',
	'WARNING_POST_DEFAULT'	=> 'This is a warning regarding the following post made by you: %s .',
	'NO_WARNINGS'	=> 'No warnings exist.',

	'YOU_SELECTED_TOPIC'	=> 'You selected topic number %d: %s.',

	'report_reasons'		=> array(
		'TITLE'	=> array(
			'WAREZ'		=> 'Warez',
			'SPAM'		=> 'Spam',
			'OFF_TOPIC'	=> 'Off-topic',
			'OTHER'		=> 'Other',
		),
		'DESCRIPTION' => array(
			'WAREZ'		=> 'The message contains links to illegal or pirated software.',
			'SPAM'		=> 'The reported message has the only purpose to advertise for a website or another product.',
			'OFF_TOPIC'	=> 'The reported message is off topic.',
			'OTHER'		=> 'The reported message does not fit into any other category, please use the further information field.',
		),
	),
));
